### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Rest.Interfaces.IUsersRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IUsersRestService
  id: IUsersRestService
  parent: OpenSettings.Services.Rest.Interfaces
  children: []
  langs:
  - csharp
  - vb
  name: IUsersRestService
  nameWithType: IUsersRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IUsersRestService
  type: Interface
  source:
    remote:
      path: src/OpenSettings/Services/Rest/Interfaces/IUsersRestService.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IUsersRestService
    path: ../../../open-settings/src/OpenSettings/Services/Rest/Interfaces/IUsersRestService.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.Rest.Interfaces
  syntax:
    content: 'public interface IUsersRestService : IUsersService'
    content.vb: Public Interface IUsersRestService Inherits IUsersService
  inheritedMembers:
  - OpenSettings.Services.Interfaces.IUsersService.GetOrCreateUserAsync(OpenSettings.Models.Inputs.GetOrCreateUserInput,System.Threading.CancellationToken)
references:
- uid: OpenSettings.Services.Rest.Interfaces
  commentId: N:OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Rest.Interfaces
  nameWithType: OpenSettings.Services.Rest.Interfaces
  fullName: OpenSettings.Services.Rest.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
- uid: OpenSettings.Services.Interfaces.IUsersService.GetOrCreateUserAsync(OpenSettings.Models.Inputs.GetOrCreateUserInput,System.Threading.CancellationToken)
  commentId: M:OpenSettings.Services.Interfaces.IUsersService.GetOrCreateUserAsync(OpenSettings.Models.Inputs.GetOrCreateUserInput,System.Threading.CancellationToken)
  parent: OpenSettings.Services.Interfaces.IUsersService
  isExternal: true
  href: OpenSettings.Services.Interfaces.IUsersService.html#OpenSettings_Services_Interfaces_IUsersService_GetOrCreateUserAsync_OpenSettings_Models_Inputs_GetOrCreateUserInput_System_Threading_CancellationToken_
  name: GetOrCreateUserAsync(GetOrCreateUserInput, CancellationToken)
  nameWithType: IUsersService.GetOrCreateUserAsync(GetOrCreateUserInput, CancellationToken)
  fullName: OpenSettings.Services.Interfaces.IUsersService.GetOrCreateUserAsync(OpenSettings.Models.Inputs.GetOrCreateUserInput, System.Threading.CancellationToken)
  spec.csharp:
  - uid: OpenSettings.Services.Interfaces.IUsersService.GetOrCreateUserAsync(OpenSettings.Models.Inputs.GetOrCreateUserInput,System.Threading.CancellationToken)
    name: GetOrCreateUserAsync
    href: OpenSettings.Services.Interfaces.IUsersService.html#OpenSettings_Services_Interfaces_IUsersService_GetOrCreateUserAsync_OpenSettings_Models_Inputs_GetOrCreateUserInput_System_Threading_CancellationToken_
  - name: (
  - uid: OpenSettings.Models.Inputs.GetOrCreateUserInput
    name: GetOrCreateUserInput
    href: OpenSettings.Models.Inputs.GetOrCreateUserInput.html
  - name: ','
  - name: " "
  - uid: System.Threading.CancellationToken
    name: CancellationToken
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken
  - name: )
  spec.vb:
  - uid: OpenSettings.Services.Interfaces.IUsersService.GetOrCreateUserAsync(OpenSettings.Models.Inputs.GetOrCreateUserInput,System.Threading.CancellationToken)
    name: GetOrCreateUserAsync
    href: OpenSettings.Services.Interfaces.IUsersService.html#OpenSettings_Services_Interfaces_IUsersService_GetOrCreateUserAsync_OpenSettings_Models_Inputs_GetOrCreateUserInput_System_Threading_CancellationToken_
  - name: (
  - uid: OpenSettings.Models.Inputs.GetOrCreateUserInput
    name: GetOrCreateUserInput
    href: OpenSettings.Models.Inputs.GetOrCreateUserInput.html
  - name: ','
  - name: " "
  - uid: System.Threading.CancellationToken
    name: CancellationToken
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken
  - name: )
- uid: OpenSettings.Services.Interfaces.IUsersService
  commentId: T:OpenSettings.Services.Interfaces.IUsersService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IUsersService.html
  name: IUsersService
  nameWithType: IUsersService
  fullName: OpenSettings.Services.Interfaces.IUsersService
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
