### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest
  commentId: T:OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest
  id: DeleteInstanceRequest
  parent: OpenSettings.AspNetCore.Models.Requests
  children:
  - OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId
  langs:
  - csharp
  - vb
  name: DeleteInstanceRequest
  nameWithType: DeleteInstanceRequest
  fullName: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest
  type: Class
  source:
    remote:
      path: src/OpenSettings.AspNetCore/Models/Requests/DeleteInstanceRequest.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: DeleteInstanceRequest
    path: ../../../open-settings/src/OpenSettings.AspNetCore/Models/Requests/DeleteInstanceRequest.cs
    startLine: 4
  assemblies:
  - OpenSettings.AspNetCore
  namespace: OpenSettings.AspNetCore.Models.Requests
  syntax:
    content: public class DeleteInstanceRequest
    content.vb: Public Class DeleteInstanceRequest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId
  commentId: P:OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId
  id: InstanceId
  parent: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest
  langs:
  - csharp
  - vb
  name: InstanceId
  nameWithType: DeleteInstanceRequest.InstanceId
  fullName: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore/Models/Requests/DeleteInstanceRequest.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: InstanceId
    path: ../../../open-settings/src/OpenSettings.AspNetCore/Models/Requests/DeleteInstanceRequest.cs
    startLine: 6
  assemblies:
  - OpenSettings.AspNetCore
  namespace: OpenSettings.AspNetCore.Models.Requests
  syntax:
    content: >-
      [FromRoute]

      public string InstanceId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <FromRoute>

      Public Property InstanceId As String
  overload: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId*
  attributes:
  - type: Microsoft.AspNetCore.Mvc.FromRouteAttribute
    ctor: Microsoft.AspNetCore.Mvc.FromRouteAttribute.#ctor
    arguments: []
references:
- uid: OpenSettings.AspNetCore.Models.Requests
  commentId: N:OpenSettings.AspNetCore.Models.Requests
  href: OpenSettings.html
  name: OpenSettings.AspNetCore.Models.Requests
  nameWithType: OpenSettings.AspNetCore.Models.Requests
  fullName: OpenSettings.AspNetCore.Models.Requests
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models
    name: Models
    href: OpenSettings.AspNetCore.Models.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models.Requests
    name: Requests
    href: OpenSettings.AspNetCore.Models.Requests.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models
    name: Models
    href: OpenSettings.AspNetCore.Models.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models.Requests
    name: Requests
    href: OpenSettings.AspNetCore.Models.Requests.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId*
  commentId: Overload:OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId
  href: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.html#OpenSettings_AspNetCore_Models_Requests_DeleteInstanceRequest_InstanceId
  name: InstanceId
  nameWithType: DeleteInstanceRequest.InstanceId
  fullName: OpenSettings.AspNetCore.Models.Requests.DeleteInstanceRequest.InstanceId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
