### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Services.Interfaces
  commentId: N:OpenSettings.AspNetCore.Services.Interfaces
  id: OpenSettings.AspNetCore.Services.Interfaces
  children:
  - OpenSettings.AspNetCore.Services.Interfaces.IInstanceUrlResolverService
  - OpenSettings.AspNetCore.Services.Interfaces.IOpenSettingsTokenService
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore.Services.Interfaces
  nameWithType: OpenSettings.AspNetCore.Services.Interfaces
  fullName: OpenSettings.AspNetCore.Services.Interfaces
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore
references:
- uid: OpenSettings.AspNetCore.Services.Interfaces.IInstanceUrlResolverService
  commentId: T:OpenSettings.AspNetCore.Services.Interfaces.IInstanceUrlResolverService
  href: OpenSettings.AspNetCore.Services.Interfaces.IInstanceUrlResolverService.html
  name: IInstanceUrlResolverService
  nameWithType: IInstanceUrlResolverService
  fullName: OpenSettings.AspNetCore.Services.Interfaces.IInstanceUrlResolverService
- uid: OpenSettings.AspNetCore.Services.Interfaces.IOpenSettingsTokenService
  commentId: T:OpenSettings.AspNetCore.Services.Interfaces.IOpenSettingsTokenService
  parent: OpenSettings.AspNetCore.Services.Interfaces
  href: OpenSettings.AspNetCore.Services.Interfaces.IOpenSettingsTokenService.html
  name: IOpenSettingsTokenService
  nameWithType: IOpenSettingsTokenService
  fullName: OpenSettings.AspNetCore.Services.Interfaces.IOpenSettingsTokenService
- uid: OpenSettings.AspNetCore.Services.Interfaces
  commentId: N:OpenSettings.AspNetCore.Services.Interfaces
  href: OpenSettings.html
  name: OpenSettings.AspNetCore.Services.Interfaces
  nameWithType: OpenSettings.AspNetCore.Services.Interfaces
  fullName: OpenSettings.AspNetCore.Services.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Services
    name: Services
    href: OpenSettings.AspNetCore.Services.html
  - name: .
  - uid: OpenSettings.AspNetCore.Services.Interfaces
    name: Interfaces
    href: OpenSettings.AspNetCore.Services.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Services
    name: Services
    href: OpenSettings.AspNetCore.Services.html
  - name: .
  - uid: OpenSettings.AspNetCore.Services.Interfaces
    name: Interfaces
    href: OpenSettings.AspNetCore.Services.Interfaces.html
