### YamlMime:ManagedReference
items:
- uid: OpenSettings.Helpers
  commentId: N:OpenSettings.Helpers
  id: OpenSettings.Helpers
  children:
  - OpenSettings.Helpers.Helper
  - OpenSettings.Helpers.JsonHelper
  - OpenSettings.Helpers.RsaPkcs8Helper
  - OpenSettings.Helpers.VersionHelper
  langs:
  - csharp
  - vb
  name: OpenSettings.Helpers
  nameWithType: OpenSettings.Helpers
  fullName: OpenSettings.Helpers
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Helpers.Helper
  commentId: T:OpenSettings.Helpers.Helper
  href: OpenSettings.Helpers.Helper.html
  name: Helper
  nameWithType: Helper
  fullName: OpenSettings.Helpers.Helper
- uid: OpenSettings.Helpers.JsonHelper
  commentId: T:OpenSettings.Helpers.JsonHelper
  href: OpenSettings.Helpers.JsonHelper.html
  name: JsonHelper
  nameWithType: JsonHelper
  fullName: OpenSettings.Helpers.JsonHelper
- uid: OpenSettings.Helpers.RsaPkcs8Helper
  commentId: T:OpenSettings.Helpers.RsaPkcs8Helper
  href: OpenSettings.Helpers.RsaPkcs8Helper.html
  name: RsaPkcs8Helper
  nameWithType: RsaPkcs8Helper
  fullName: OpenSettings.Helpers.RsaPkcs8Helper
- uid: OpenSettings.Helpers.VersionHelper
  commentId: T:OpenSettings.Helpers.VersionHelper
  href: OpenSettings.Helpers.VersionHelper.html
  name: VersionHelper
  nameWithType: VersionHelper
  fullName: OpenSettings.Helpers.VersionHelper
