### YamlMime:ManagedReference
items:
- uid: OpenSettings.Domains.Redis
  commentId: N:OpenSettings.Domains.Redis
  id: OpenSettings.Domains.Redis
  children:
  - OpenSettings.Domains.Redis.IOpenSettingsDistributedCache
  - OpenSettings.Domains.Redis.OpenSettingsDistributedMemoryCache
  - OpenSettings.Domains.Redis.OpenSettingsDistributedRedisCache
  langs:
  - csharp
  - vb
  name: OpenSettings.Domains.Redis
  nameWithType: OpenSettings.Domains.Redis
  fullName: OpenSettings.Domains.Redis
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Domains.Redis.IOpenSettingsDistributedCache
  commentId: T:OpenSettings.Domains.Redis.IOpenSettingsDistributedCache
  parent: OpenSettings.Domains.Redis
  href: OpenSettings.Domains.Redis.IOpenSettingsDistributedCache.html
  name: IOpenSettingsDistributedCache
  nameWithType: IOpenSettingsDistributedCache
  fullName: OpenSettings.Domains.Redis.IOpenSettingsDistributedCache
- uid: OpenSettings.Domains.Redis.OpenSettingsDistributedMemoryCache
  commentId: T:OpenSettings.Domains.Redis.OpenSettingsDistributedMemoryCache
  href: OpenSettings.Domains.Redis.OpenSettingsDistributedMemoryCache.html
  name: OpenSettingsDistributedMemoryCache
  nameWithType: OpenSettingsDistributedMemoryCache
  fullName: OpenSettings.Domains.Redis.OpenSettingsDistributedMemoryCache
- uid: OpenSettings.Domains.Redis.OpenSettingsDistributedRedisCache
  commentId: T:OpenSettings.Domains.Redis.OpenSettingsDistributedRedisCache
  href: OpenSettings.Domains.Redis.OpenSettingsDistributedRedisCache.html
  name: OpenSettingsDistributedRedisCache
  nameWithType: OpenSettingsDistributedRedisCache
  fullName: OpenSettings.Domains.Redis.OpenSettingsDistributedRedisCache
- uid: OpenSettings.Domains.Redis
  commentId: N:OpenSettings.Domains.Redis
  href: OpenSettings.html
  name: OpenSettings.Domains.Redis
  nameWithType: OpenSettings.Domains.Redis
  fullName: OpenSettings.Domains.Redis
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Redis
    name: Redis
    href: OpenSettings.Domains.Redis.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Redis
    name: Redis
    href: OpenSettings.Domains.Redis.html
