### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.LicenseEdition
  commentId: T:OpenSettings.Models.LicenseEdition
  id: LicenseEdition
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.LicenseEdition.Community
  - OpenSettings.Models.LicenseEdition.Enterprise
  - OpenSettings.Models.LicenseEdition.Personal
  - OpenSettings.Models.LicenseEdition.Professional
  - OpenSettings.Models.LicenseEdition.Trial
  langs:
  - csharp
  - vb
  name: LicenseEdition
  nameWithType: LicenseEdition
  fullName: OpenSettings.Models.LicenseEdition
  type: Enum
  source:
    remote:
      path: src/OpenSettings/Models/LicenseEdition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: LicenseEdition
    path: ../../../open-settings/src/OpenSettings/Models/LicenseEdition.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public enum LicenseEdition
    content.vb: Public Enum LicenseEdition
- uid: OpenSettings.Models.LicenseEdition.Community
  commentId: F:OpenSettings.Models.LicenseEdition.Community
  id: Community
  parent: OpenSettings.Models.LicenseEdition
  langs:
  - csharp
  - vb
  name: Community
  nameWithType: LicenseEdition.Community
  fullName: OpenSettings.Models.LicenseEdition.Community
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/LicenseEdition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Community
    path: ../../../open-settings/src/OpenSettings/Models/LicenseEdition.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Community = 100
    return:
      type: OpenSettings.Models.LicenseEdition
- uid: OpenSettings.Models.LicenseEdition.Personal
  commentId: F:OpenSettings.Models.LicenseEdition.Personal
  id: Personal
  parent: OpenSettings.Models.LicenseEdition
  langs:
  - csharp
  - vb
  name: Personal
  nameWithType: LicenseEdition.Personal
  fullName: OpenSettings.Models.LicenseEdition.Personal
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/LicenseEdition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Personal
    path: ../../../open-settings/src/OpenSettings/Models/LicenseEdition.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Personal = 200
    return:
      type: OpenSettings.Models.LicenseEdition
- uid: OpenSettings.Models.LicenseEdition.Professional
  commentId: F:OpenSettings.Models.LicenseEdition.Professional
  id: Professional
  parent: OpenSettings.Models.LicenseEdition
  langs:
  - csharp
  - vb
  name: Professional
  nameWithType: LicenseEdition.Professional
  fullName: OpenSettings.Models.LicenseEdition.Professional
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/LicenseEdition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Professional
    path: ../../../open-settings/src/OpenSettings/Models/LicenseEdition.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Professional = 300
    return:
      type: OpenSettings.Models.LicenseEdition
- uid: OpenSettings.Models.LicenseEdition.Trial
  commentId: F:OpenSettings.Models.LicenseEdition.Trial
  id: Trial
  parent: OpenSettings.Models.LicenseEdition
  langs:
  - csharp
  - vb
  name: Trial
  nameWithType: LicenseEdition.Trial
  fullName: OpenSettings.Models.LicenseEdition.Trial
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/LicenseEdition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Trial
    path: ../../../open-settings/src/OpenSettings/Models/LicenseEdition.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Trial = 400
    return:
      type: OpenSettings.Models.LicenseEdition
- uid: OpenSettings.Models.LicenseEdition.Enterprise
  commentId: F:OpenSettings.Models.LicenseEdition.Enterprise
  id: Enterprise
  parent: OpenSettings.Models.LicenseEdition
  langs:
  - csharp
  - vb
  name: Enterprise
  nameWithType: LicenseEdition.Enterprise
  fullName: OpenSettings.Models.LicenseEdition.Enterprise
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/LicenseEdition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Enterprise
    path: ../../../open-settings/src/OpenSettings/Models/LicenseEdition.cs
    startLine: 12
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Enterprise = 500
    return:
      type: OpenSettings.Models.LicenseEdition
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: OpenSettings.Models.LicenseEdition
  commentId: T:OpenSettings.Models.LicenseEdition
  parent: OpenSettings.Models
  href: OpenSettings.Models.LicenseEdition.html
  name: LicenseEdition
  nameWithType: LicenseEdition
  fullName: OpenSettings.Models.LicenseEdition
