### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  id: OpenSettings.Services.Interfaces
  children:
  - OpenSettings.Services.Interfaces.IAppGroupsService
  - OpenSettings.Services.Interfaces.IAppIdentifierMappingsService
  - OpenSettings.Services.Interfaces.IAppTagMappingsService
  - OpenSettings.Services.Interfaces.IAppsService
  - OpenSettings.Services.Interfaces.IConfigurationsService
  - OpenSettings.Services.Interfaces.IDataChangeService
  - OpenSettings.Services.Interfaces.IIdentifiersService
  - OpenSettings.Services.Interfaces.IInstancesService
  - OpenSettings.Services.Interfaces.ILicensesService
  - OpenSettings.Services.Interfaces.ILocalSettingsService
  - OpenSettings.Services.Interfaces.ILocksService
  - OpenSettings.Services.Interfaces.INotificationsService
  - OpenSettings.Services.Interfaces.IOpenSettingsService
  - OpenSettings.Services.Interfaces.IProviderService
  - OpenSettings.Services.Interfaces.ISettingClassesService
  - OpenSettings.Services.Interfaces.ISettingHistoriesService
  - OpenSettings.Services.Interfaces.ISettings
  - OpenSettings.Services.Interfaces.ISettingsService
  - OpenSettings.Services.Interfaces.ITagsService
  - OpenSettings.Services.Interfaces.IUserNotificationMappingsService
  - OpenSettings.Services.Interfaces.IUsersService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Interfaces.IAppGroupsService
  commentId: T:OpenSettings.Services.Interfaces.IAppGroupsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppGroupsService.html
  name: IAppGroupsService
  nameWithType: IAppGroupsService
  fullName: OpenSettings.Services.Interfaces.IAppGroupsService
- uid: OpenSettings.Services.Interfaces.IAppIdentifierMappingsService
  commentId: T:OpenSettings.Services.Interfaces.IAppIdentifierMappingsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppIdentifierMappingsService.html
  name: IAppIdentifierMappingsService
  nameWithType: IAppIdentifierMappingsService
  fullName: OpenSettings.Services.Interfaces.IAppIdentifierMappingsService
- uid: OpenSettings.Services.Interfaces.IAppsService
  commentId: T:OpenSettings.Services.Interfaces.IAppsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppsService.html
  name: IAppsService
  nameWithType: IAppsService
  fullName: OpenSettings.Services.Interfaces.IAppsService
- uid: OpenSettings.Services.Interfaces.IAppTagMappingsService
  commentId: T:OpenSettings.Services.Interfaces.IAppTagMappingsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppTagMappingsService.html
  name: IAppTagMappingsService
  nameWithType: IAppTagMappingsService
  fullName: OpenSettings.Services.Interfaces.IAppTagMappingsService
- uid: OpenSettings.Services.Interfaces.IConfigurationsService
  commentId: T:OpenSettings.Services.Interfaces.IConfigurationsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IConfigurationsService.html
  name: IConfigurationsService
  nameWithType: IConfigurationsService
  fullName: OpenSettings.Services.Interfaces.IConfigurationsService
- uid: OpenSettings.Services.Interfaces.IDataChangeService
  commentId: T:OpenSettings.Services.Interfaces.IDataChangeService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IDataChangeService.html
  name: IDataChangeService
  nameWithType: IDataChangeService
  fullName: OpenSettings.Services.Interfaces.IDataChangeService
- uid: OpenSettings.Services.Interfaces.IInstancesService
  commentId: T:OpenSettings.Services.Interfaces.IInstancesService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IInstancesService.html
  name: IInstancesService
  nameWithType: IInstancesService
  fullName: OpenSettings.Services.Interfaces.IInstancesService
- uid: OpenSettings.Services.Interfaces.ILicensesService
  commentId: T:OpenSettings.Services.Interfaces.ILicensesService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ILicensesService.html
  name: ILicensesService
  nameWithType: ILicensesService
  fullName: OpenSettings.Services.Interfaces.ILicensesService
- uid: OpenSettings.Services.Interfaces.ILocalSettingsService
  commentId: T:OpenSettings.Services.Interfaces.ILocalSettingsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ILocalSettingsService.html
  name: ILocalSettingsService
  nameWithType: ILocalSettingsService
  fullName: OpenSettings.Services.Interfaces.ILocalSettingsService
- uid: OpenSettings.Services.Interfaces.ILocksService
  commentId: T:OpenSettings.Services.Interfaces.ILocksService
  href: OpenSettings.Services.Interfaces.ILocksService.html
  name: ILocksService
  nameWithType: ILocksService
  fullName: OpenSettings.Services.Interfaces.ILocksService
- uid: OpenSettings.Services.Interfaces.INotificationsService
  commentId: T:OpenSettings.Services.Interfaces.INotificationsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.INotificationsService.html
  name: INotificationsService
  nameWithType: INotificationsService
  fullName: OpenSettings.Services.Interfaces.INotificationsService
- uid: OpenSettings.Services.Interfaces.IOpenSettingsService
  commentId: T:OpenSettings.Services.Interfaces.IOpenSettingsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IOpenSettingsService.html
  name: IOpenSettingsService
  nameWithType: IOpenSettingsService
  fullName: OpenSettings.Services.Interfaces.IOpenSettingsService
- uid: OpenSettings.Services.Interfaces.IProviderService
  commentId: T:OpenSettings.Services.Interfaces.IProviderService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IProviderService.html
  name: IProviderService
  nameWithType: IProviderService
  fullName: OpenSettings.Services.Interfaces.IProviderService
- uid: OpenSettings.Services.Interfaces.ISettingClassesService
  commentId: T:OpenSettings.Services.Interfaces.ISettingClassesService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ISettingClassesService.html
  name: ISettingClassesService
  nameWithType: ISettingClassesService
  fullName: OpenSettings.Services.Interfaces.ISettingClassesService
- uid: OpenSettings.Services.Interfaces.ISettingHistoriesService
  commentId: T:OpenSettings.Services.Interfaces.ISettingHistoriesService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ISettingHistoriesService.html
  name: ISettingHistoriesService
  nameWithType: ISettingHistoriesService
  fullName: OpenSettings.Services.Interfaces.ISettingHistoriesService
- uid: OpenSettings.Services.Interfaces.IIdentifiersService
  commentId: T:OpenSettings.Services.Interfaces.IIdentifiersService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IIdentifiersService.html
  name: IIdentifiersService
  nameWithType: IIdentifiersService
  fullName: OpenSettings.Services.Interfaces.IIdentifiersService
- uid: OpenSettings.Services.Interfaces.ISettings
  commentId: T:OpenSettings.Services.Interfaces.ISettings
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ISettings.html
  name: ISettings
  nameWithType: ISettings
  fullName: OpenSettings.Services.Interfaces.ISettings
- uid: OpenSettings.Services.Interfaces.ISettingsService
  commentId: T:OpenSettings.Services.Interfaces.ISettingsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ISettingsService.html
  name: ISettingsService
  nameWithType: ISettingsService
  fullName: OpenSettings.Services.Interfaces.ISettingsService
- uid: OpenSettings.Services.Interfaces.ITagsService
  commentId: T:OpenSettings.Services.Interfaces.ITagsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ITagsService.html
  name: ITagsService
  nameWithType: ITagsService
  fullName: OpenSettings.Services.Interfaces.ITagsService
- uid: OpenSettings.Services.Interfaces.IUserNotificationMappingsService
  commentId: T:OpenSettings.Services.Interfaces.IUserNotificationMappingsService
  href: OpenSettings.Services.Interfaces.IUserNotificationMappingsService.html
  name: IUserNotificationMappingsService
  nameWithType: IUserNotificationMappingsService
  fullName: OpenSettings.Services.Interfaces.IUserNotificationMappingsService
- uid: OpenSettings.Services.Interfaces.IUsersService
  commentId: T:OpenSettings.Services.Interfaces.IUsersService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IUsersService.html
  name: IUsersService
  nameWithType: IUsersService
  fullName: OpenSettings.Services.Interfaces.IUsersService
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
