### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services
  commentId: N:OpenSettings.Services
  id: OpenSettings.Services
  children:
  - OpenSettings.Services.OpenSettingsService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services
  nameWithType: OpenSettings.Services
  fullName: OpenSettings.Services
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.OpenSettingsService
  commentId: T:OpenSettings.Services.OpenSettingsService
  href: OpenSettings.Services.OpenSettingsService.html
  name: OpenSettingsService
  nameWithType: OpenSettingsService
  fullName: OpenSettings.Services.OpenSettingsService
