### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Models.Responses
  commentId: N:OpenSettings.AspNetCore.Models.Responses
  id: OpenSettings.AspNetCore.Models.Responses
  children:
  - OpenSettings.AspNetCore.Models.Responses.RefreshTokenResponse
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore.Models.Responses
  nameWithType: OpenSettings.AspNetCore.Models.Responses
  fullName: OpenSettings.AspNetCore.Models.Responses
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore
references:
- uid: OpenSettings.AspNetCore.Models.Responses.RefreshTokenResponse
  commentId: T:OpenSettings.AspNetCore.Models.Responses.RefreshTokenResponse
  href: OpenSettings.AspNetCore.Models.Responses.RefreshTokenResponse.html
  name: RefreshTokenResponse
  nameWithType: RefreshTokenResponse
  fullName: OpenSettings.AspNetCore.Models.Responses.RefreshTokenResponse
