### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Interfaces.IUserNotificationMappingsService
  commentId: T:OpenSettings.Services.Interfaces.IUserNotificationMappingsService
  id: IUserNotificationMappingsService
  parent: OpenSettings.Services.Interfaces
  children: []
  langs:
  - csharp
  - vb
  name: IUserNotificationMappingsService
  nameWithType: IUserNotificationMappingsService
  fullName: OpenSettings.Services.Interfaces.IUserNotificationMappingsService
  type: Interface
  source:
    remote:
      path: src/OpenSettings/Services/Interfaces/IUserNotificationMappingsService.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IUserNotificationMappingsService
    path: ../../../open-settings/src/OpenSettings/Services/Interfaces/IUserNotificationMappingsService.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.Interfaces
  syntax:
    content: public interface IUserNotificationMappingsService
    content.vb: Public Interface IUserNotificationMappingsService
references:
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
