### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.SetSortOrderPosition
  commentId: T:OpenSettings.Models.SetSortOrderPosition
  id: SetSortOrderPosition
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.SetSortOrderPosition.Bottom
  - OpenSettings.Models.SetSortOrderPosition.Top
  langs:
  - csharp
  - vb
  name: SetSortOrderPosition
  nameWithType: SetSortOrderPosition
  fullName: OpenSettings.Models.SetSortOrderPosition
  type: Enum
  source:
    remote:
      path: src/OpenSettings/Models/SetSortOrderPosition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: SetSortOrderPosition
    path: ../../../open-settings/src/OpenSettings/Models/SetSortOrderPosition.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public enum SetSortOrderPosition
    content.vb: Public Enum SetSortOrderPosition
- uid: OpenSettings.Models.SetSortOrderPosition.Bottom
  commentId: F:OpenSettings.Models.SetSortOrderPosition.Bottom
  id: Bottom
  parent: OpenSettings.Models.SetSortOrderPosition
  langs:
  - csharp
  - vb
  name: Bottom
  nameWithType: SetSortOrderPosition.Bottom
  fullName: OpenSettings.Models.SetSortOrderPosition.Bottom
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/SetSortOrderPosition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Bottom
    path: ../../../open-settings/src/OpenSettings/Models/SetSortOrderPosition.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Bottom = 1
    return:
      type: OpenSettings.Models.SetSortOrderPosition
- uid: OpenSettings.Models.SetSortOrderPosition.Top
  commentId: F:OpenSettings.Models.SetSortOrderPosition.Top
  id: Top
  parent: OpenSettings.Models.SetSortOrderPosition
  langs:
  - csharp
  - vb
  name: Top
  nameWithType: SetSortOrderPosition.Top
  fullName: OpenSettings.Models.SetSortOrderPosition.Top
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/SetSortOrderPosition.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Top
    path: ../../../open-settings/src/OpenSettings/Models/SetSortOrderPosition.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Top = 2
    return:
      type: OpenSettings.Models.SetSortOrderPosition
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: OpenSettings.Models.SetSortOrderPosition
  commentId: T:OpenSettings.Models.SetSortOrderPosition
  parent: OpenSettings.Models
  href: OpenSettings.Models.SetSortOrderPosition.html
  name: SetSortOrderPosition
  nameWithType: SetSortOrderPosition
  fullName: OpenSettings.Models.SetSortOrderPosition
