### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Rest.Interfaces
  commentId: N:OpenSettings.Services.Rest.Interfaces
  id: OpenSettings.Services.Rest.Interfaces
  children:
  - OpenSettings.Services.Rest.Interfaces.IAppGroupsRestService
  - OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingsRestService
  - OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService
  - OpenSettings.Services.Rest.Interfaces.IAppsRestService
  - OpenSettings.Services.Rest.Interfaces.IConfigurationsRestService
  - OpenSettings.Services.Rest.Interfaces.IIdentifiersRestService
  - OpenSettings.Services.Rest.Interfaces.IInstancesRestService
  - OpenSettings.Services.Rest.Interfaces.ILicensesRestService
  - OpenSettings.Services.Rest.Interfaces.INotificationsRestService
  - OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
  - OpenSettings.Services.Rest.Interfaces.IProviderRestService
  - OpenSettings.Services.Rest.Interfaces.ISettingClassesRestService
  - OpenSettings.Services.Rest.Interfaces.ISettingHistoriesRestService
  - OpenSettings.Services.Rest.Interfaces.ISettingsRestService
  - OpenSettings.Services.Rest.Interfaces.ITagsRestService
  - OpenSettings.Services.Rest.Interfaces.IUsersRestService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Rest.Interfaces
  nameWithType: OpenSettings.Services.Rest.Interfaces
  fullName: OpenSettings.Services.Rest.Interfaces
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Rest.Interfaces.IAppGroupsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppGroupsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppGroupsRestService.html
  name: IAppGroupsRestService
  nameWithType: IAppGroupsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppGroupsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingsRestService.html
  name: IAppIdentifierMappingsRestService
  nameWithType: IAppIdentifierMappingsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppsRestService.html
  name: IAppsRestService
  nameWithType: IAppsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService.html
  name: IAppTagMappingsRestService
  nameWithType: IAppTagMappingsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IConfigurationsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IConfigurationsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IConfigurationsRestService.html
  name: IConfigurationsRestService
  nameWithType: IConfigurationsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IConfigurationsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IIdentifiersRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IIdentifiersRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IIdentifiersRestService.html
  name: IIdentifiersRestService
  nameWithType: IIdentifiersRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IIdentifiersRestService
- uid: OpenSettings.Services.Rest.Interfaces.IInstancesRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IInstancesRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IInstancesRestService.html
  name: IInstancesRestService
  nameWithType: IInstancesRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IInstancesRestService
- uid: OpenSettings.Services.Rest.Interfaces.ILicensesRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ILicensesRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ILicensesRestService.html
  name: ILicensesRestService
  nameWithType: ILicensesRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ILicensesRestService
- uid: OpenSettings.Services.Rest.Interfaces.INotificationsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.INotificationsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.INotificationsRestService.html
  name: INotificationsRestService
  nameWithType: INotificationsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.INotificationsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService.html
  name: IOpenSettingsRestService
  nameWithType: IOpenSettingsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IProviderRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IProviderRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IProviderRestService.html
  name: IProviderRestService
  nameWithType: IProviderRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IProviderRestService
- uid: OpenSettings.Services.Rest.Interfaces.ISettingClassesRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ISettingClassesRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ISettingClassesRestService.html
  name: ISettingClassesRestService
  nameWithType: ISettingClassesRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ISettingClassesRestService
- uid: OpenSettings.Services.Rest.Interfaces.ISettingHistoriesRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ISettingHistoriesRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ISettingHistoriesRestService.html
  name: ISettingHistoriesRestService
  nameWithType: ISettingHistoriesRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ISettingHistoriesRestService
- uid: OpenSettings.Services.Rest.Interfaces.ISettingsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ISettingsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ISettingsRestService.html
  name: ISettingsRestService
  nameWithType: ISettingsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ISettingsRestService
- uid: OpenSettings.Services.Rest.Interfaces.ITagsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ITagsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ITagsRestService.html
  name: ITagsRestService
  nameWithType: ITagsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ITagsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IUsersRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IUsersRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IUsersRestService.html
  name: IUsersRestService
  nameWithType: IUsersRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IUsersRestService
- uid: OpenSettings.Services.Rest.Interfaces
  commentId: N:OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Rest.Interfaces
  nameWithType: OpenSettings.Services.Rest.Interfaces
  fullName: OpenSettings.Services.Rest.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
