### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Spa
  commentId: N:OpenSettings.AspNetCore.Spa
  id: OpenSettings.AspNetCore.Spa
  children:
  - OpenSettings.AspNetCore.Spa.SettingsSpaMiddleware
  - OpenSettings.AspNetCore.Spa.SettingsSpaOptions
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore.Spa
  nameWithType: OpenSettings.AspNetCore.Spa
  fullName: OpenSettings.AspNetCore.Spa
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore.Spa
references:
- uid: OpenSettings.AspNetCore.Spa.SettingsSpaMiddleware
  commentId: T:OpenSettings.AspNetCore.Spa.SettingsSpaMiddleware
  href: OpenSettings.AspNetCore.Spa.SettingsSpaMiddleware.html
  name: SettingsSpaMiddleware
  nameWithType: SettingsSpaMiddleware
  fullName: OpenSettings.AspNetCore.Spa.SettingsSpaMiddleware
- uid: OpenSettings.AspNetCore.Spa.SettingsSpaOptions
  commentId: T:OpenSettings.AspNetCore.Spa.SettingsSpaOptions
  parent: OpenSettings.AspNetCore.Spa
  href: OpenSettings.AspNetCore.Spa.SettingsSpaOptions.html
  name: SettingsSpaOptions
  nameWithType: SettingsSpaOptions
  fullName: OpenSettings.AspNetCore.Spa.SettingsSpaOptions
- uid: OpenSettings.AspNetCore.Spa
  commentId: N:OpenSettings.AspNetCore.Spa
  href: OpenSettings.html
  name: OpenSettings.AspNetCore.Spa
  nameWithType: OpenSettings.AspNetCore.Spa
  fullName: OpenSettings.AspNetCore.Spa
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Spa
    name: Spa
    href: OpenSettings.AspNetCore.Spa.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Spa
    name: Spa
    href: OpenSettings.AspNetCore.Spa.html
