### YamlMime:ManagedReference
items:
- uid: OpenSettings.Exceptions
  commentId: N:OpenSettings.Exceptions
  id: OpenSettings.Exceptions
  children:
  - OpenSettings.Exceptions.DuplicateSettingsNameException
  langs:
  - csharp
  - vb
  name: OpenSettings.Exceptions
  nameWithType: OpenSettings.Exceptions
  fullName: OpenSettings.Exceptions
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Exceptions.DuplicateSettingsNameException
  commentId: T:OpenSettings.Exceptions.DuplicateSettingsNameException
  href: OpenSettings.Exceptions.DuplicateSettingsNameException.html
  name: DuplicateSettingsNameException
  nameWithType: DuplicateSettingsNameException
  fullName: OpenSettings.Exceptions.DuplicateSettingsNameException
