### YamlMime:ManagedReference
items:
- uid: OpenSettings
  commentId: N:OpenSettings
  id: OpenSettings
  children:
  - OpenSettings.Constants
  - OpenSettings.Errors
  - OpenSettings.Helper
  - OpenSettings.LicenseProvider
  - OpenSettings.SettingsProvider
  langs:
  - csharp
  - vb
  name: OpenSettings
  nameWithType: OpenSettings
  fullName: OpenSettings
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Constants
  commentId: T:OpenSettings.Constants
  href: OpenSettings.Constants.html
  name: Constants
  nameWithType: Constants
  fullName: OpenSettings.Constants
- uid: OpenSettings.Errors
  commentId: T:OpenSettings.Errors
  parent: OpenSettings
  href: OpenSettings.Errors.html
  name: Errors
  nameWithType: Errors
  fullName: OpenSettings.Errors
- uid: OpenSettings.Helper
  commentId: T:OpenSettings.Helper
  parent: OpenSettings
  href: OpenSettings.Helper.html
  name: Helper
  nameWithType: Helper
  fullName: OpenSettings.Helper
- uid: OpenSettings.LicenseProvider
  commentId: T:OpenSettings.LicenseProvider
  parent: OpenSettings
  href: OpenSettings.LicenseProvider.html
  name: LicenseProvider
  nameWithType: LicenseProvider
  fullName: OpenSettings.LicenseProvider
- uid: OpenSettings.SettingsProvider
  commentId: T:OpenSettings.SettingsProvider
  href: OpenSettings.SettingsProvider.html
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: OpenSettings.SettingsProvider
- uid: OpenSettings
  commentId: N:OpenSettings
  href: OpenSettings.html
  name: OpenSettings
  nameWithType: OpenSettings
  fullName: OpenSettings
