### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService
  id: IAppTagMappingsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  children: []
  langs:
  - csharp
  - vb
  name: IAppTagMappingsRestService
  nameWithType: IAppTagMappingsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppTagMappingsRestService
  type: Interface
  source:
    remote:
      path: src/OpenSettings/Services/Rest/Interfaces/IAppTagMappingsRestService.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IAppTagMappingsRestService
    path: ../../../open-settings/src/OpenSettings/Services/Rest/Interfaces/IAppTagMappingsRestService.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.Rest.Interfaces
  syntax:
    content: 'public interface IAppTagMappingsRestService : IAppTagMappingsService'
    content.vb: Public Interface IAppTagMappingsRestService Inherits IAppTagMappingsService
references:
- uid: OpenSettings.Services.Rest.Interfaces
  commentId: N:OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Rest.Interfaces
  nameWithType: OpenSettings.Services.Rest.Interfaces
  fullName: OpenSettings.Services.Rest.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
