### YamlMime:ManagedReference
items:
- uid: OpenSettings.Domains.Sql.Entities
  commentId: N:OpenSettings.Domains.Sql.Entities
  id: OpenSettings.Domains.Sql.Entities
  children:
  - OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
  - OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.AppSqlModel
  - OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.ConfigurationSqlModel
  - OpenSettings.Domains.Sql.Entities.EntityBase`1
  - OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
  - OpenSettings.Domains.Sql.Entities.InstanceSqlModel
  - OpenSettings.Domains.Sql.Entities.LicenseSqlModel
  - OpenSettings.Domains.Sql.Entities.LockSqlModel
  - OpenSettings.Domains.Sql.Entities.NotificationSqlModel
  - OpenSettings.Domains.Sql.Entities.SettingClassSqlModel
  - OpenSettings.Domains.Sql.Entities.SettingHistorySqlModel
  - OpenSettings.Domains.Sql.Entities.SettingSqlModel
  - OpenSettings.Domains.Sql.Entities.TagSqlModel
  - OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupClaimMappingModel
  - OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
  - OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleClaimMappingModel
  - OpenSettings.Domains.Sql.Entities.UserRoleGroupMappingModel
  - OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
  - OpenSettings.Domains.Sql.Entities.UserSqlModel
  langs:
  - csharp
  - vb
  name: OpenSettings.Domains.Sql.Entities
  nameWithType: OpenSettings.Domains.Sql.Entities
  fullName: OpenSettings.Domains.Sql.Entities
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.AppGroupSqlModel.html
  name: AppGroupSqlModel
  nameWithType: AppGroupSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel.html
  name: AppIdentifierMappingSqlModel
  nameWithType: AppIdentifierMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.AppSqlModel.html
  name: AppSqlModel
  nameWithType: AppSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel.html
  name: AppTagMappingSqlModel
  nameWithType: AppTagMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.ConfigurationSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.ConfigurationSqlModel
  href: OpenSettings.Domains.Sql.Entities.ConfigurationSqlModel.html
  name: ConfigurationSqlModel
  nameWithType: ConfigurationSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.ConfigurationSqlModel
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1
  commentId: T:OpenSettings.Domains.Sql.Entities.EntityBase`1
  href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html
  name: EntityBase<TId>
  nameWithType: EntityBase<TId>
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>
  nameWithType.vb: EntityBase(Of TId)
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId)
  name.vb: EntityBase(Of TId)
  spec.csharp:
  - uid: OpenSettings.Domains.Sql.Entities.EntityBase`1
    name: EntityBase
    href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html
  - name: <
  - name: TId
  - name: '>'
  spec.vb:
  - uid: OpenSettings.Domains.Sql.Entities.EntityBase`1
    name: EntityBase
    href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TId
  - name: )
- uid: OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.IdentifierSqlModel.html
  name: IdentifierSqlModel
  nameWithType: IdentifierSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
- uid: OpenSettings.Domains.Sql.Entities.InstanceSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.InstanceSqlModel
  href: OpenSettings.Domains.Sql.Entities.InstanceSqlModel.html
  name: InstanceSqlModel
  nameWithType: InstanceSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.InstanceSqlModel
- uid: OpenSettings.Domains.Sql.Entities.LicenseSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.LicenseSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.LicenseSqlModel.html
  name: LicenseSqlModel
  nameWithType: LicenseSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.LicenseSqlModel
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.LockSqlModel
  href: OpenSettings.Domains.Sql.Entities.LockSqlModel.html
  name: LockSqlModel
  nameWithType: LockSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel
- uid: OpenSettings.Domains.Sql.Entities.NotificationSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.NotificationSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.NotificationSqlModel.html
  name: NotificationSqlModel
  nameWithType: NotificationSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.NotificationSqlModel
- uid: OpenSettings.Domains.Sql.Entities.SettingClassSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.SettingClassSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.SettingClassSqlModel.html
  name: SettingClassSqlModel
  nameWithType: SettingClassSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.SettingClassSqlModel
- uid: OpenSettings.Domains.Sql.Entities.SettingHistorySqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.SettingHistorySqlModel
  href: OpenSettings.Domains.Sql.Entities.SettingHistorySqlModel.html
  name: SettingHistorySqlModel
  nameWithType: SettingHistorySqlModel
  fullName: OpenSettings.Domains.Sql.Entities.SettingHistorySqlModel
- uid: OpenSettings.Domains.Sql.Entities.SettingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.SettingSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.SettingSqlModel.html
  name: SettingSqlModel
  nameWithType: SettingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.SettingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.TagSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.TagSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.TagSqlModel.html
  name: TagSqlModel
  nameWithType: TagSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.TagSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel.html
  name: UserClaimMappingSqlModel
  nameWithType: UserClaimMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserClaimSqlModel.html
  name: UserClaimSqlModel
  nameWithType: UserClaimSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupClaimMappingModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupClaimMappingModel
  href: OpenSettings.Domains.Sql.Entities.UserGroupClaimMappingModel.html
  name: UserGroupClaimMappingModel
  nameWithType: UserGroupClaimMappingModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupClaimMappingModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel.html
  name: UserGroupMappingSqlModel
  nameWithType: UserGroupMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel.html
  name: UserGroupNotificationMappingSqlModel
  nameWithType: UserGroupNotificationMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserGroupSqlModel.html
  name: UserGroupSqlModel
  nameWithType: UserGroupSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel.html
  name: UserNotificationMappingSqlModel
  nameWithType: UserNotificationMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleClaimMappingModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleClaimMappingModel
  href: OpenSettings.Domains.Sql.Entities.UserRoleClaimMappingModel.html
  name: UserRoleClaimMappingModel
  nameWithType: UserRoleClaimMappingModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleClaimMappingModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleGroupMappingModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleGroupMappingModel
  href: OpenSettings.Domains.Sql.Entities.UserRoleGroupMappingModel.html
  name: UserRoleGroupMappingModel
  nameWithType: UserRoleGroupMappingModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleGroupMappingModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel.html
  name: UserRoleMappingSqlModel
  nameWithType: UserRoleMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserRoleSqlModel.html
  name: UserRoleSqlModel
  nameWithType: UserRoleSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserSqlModel.html
  name: UserSqlModel
  nameWithType: UserSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserSqlModel
- uid: OpenSettings.Domains.Sql.Entities
  commentId: N:OpenSettings.Domains.Sql.Entities
  href: OpenSettings.html
  name: OpenSettings.Domains.Sql.Entities
  nameWithType: OpenSettings.Domains.Sql.Entities
  fullName: OpenSettings.Domains.Sql.Entities
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
