### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
  commentId: T:OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
  id: OpenSettingsConfigsDataCacheModel`1
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.AbsoluteExpiration
  - OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.Data
  langs:
  - csharp
  - vb
  name: OpenSettingsConfigsDataCacheModel<T>
  nameWithType: OpenSettingsConfigsDataCacheModel<T>
  fullName: OpenSettings.Models.OpenSettingsConfigsDataCacheModel<T>
  type: Class
  source:
    remote:
      path: src/OpenSettings/Models/OpenSettingsConfigDataCacheModel.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: OpenSettingsConfigsDataCacheModel
    path: ../../../open-settings/src/OpenSettings/Models/OpenSettingsConfigDataCacheModel.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public class OpenSettingsConfigsDataCacheModel<T>
    typeParameters:
    - id: T
    content.vb: Public Class OpenSettingsConfigsDataCacheModel(Of T)
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  nameWithType.vb: OpenSettingsConfigsDataCacheModel(Of T)
  fullName.vb: OpenSettings.Models.OpenSettingsConfigsDataCacheModel(Of T)
  name.vb: OpenSettingsConfigsDataCacheModel(Of T)
- uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.Data
  commentId: P:OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.Data
  id: Data
  parent: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: OpenSettingsConfigsDataCacheModel<T>.Data
  fullName: OpenSettings.Models.OpenSettingsConfigsDataCacheModel<T>.Data
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/OpenSettingsConfigDataCacheModel.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Data
    path: ../../../open-settings/src/OpenSettings/Models/OpenSettingsConfigDataCacheModel.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public T Data { get; set; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public Property Data As T
  overload: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.Data*
  nameWithType.vb: OpenSettingsConfigsDataCacheModel(Of T).Data
  fullName.vb: OpenSettings.Models.OpenSettingsConfigsDataCacheModel(Of T).Data
- uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.AbsoluteExpiration
  commentId: P:OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.AbsoluteExpiration
  id: AbsoluteExpiration
  parent: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
  langs:
  - csharp
  - vb
  name: AbsoluteExpiration
  nameWithType: OpenSettingsConfigsDataCacheModel<T>.AbsoluteExpiration
  fullName: OpenSettings.Models.OpenSettingsConfigsDataCacheModel<T>.AbsoluteExpiration
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/OpenSettingsConfigDataCacheModel.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: AbsoluteExpiration
    path: ../../../open-settings/src/OpenSettings/Models/OpenSettingsConfigDataCacheModel.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public DateTimeOffset AbsoluteExpiration { get; set; }
    parameters: []
    return:
      type: System.DateTimeOffset
    content.vb: Public Property AbsoluteExpiration As DateTimeOffset
  overload: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.AbsoluteExpiration*
  nameWithType.vb: OpenSettingsConfigsDataCacheModel(Of T).AbsoluteExpiration
  fullName.vb: OpenSettings.Models.OpenSettingsConfigsDataCacheModel(Of T).AbsoluteExpiration
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.Data*
  commentId: Overload:OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.Data
  href: OpenSettings.Models.OpenSettingsConfigsDataCacheModel-1.html#OpenSettings_Models_OpenSettingsConfigsDataCacheModel_1_Data
  name: Data
  nameWithType: OpenSettingsConfigsDataCacheModel<T>.Data
  fullName: OpenSettings.Models.OpenSettingsConfigsDataCacheModel<T>.Data
  nameWithType.vb: OpenSettingsConfigsDataCacheModel(Of T).Data
  fullName.vb: OpenSettings.Models.OpenSettingsConfigsDataCacheModel(Of T).Data
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.AbsoluteExpiration*
  commentId: Overload:OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1.AbsoluteExpiration
  href: OpenSettings.Models.OpenSettingsConfigsDataCacheModel-1.html#OpenSettings_Models_OpenSettingsConfigsDataCacheModel_1_AbsoluteExpiration
  name: AbsoluteExpiration
  nameWithType: OpenSettingsConfigsDataCacheModel<T>.AbsoluteExpiration
  fullName: OpenSettings.Models.OpenSettingsConfigsDataCacheModel<T>.AbsoluteExpiration
  nameWithType.vb: OpenSettingsConfigsDataCacheModel(Of T).AbsoluteExpiration
  fullName.vb: OpenSettings.Models.OpenSettingsConfigsDataCacheModel(Of T).AbsoluteExpiration
- uid: System.DateTimeOffset
  commentId: T:System.DateTimeOffset
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.datetimeoffset
  name: DateTimeOffset
  nameWithType: DateTimeOffset
  fullName: System.DateTimeOffset
