### YamlMime:ManagedReference
items:
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.LockSqlModel
  id: LockSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  children:
  - OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime
  - OpenSettings.Domains.Sql.Entities.LockSqlModel.Key
  - OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner
  langs:
  - csharp
  - vb
  name: LockSqlModel
  nameWithType: LockSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel
  type: Class
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: LockSqlModel
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: Represents a lock entity.
  example: []
  syntax:
    content: >-
      [Table("Locks")]

      public class LockSqlModel
    content.vb: >-
      <Table("Locks")>

      Public Class LockSqlModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.ComponentModel.DataAnnotations.Schema.TableAttribute
    ctor: System.ComponentModel.DataAnnotations.Schema.TableAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Locks
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel.Key
  commentId: P:OpenSettings.Domains.Sql.Entities.LockSqlModel.Key
  id: Key
  parent: OpenSettings.Domains.Sql.Entities.LockSqlModel
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: LockSqlModel.Key
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel.Key
  type: Property
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Key
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
    startLine: 14
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: The key of the lock.
  example: []
  syntax:
    content: public string Key { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Key As String
  overload: OpenSettings.Domains.Sql.Entities.LockSqlModel.Key*
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner
  commentId: P:OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner
  id: Owner
  parent: OpenSettings.Domains.Sql.Entities.LockSqlModel
  langs:
  - csharp
  - vb
  name: Owner
  nameWithType: LockSqlModel.Owner
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner
  type: Property
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Owner
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
    startLine: 19
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: The owner of the lock.
  example: []
  syntax:
    content: public string Owner { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Owner As String
  overload: OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner*
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime
  commentId: P:OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime
  id: ExpiryTime
  parent: OpenSettings.Domains.Sql.Entities.LockSqlModel
  langs:
  - csharp
  - vb
  name: ExpiryTime
  nameWithType: LockSqlModel.ExpiryTime
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime
  type: Property
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: ExpiryTime
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/LockSqlModel.cs
    startLine: 24
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: The expiry time of the lock.
  example: []
  syntax:
    content: public DateTime ExpiryTime { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: Public Property ExpiryTime As Date
  overload: OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime*
references:
- uid: OpenSettings.Domains.Sql.Entities
  commentId: N:OpenSettings.Domains.Sql.Entities
  href: OpenSettings.html
  name: OpenSettings.Domains.Sql.Entities
  nameWithType: OpenSettings.Domains.Sql.Entities
  fullName: OpenSettings.Domains.Sql.Entities
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel.Key*
  commentId: Overload:OpenSettings.Domains.Sql.Entities.LockSqlModel.Key
  href: OpenSettings.Domains.Sql.Entities.LockSqlModel.html#OpenSettings_Domains_Sql_Entities_LockSqlModel_Key
  name: Key
  nameWithType: LockSqlModel.Key
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel.Key
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner*
  commentId: Overload:OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner
  href: OpenSettings.Domains.Sql.Entities.LockSqlModel.html#OpenSettings_Domains_Sql_Entities_LockSqlModel_Owner
  name: Owner
  nameWithType: LockSqlModel.Owner
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel.Owner
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime*
  commentId: Overload:OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime
  href: OpenSettings.Domains.Sql.Entities.LockSqlModel.html#OpenSettings_Domains_Sql_Entities_LockSqlModel_ExpiryTime
  name: ExpiryTime
  nameWithType: LockSqlModel.ExpiryTime
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel.ExpiryTime
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.datetime
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
  nameWithType.vb: Date
  fullName.vb: Date
  name.vb: Date
