### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Sql.Interfaces
  commentId: N:OpenSettings.Services.Sql.Interfaces
  id: OpenSettings.Services.Sql.Interfaces
  children:
  - OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Sql.Interfaces
  nameWithType: OpenSettings.Services.Sql.Interfaces
  fullName: OpenSettings.Services.Sql.Interfaces
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService
  commentId: T:OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService
  href: OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService.html
  name: IUserNotificationMappingsSqlService
  nameWithType: IUserNotificationMappingsSqlService
  fullName: OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService
