### YamlMime:ManagedReference
items:
- uid: OpenSettings.Configurations.SpaConfiguration
  commentId: T:OpenSettings.Configurations.SpaConfiguration
  id: SpaConfiguration
  parent: OpenSettings.Configurations
  children:
  - OpenSettings.Configurations.SpaConfiguration.DocumentTitle
  - OpenSettings.Configurations.SpaConfiguration.IndexStream
  - OpenSettings.Configurations.SpaConfiguration.IsActive
  - OpenSettings.Configurations.SpaConfiguration.RoutePrefix
  langs:
  - csharp
  - vb
  name: SpaConfiguration
  nameWithType: SpaConfiguration
  fullName: OpenSettings.Configurations.SpaConfiguration
  type: Class
  source:
    remote:
      path: src/OpenSettings/Configurations/SpaConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: SpaConfiguration
    path: ../../../open-settings/src/OpenSettings/Configurations/SpaConfiguration.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Represents the configuration options for the open settings Spa page.

    <p>This class allows customization of various settings related to the page behavior and appearance.</p>

    <p>It includes properties for managing the index stream and document title, among other settings.</p>
  example: []
  syntax:
    content: public class SpaConfiguration
    content.vb: Public Class SpaConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.Configurations.SpaConfiguration.RoutePrefix
  commentId: P:OpenSettings.Configurations.SpaConfiguration.RoutePrefix
  id: RoutePrefix
  parent: OpenSettings.Configurations.SpaConfiguration
  langs:
  - csharp
  - vb
  name: RoutePrefix
  nameWithType: SpaConfiguration.RoutePrefix
  fullName: OpenSettings.Configurations.SpaConfiguration.RoutePrefix
  type: Property
  source:
    remote:
      path: src/OpenSettings/Configurations/SpaConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: RoutePrefix
    path: ../../../open-settings/src/OpenSettings/Configurations/SpaConfiguration.cs
    startLine: 21
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Specifies the prefix used to access the open settings Spa page.  

    <p>With this prefix, the open settings Spa page can be accessed through the defined route.</p>
  remarks: The default value is '<code>settings</code>'.
  example: []
  syntax:
    content: public string RoutePrefix { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property RoutePrefix As String
  overload: OpenSettings.Configurations.SpaConfiguration.RoutePrefix*
- uid: OpenSettings.Configurations.SpaConfiguration.IndexStream
  commentId: P:OpenSettings.Configurations.SpaConfiguration.IndexStream
  id: IndexStream
  parent: OpenSettings.Configurations.SpaConfiguration
  langs:
  - csharp
  - vb
  name: IndexStream
  nameWithType: SpaConfiguration.IndexStream
  fullName: OpenSettings.Configurations.SpaConfiguration.IndexStream
  type: Property
  source:
    remote:
      path: src/OpenSettings/Configurations/SpaConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IndexStream
    path: ../../../open-settings/src/OpenSettings/Configurations/SpaConfiguration.cs
    startLine: 45
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Gets or sets a function that returns a <xref href="System.IO.Stream" data-throw-if-not-resolved="false"></xref> representing the index HTML file for the open settings spa.  

    <p>This function retrieves the embedded resource stream for the specified HTML file.</p>

    <p>The default implementation uses the <code>OpenSettings.AspNetCore.Spa</code> type's assembly to access the embedded resource.</p>
  example: []
  syntax:
    content: public Func<Stream> IndexStream { get; set; }
    parameters: []
    return:
      type: System.Func{System.IO.Stream}
    content.vb: Public Property IndexStream As Func(Of Stream)
  overload: OpenSettings.Configurations.SpaConfiguration.IndexStream*
- uid: OpenSettings.Configurations.SpaConfiguration.DocumentTitle
  commentId: P:OpenSettings.Configurations.SpaConfiguration.DocumentTitle
  id: DocumentTitle
  parent: OpenSettings.Configurations.SpaConfiguration
  langs:
  - csharp
  - vb
  name: DocumentTitle
  nameWithType: SpaConfiguration.DocumentTitle
  fullName: OpenSettings.Configurations.SpaConfiguration.DocumentTitle
  type: Property
  source:
    remote:
      path: src/OpenSettings/Configurations/SpaConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: DocumentTitle
    path: ../../../open-settings/src/OpenSettings/Configurations/SpaConfiguration.cs
    startLine: 54
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Gets or sets the title of the document for the open settings page.  

    <p>This title is used in the HTML document's title element and will be displayed in the browser's title bar.</p>
  remarks: The default value is '<code>OpenSettings Spa</code>'.
  example: []
  syntax:
    content: public string DocumentTitle { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DocumentTitle As String
  overload: OpenSettings.Configurations.SpaConfiguration.DocumentTitle*
- uid: OpenSettings.Configurations.SpaConfiguration.IsActive
  commentId: P:OpenSettings.Configurations.SpaConfiguration.IsActive
  id: IsActive
  parent: OpenSettings.Configurations.SpaConfiguration
  langs:
  - csharp
  - vb
  name: IsActive
  nameWithType: SpaConfiguration.IsActive
  fullName: OpenSettings.Configurations.SpaConfiguration.IsActive
  type: Property
  source:
    remote:
      path: src/OpenSettings/Configurations/SpaConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IsActive
    path: ../../../open-settings/src/OpenSettings/Configurations/SpaConfiguration.cs
    startLine: 64
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Gets or sets a value indicating whether the open settings Spa (Single Page Application) is active.

    The default value is <code>true</code>.
  remarks: >-
    Setting this property to <code>true</code> does not guarantee that the Spa will be accessible.

    Make sure to register <code>AddOpenSettingsController(...)</code> and <code>app.UseOpenSettings(...)</code> after <code>UseRouting()</code> and before <code>UseEndpoints()</code>.
  example: []
  syntax:
    content: public bool IsActive { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsActive As Boolean
  overload: OpenSettings.Configurations.SpaConfiguration.IsActive*
references:
- uid: OpenSettings.Configurations
  commentId: N:OpenSettings.Configurations
  href: OpenSettings.html
  name: OpenSettings.Configurations
  nameWithType: OpenSettings.Configurations
  fullName: OpenSettings.Configurations
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Configurations
    name: Configurations
    href: OpenSettings.Configurations.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Configurations
    name: Configurations
    href: OpenSettings.Configurations.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Configurations.SpaConfiguration.RoutePrefix*
  commentId: Overload:OpenSettings.Configurations.SpaConfiguration.RoutePrefix
  href: OpenSettings.Configurations.SpaConfiguration.html#OpenSettings_Configurations_SpaConfiguration_RoutePrefix
  name: RoutePrefix
  nameWithType: SpaConfiguration.RoutePrefix
  fullName: OpenSettings.Configurations.SpaConfiguration.RoutePrefix
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.IO.Stream
  commentId: T:System.IO.Stream
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.io.stream
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: OpenSettings.Configurations.SpaConfiguration.IndexStream*
  commentId: Overload:OpenSettings.Configurations.SpaConfiguration.IndexStream
  href: OpenSettings.Configurations.SpaConfiguration.html#OpenSettings_Configurations_SpaConfiguration_IndexStream
  name: IndexStream
  nameWithType: SpaConfiguration.IndexStream
  fullName: OpenSettings.Configurations.SpaConfiguration.IndexStream
- uid: System.Func{System.IO.Stream}
  commentId: T:System.Func{System.IO.Stream}
  parent: System
  definition: System.Func`1
  href: https://learn.microsoft.com/dotnet/api/system.func-1
  name: Func<Stream>
  nameWithType: Func<Stream>
  fullName: System.Func<System.IO.Stream>
  nameWithType.vb: Func(Of Stream)
  fullName.vb: System.Func(Of System.IO.Stream)
  name.vb: Func(Of Stream)
  spec.csharp:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: <
  - uid: System.IO.Stream
    name: Stream
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.io.stream
  - name: '>'
  spec.vb:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.IO.Stream
    name: Stream
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.io.stream
  - name: )
- uid: System.Func`1
  commentId: T:System.Func`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.func-1
  name: Func<TResult>
  nameWithType: Func<TResult>
  fullName: System.Func<TResult>
  nameWithType.vb: Func(Of TResult)
  fullName.vb: System.Func(Of TResult)
  name.vb: Func(Of TResult)
  spec.csharp:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: OpenSettings.Configurations.SpaConfiguration.DocumentTitle*
  commentId: Overload:OpenSettings.Configurations.SpaConfiguration.DocumentTitle
  href: OpenSettings.Configurations.SpaConfiguration.html#OpenSettings_Configurations_SpaConfiguration_DocumentTitle
  name: DocumentTitle
  nameWithType: SpaConfiguration.DocumentTitle
  fullName: OpenSettings.Configurations.SpaConfiguration.DocumentTitle
- uid: OpenSettings.Configurations.SpaConfiguration.IsActive*
  commentId: Overload:OpenSettings.Configurations.SpaConfiguration.IsActive
  href: OpenSettings.Configurations.SpaConfiguration.html#OpenSettings_Configurations_SpaConfiguration_IsActive
  name: IsActive
  nameWithType: SpaConfiguration.IsActive
  fullName: OpenSettings.Configurations.SpaConfiguration.IsActive
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
