### YamlMime:ManagedReference
items:
- uid: OpenSettings.Helpers
  commentId: N:OpenSettings.Helpers
  id: OpenSettings.Helpers
  children:
  - OpenSettings.Helpers.Helper
  - OpenSettings.Helpers.JsonHelper
  - OpenSettings.Helpers.VersionHelper
  langs:
  - csharp
  - vb
  name: OpenSettings.Helpers
  nameWithType: OpenSettings.Helpers
  fullName: OpenSettings.Helpers
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Helpers.Helper
  commentId: T:OpenSettings.Helpers.Helper
  parent: OpenSettings.Helpers
  href: OpenSettings.Helpers.Helper.html
  name: Helper
  nameWithType: Helper
  fullName: OpenSettings.Helpers.Helper
- uid: OpenSettings.Helpers.JsonHelper
  commentId: T:OpenSettings.Helpers.JsonHelper
  href: OpenSettings.Helpers.JsonHelper.html
  name: JsonHelper
  nameWithType: JsonHelper
  fullName: OpenSettings.Helpers.JsonHelper
- uid: OpenSettings.Helpers.VersionHelper
  commentId: T:OpenSettings.Helpers.VersionHelper
  href: OpenSettings.Helpers.VersionHelper.html
  name: VersionHelper
  nameWithType: VersionHelper
  fullName: OpenSettings.Helpers.VersionHelper
- uid: OpenSettings.Helpers
  commentId: N:OpenSettings.Helpers
  href: OpenSettings.html
  name: OpenSettings.Helpers
  nameWithType: OpenSettings.Helpers
  fullName: OpenSettings.Helpers
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Helpers
    name: Helpers
    href: OpenSettings.Helpers.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Helpers
    name: Helpers
    href: OpenSettings.Helpers.html
