### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Spa
  commentId: N:OpenSettings.AspNetCore.Spa
  id: OpenSettings.AspNetCore.Spa
  children:
  - OpenSettings.AspNetCore.Spa.OpenSettingsSpaMiddleware
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore.Spa
  nameWithType: OpenSettings.AspNetCore.Spa
  fullName: OpenSettings.AspNetCore.Spa
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore.Spa
references:
- uid: OpenSettings.AspNetCore.Spa.OpenSettingsSpaMiddleware
  commentId: T:OpenSettings.AspNetCore.Spa.OpenSettingsSpaMiddleware
  href: OpenSettings.AspNetCore.Spa.OpenSettingsSpaMiddleware.html
  name: OpenSettingsSpaMiddleware
  nameWithType: OpenSettingsSpaMiddleware
  fullName: OpenSettings.AspNetCore.Spa.OpenSettingsSpaMiddleware
