### YamlMime:ManagedReference
items:
- uid: OpenSettings.Domains.Redis.DataContext
  commentId: N:OpenSettings.Domains.Redis.DataContext
  id: OpenSettings.Domains.Redis.DataContext
  children:
  - OpenSettings.Domains.Redis.DataContext.Context
  - OpenSettings.Domains.Redis.DataContext.RedisContext
  - OpenSettings.Domains.Redis.DataContext.RedisContextOptions
  langs:
  - csharp
  - vb
  name: OpenSettings.Domains.Redis.DataContext
  nameWithType: OpenSettings.Domains.Redis.DataContext
  fullName: OpenSettings.Domains.Redis.DataContext
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Domains.Redis.DataContext.Context
  commentId: T:OpenSettings.Domains.Redis.DataContext.Context
  href: OpenSettings.Domains.Redis.DataContext.Context.html
  name: Context
  nameWithType: Context
  fullName: OpenSettings.Domains.Redis.DataContext.Context
- uid: OpenSettings.Domains.Redis.DataContext.RedisContext
  commentId: T:OpenSettings.Domains.Redis.DataContext.RedisContext
  parent: OpenSettings.Domains.Redis.DataContext
  href: OpenSettings.Domains.Redis.DataContext.RedisContext.html
  name: RedisContext
  nameWithType: RedisContext
  fullName: OpenSettings.Domains.Redis.DataContext.RedisContext
- uid: OpenSettings.Domains.Redis.DataContext.RedisContextOptions
  commentId: T:OpenSettings.Domains.Redis.DataContext.RedisContextOptions
  parent: OpenSettings.Domains.Redis.DataContext
  href: OpenSettings.Domains.Redis.DataContext.RedisContextOptions.html
  name: RedisContextOptions
  nameWithType: RedisContextOptions
  fullName: OpenSettings.Domains.Redis.DataContext.RedisContextOptions
- uid: OpenSettings.Domains.Redis.DataContext
  commentId: N:OpenSettings.Domains.Redis.DataContext
  href: OpenSettings.html
  name: OpenSettings.Domains.Redis.DataContext
  nameWithType: OpenSettings.Domains.Redis.DataContext
  fullName: OpenSettings.Domains.Redis.DataContext
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Redis
    name: Redis
    href: OpenSettings.Domains.Redis.html
  - name: .
  - uid: OpenSettings.Domains.Redis.DataContext
    name: DataContext
    href: OpenSettings.Domains.Redis.DataContext.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Redis
    name: Redis
    href: OpenSettings.Domains.Redis.html
  - name: .
  - uid: OpenSettings.Domains.Redis.DataContext
    name: DataContext
    href: OpenSettings.Domains.Redis.DataContext.html
