### YamlMime:ManagedReference
items:
- uid: OpenSettings.Attributes
  commentId: N:OpenSettings.Attributes
  id: OpenSettings.Attributes
  children:
  - OpenSettings.Attributes.ComputedIdentifierAttribute
  - OpenSettings.Attributes.RegistrationModeAttribute
  - OpenSettings.Attributes.StoreInSeparateFileAttribute
  langs:
  - csharp
  - vb
  name: OpenSettings.Attributes
  nameWithType: OpenSettings.Attributes
  fullName: OpenSettings.Attributes
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Attributes.ComputedIdentifierAttribute
  commentId: T:OpenSettings.Attributes.ComputedIdentifierAttribute
  href: OpenSettings.Attributes.ComputedIdentifierAttribute.html
  name: ComputedIdentifierAttribute
  nameWithType: ComputedIdentifierAttribute
  fullName: OpenSettings.Attributes.ComputedIdentifierAttribute
- uid: OpenSettings.Attributes.RegistrationModeAttribute
  commentId: T:OpenSettings.Attributes.RegistrationModeAttribute
  href: OpenSettings.Attributes.RegistrationModeAttribute.html
  name: RegistrationModeAttribute
  nameWithType: RegistrationModeAttribute
  fullName: OpenSettings.Attributes.RegistrationModeAttribute
- uid: OpenSettings.Attributes.StoreInSeparateFileAttribute
  commentId: T:OpenSettings.Attributes.StoreInSeparateFileAttribute
  href: OpenSettings.Attributes.StoreInSeparateFileAttribute.html
  name: StoreInSeparateFileAttribute
  nameWithType: StoreInSeparateFileAttribute
  fullName: OpenSettings.Attributes.StoreInSeparateFileAttribute
