### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Rest
  commentId: N:OpenSettings.Services.Rest
  id: OpenSettings.Services.Rest
  children:
  - OpenSettings.Services.Rest.AppGroupsRestService
  - OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  - OpenSettings.Services.Rest.AppTagMappingsRestService
  - OpenSettings.Services.Rest.AppsRestService
  - OpenSettings.Services.Rest.ConfigurationsRestService
  - OpenSettings.Services.Rest.IdentifiersRestService
  - OpenSettings.Services.Rest.InstancesRestService
  - OpenSettings.Services.Rest.LicensesRestService
  - OpenSettings.Services.Rest.NotificationsRestService
  - OpenSettings.Services.Rest.OpenSettingsRestService
  - OpenSettings.Services.Rest.ProviderRestService
  - OpenSettings.Services.Rest.QueryBuilder
  - OpenSettings.Services.Rest.SettingClassesRestService
  - OpenSettings.Services.Rest.SettingHistoriesRestService
  - OpenSettings.Services.Rest.SettingsRestService
  - OpenSettings.Services.Rest.TagsRestService
  - OpenSettings.Services.Rest.UsersRestService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Rest
  nameWithType: OpenSettings.Services.Rest
  fullName: OpenSettings.Services.Rest
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Rest.AppGroupsRestService
  commentId: T:OpenSettings.Services.Rest.AppGroupsRestService
  href: OpenSettings.Services.Rest.AppGroupsRestService.html
  name: AppGroupsRestService
  nameWithType: AppGroupsRestService
  fullName: OpenSettings.Services.Rest.AppGroupsRestService
- uid: OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  commentId: T:OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  href: OpenSettings.Services.Rest.AppIdentifierMappingsRestService.html
  name: AppIdentifierMappingsRestService
  nameWithType: AppIdentifierMappingsRestService
  fullName: OpenSettings.Services.Rest.AppIdentifierMappingsRestService
- uid: OpenSettings.Services.Rest.AppsRestService
  commentId: T:OpenSettings.Services.Rest.AppsRestService
  href: OpenSettings.Services.Rest.AppsRestService.html
  name: AppsRestService
  nameWithType: AppsRestService
  fullName: OpenSettings.Services.Rest.AppsRestService
- uid: OpenSettings.Services.Rest.AppTagMappingsRestService
  commentId: T:OpenSettings.Services.Rest.AppTagMappingsRestService
  href: OpenSettings.Services.Rest.AppTagMappingsRestService.html
  name: AppTagMappingsRestService
  nameWithType: AppTagMappingsRestService
  fullName: OpenSettings.Services.Rest.AppTagMappingsRestService
- uid: OpenSettings.Services.Rest.ConfigurationsRestService
  commentId: T:OpenSettings.Services.Rest.ConfigurationsRestService
  href: OpenSettings.Services.Rest.ConfigurationsRestService.html
  name: ConfigurationsRestService
  nameWithType: ConfigurationsRestService
  fullName: OpenSettings.Services.Rest.ConfigurationsRestService
- uid: OpenSettings.Services.Rest.IdentifiersRestService
  commentId: T:OpenSettings.Services.Rest.IdentifiersRestService
  href: OpenSettings.Services.Rest.IdentifiersRestService.html
  name: IdentifiersRestService
  nameWithType: IdentifiersRestService
  fullName: OpenSettings.Services.Rest.IdentifiersRestService
- uid: OpenSettings.Services.Rest.InstancesRestService
  commentId: T:OpenSettings.Services.Rest.InstancesRestService
  href: OpenSettings.Services.Rest.InstancesRestService.html
  name: InstancesRestService
  nameWithType: InstancesRestService
  fullName: OpenSettings.Services.Rest.InstancesRestService
- uid: OpenSettings.Services.Rest.LicensesRestService
  commentId: T:OpenSettings.Services.Rest.LicensesRestService
  href: OpenSettings.Services.Rest.LicensesRestService.html
  name: LicensesRestService
  nameWithType: LicensesRestService
  fullName: OpenSettings.Services.Rest.LicensesRestService
- uid: OpenSettings.Services.Rest.NotificationsRestService
  commentId: T:OpenSettings.Services.Rest.NotificationsRestService
  href: OpenSettings.Services.Rest.NotificationsRestService.html
  name: NotificationsRestService
  nameWithType: NotificationsRestService
  fullName: OpenSettings.Services.Rest.NotificationsRestService
- uid: OpenSettings.Services.Rest.OpenSettingsRestService
  commentId: T:OpenSettings.Services.Rest.OpenSettingsRestService
  href: OpenSettings.Services.Rest.OpenSettingsRestService.html
  name: OpenSettingsRestService
  nameWithType: OpenSettingsRestService
  fullName: OpenSettings.Services.Rest.OpenSettingsRestService
- uid: OpenSettings.Services.Rest.ProviderRestService
  commentId: T:OpenSettings.Services.Rest.ProviderRestService
  href: OpenSettings.Services.Rest.ProviderRestService.html
  name: ProviderRestService
  nameWithType: ProviderRestService
  fullName: OpenSettings.Services.Rest.ProviderRestService
- uid: OpenSettings.Services.Rest.QueryBuilder
  commentId: T:OpenSettings.Services.Rest.QueryBuilder
  parent: OpenSettings.Services.Rest
  href: OpenSettings.Services.Rest.QueryBuilder.html
  name: QueryBuilder
  nameWithType: QueryBuilder
  fullName: OpenSettings.Services.Rest.QueryBuilder
- uid: OpenSettings.Services.Rest.SettingClassesRestService
  commentId: T:OpenSettings.Services.Rest.SettingClassesRestService
  href: OpenSettings.Services.Rest.SettingClassesRestService.html
  name: SettingClassesRestService
  nameWithType: SettingClassesRestService
  fullName: OpenSettings.Services.Rest.SettingClassesRestService
- uid: OpenSettings.Services.Rest.SettingHistoriesRestService
  commentId: T:OpenSettings.Services.Rest.SettingHistoriesRestService
  href: OpenSettings.Services.Rest.SettingHistoriesRestService.html
  name: SettingHistoriesRestService
  nameWithType: SettingHistoriesRestService
  fullName: OpenSettings.Services.Rest.SettingHistoriesRestService
- uid: OpenSettings.Services.Rest.SettingsRestService
  commentId: T:OpenSettings.Services.Rest.SettingsRestService
  href: OpenSettings.Services.Rest.SettingsRestService.html
  name: SettingsRestService
  nameWithType: SettingsRestService
  fullName: OpenSettings.Services.Rest.SettingsRestService
- uid: OpenSettings.Services.Rest.TagsRestService
  commentId: T:OpenSettings.Services.Rest.TagsRestService
  href: OpenSettings.Services.Rest.TagsRestService.html
  name: TagsRestService
  nameWithType: TagsRestService
  fullName: OpenSettings.Services.Rest.TagsRestService
- uid: OpenSettings.Services.Rest.UsersRestService
  commentId: T:OpenSettings.Services.Rest.UsersRestService
  href: OpenSettings.Services.Rest.UsersRestService.html
  name: UsersRestService
  nameWithType: UsersRestService
  fullName: OpenSettings.Services.Rest.UsersRestService
- uid: OpenSettings.Services.Rest
  commentId: N:OpenSettings.Services.Rest
  href: OpenSettings.html
  name: OpenSettings.Services.Rest
  nameWithType: OpenSettings.Services.Rest
  fullName: OpenSettings.Services.Rest
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
