### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.MemoryCache
  commentId: N:OpenSettings.Services.MemoryCache
  id: OpenSettings.Services.MemoryCache
  children:
  - OpenSettings.Services.MemoryCache.MemoryCacheKeys
  - OpenSettings.Services.MemoryCache.OpenSettingsMemoryCache
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.MemoryCache
  nameWithType: OpenSettings.Services.MemoryCache
  fullName: OpenSettings.Services.MemoryCache
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.MemoryCache.MemoryCacheKeys
  commentId: T:OpenSettings.Services.MemoryCache.MemoryCacheKeys
  href: OpenSettings.Services.MemoryCache.MemoryCacheKeys.html
  name: MemoryCacheKeys
  nameWithType: MemoryCacheKeys
  fullName: OpenSettings.Services.MemoryCache.MemoryCacheKeys
- uid: OpenSettings.Services.MemoryCache.OpenSettingsMemoryCache
  commentId: T:OpenSettings.Services.MemoryCache.OpenSettingsMemoryCache
  parent: OpenSettings.Services.MemoryCache
  href: OpenSettings.Services.MemoryCache.OpenSettingsMemoryCache.html
  name: OpenSettingsMemoryCache
  nameWithType: OpenSettingsMemoryCache
  fullName: OpenSettings.Services.MemoryCache.OpenSettingsMemoryCache
- uid: OpenSettings.Services.MemoryCache
  commentId: N:OpenSettings.Services.MemoryCache
  href: OpenSettings.html
  name: OpenSettings.Services.MemoryCache
  nameWithType: OpenSettings.Services.MemoryCache
  fullName: OpenSettings.Services.MemoryCache
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.MemoryCache
    name: MemoryCache
    href: OpenSettings.Services.MemoryCache.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.MemoryCache
    name: MemoryCache
    href: OpenSettings.Services.MemoryCache.html
