### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.AppType
  commentId: T:OpenSettings.Models.AppType
  id: AppType
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.AppType.Dotnet
  - OpenSettings.Models.AppType.Java
  - OpenSettings.Models.AppType.NodeJs
  - OpenSettings.Models.AppType.Python
  - OpenSettings.Models.AppType.Unknown
  langs:
  - csharp
  - vb
  name: AppType
  nameWithType: AppType
  fullName: OpenSettings.Models.AppType
  type: Enum
  source:
    remote:
      path: src/OpenSettings/Models/AppType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: AppType
    path: ../../../open-settings/src/OpenSettings/Models/AppType.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public enum AppType
    content.vb: Public Enum AppType
- uid: OpenSettings.Models.AppType.Unknown
  commentId: F:OpenSettings.Models.AppType.Unknown
  id: Unknown
  parent: OpenSettings.Models.AppType
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: AppType.Unknown
  fullName: OpenSettings.Models.AppType.Unknown
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AppType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Unknown
    path: ../../../open-settings/src/OpenSettings/Models/AppType.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Unknown = 0
    return:
      type: OpenSettings.Models.AppType
- uid: OpenSettings.Models.AppType.Dotnet
  commentId: F:OpenSettings.Models.AppType.Dotnet
  id: Dotnet
  parent: OpenSettings.Models.AppType
  langs:
  - csharp
  - vb
  name: Dotnet
  nameWithType: AppType.Dotnet
  fullName: OpenSettings.Models.AppType.Dotnet
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AppType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Dotnet
    path: ../../../open-settings/src/OpenSettings/Models/AppType.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Dotnet = 1
    return:
      type: OpenSettings.Models.AppType
- uid: OpenSettings.Models.AppType.Java
  commentId: F:OpenSettings.Models.AppType.Java
  id: Java
  parent: OpenSettings.Models.AppType
  langs:
  - csharp
  - vb
  name: Java
  nameWithType: AppType.Java
  fullName: OpenSettings.Models.AppType.Java
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AppType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Java
    path: ../../../open-settings/src/OpenSettings/Models/AppType.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Java = 2
    return:
      type: OpenSettings.Models.AppType
- uid: OpenSettings.Models.AppType.Python
  commentId: F:OpenSettings.Models.AppType.Python
  id: Python
  parent: OpenSettings.Models.AppType
  langs:
  - csharp
  - vb
  name: Python
  nameWithType: AppType.Python
  fullName: OpenSettings.Models.AppType.Python
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AppType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Python
    path: ../../../open-settings/src/OpenSettings/Models/AppType.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Python = 3
    return:
      type: OpenSettings.Models.AppType
- uid: OpenSettings.Models.AppType.NodeJs
  commentId: F:OpenSettings.Models.AppType.NodeJs
  id: NodeJs
  parent: OpenSettings.Models.AppType
  langs:
  - csharp
  - vb
  name: NodeJs
  nameWithType: AppType.NodeJs
  fullName: OpenSettings.Models.AppType.NodeJs
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AppType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: NodeJs
    path: ../../../open-settings/src/OpenSettings/Models/AppType.cs
    startLine: 12
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: NodeJs = 4
    return:
      type: OpenSettings.Models.AppType
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: OpenSettings.Models.AppType
  commentId: T:OpenSettings.Models.AppType
  parent: OpenSettings.Models
  href: OpenSettings.Models.AppType.html
  name: AppType
  nameWithType: AppType
  fullName: OpenSettings.Models.AppType
