### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.DataAccessType
  commentId: T:OpenSettings.Models.DataAccessType
  id: DataAccessType
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.DataAccessType.Orm
  langs:
  - csharp
  - vb
  name: DataAccessType
  nameWithType: DataAccessType
  fullName: OpenSettings.Models.DataAccessType
  type: Enum
  source:
    remote:
      path: src/OpenSettings/Models/DataAccessType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: DataAccessType
    path: ../../../open-settings/src/OpenSettings/Models/DataAccessType.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  summary: >-
    Specifies the type of data access used by the provider for data persistence.

    This enum is used to define how data is stored and accessed within the provider.
  example: []
  syntax:
    content: public enum DataAccessType
    content.vb: Public Enum DataAccessType
- uid: OpenSettings.Models.DataAccessType.Orm
  commentId: F:OpenSettings.Models.DataAccessType.Orm
  id: Orm
  parent: OpenSettings.Models.DataAccessType
  langs:
  - csharp
  - vb
  name: Orm
  nameWithType: DataAccessType.Orm
  fullName: OpenSettings.Models.DataAccessType.Orm
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/DataAccessType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Orm
    path: ../../../open-settings/src/OpenSettings/Models/DataAccessType.cs
    startLine: 13
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  summary: >-
    Represents the use of an Object-Relational Mapper (ORM) for data persistence.

    The ORM approach abstracts the database interactions, allowing objects in the application 

    to be mapped to relational database tables.
  example: []
  syntax:
    content: Orm = 1
    return:
      type: OpenSettings.Models.DataAccessType
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: OpenSettings.Models.DataAccessType
  commentId: T:OpenSettings.Models.DataAccessType
  parent: OpenSettings.Models
  href: OpenSettings.Models.DataAccessType.html
  name: DataAccessType
  nameWithType: DataAccessType
  fullName: OpenSettings.Models.DataAccessType
