### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  id: OpenSettings.Models
  children:
  - OpenSettings.Models.AppType
  - OpenSettings.Models.CacheModel
  - OpenSettings.Models.ClientInfo
  - OpenSettings.Models.ConcurrencyConflict
  - OpenSettings.Models.ConcurrencyConflictInfo
  - OpenSettings.Models.ConcurrencyConflictValue
  - OpenSettings.Models.ConfigSource
  - OpenSettings.Models.ConfigurationConsumer
  - OpenSettings.Models.ConfigurationConsumerPollingSettingsWorker
  - OpenSettings.Models.ConfigurationController
  - OpenSettings.Models.ConfigurationProvider
  - OpenSettings.Models.ConfigurationSpa
  - OpenSettings.Models.ConflictModel
  - OpenSettings.Models.DataAccessType
  - OpenSettings.Models.FileMergeResult
  - OpenSettings.Models.FileModel
  - OpenSettings.Models.GeneratedSettingData
  - OpenSettings.Models.ILocalSetting
  - OpenSettings.Models.JsonMergeResult
  - OpenSettings.Models.License
  - OpenSettings.Models.LicenseEdition
  - OpenSettings.Models.NotificationSource
  - OpenSettings.Models.NotificationType
  - OpenSettings.Models.OAuth2Info
  - OpenSettings.Models.OpenSettingsAssemblyInfo
  - OpenSettings.Models.OpenSettingsConfigModel
  - OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
  - OpenSettings.Models.OpenSettingsConfigsDataModel
  - OpenSettings.Models.Operation
  - OpenSettings.Models.PagingInfo
  - OpenSettings.Models.PropertyInfoHelperModel
  - OpenSettings.Models.ProviderInfo
  - OpenSettings.Models.ProviderInfoClient
  - OpenSettings.Models.ProviderRegistryScheme
  - OpenSettings.Models.RedisInfo
  - OpenSettings.Models.RedisMessage
  - OpenSettings.Models.RedisMessageType
  - OpenSettings.Models.RegistrationMode
  - OpenSettings.Models.ReloadStrategy
  - OpenSettings.Models.ReorderResponse
  - OpenSettings.Models.SerializerType
  - OpenSettings.Models.ServiceType
  - OpenSettings.Models.SetSortOrderPosition
  - OpenSettings.Models.SortDirection
  langs:
  - csharp
  - vb
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Models.AppType
  commentId: T:OpenSettings.Models.AppType
  parent: OpenSettings.Models
  href: OpenSettings.Models.AppType.html
  name: AppType
  nameWithType: AppType
  fullName: OpenSettings.Models.AppType
- uid: OpenSettings.Models.CacheModel
  commentId: T:OpenSettings.Models.CacheModel
  parent: OpenSettings.Models
  href: OpenSettings.Models.CacheModel.html
  name: CacheModel
  nameWithType: CacheModel
  fullName: OpenSettings.Models.CacheModel
- uid: OpenSettings.Models.ClientInfo
  commentId: T:OpenSettings.Models.ClientInfo
  parent: OpenSettings.Models
  href: OpenSettings.Models.ClientInfo.html
  name: ClientInfo
  nameWithType: ClientInfo
  fullName: OpenSettings.Models.ClientInfo
- uid: OpenSettings.Models.ConcurrencyConflict
  commentId: T:OpenSettings.Models.ConcurrencyConflict
  href: OpenSettings.Models.ConcurrencyConflict.html
  name: ConcurrencyConflict
  nameWithType: ConcurrencyConflict
  fullName: OpenSettings.Models.ConcurrencyConflict
- uid: OpenSettings.Models.ConcurrencyConflictInfo
  commentId: T:OpenSettings.Models.ConcurrencyConflictInfo
  href: OpenSettings.Models.ConcurrencyConflictInfo.html
  name: ConcurrencyConflictInfo
  nameWithType: ConcurrencyConflictInfo
  fullName: OpenSettings.Models.ConcurrencyConflictInfo
- uid: OpenSettings.Models.ConcurrencyConflictValue
  commentId: T:OpenSettings.Models.ConcurrencyConflictValue
  href: OpenSettings.Models.ConcurrencyConflictValue.html
  name: ConcurrencyConflictValue
  nameWithType: ConcurrencyConflictValue
  fullName: OpenSettings.Models.ConcurrencyConflictValue
- uid: OpenSettings.Models.ConfigSource
  commentId: T:OpenSettings.Models.ConfigSource
  parent: OpenSettings.Models
  href: OpenSettings.Models.ConfigSource.html
  name: ConfigSource
  nameWithType: ConfigSource
  fullName: OpenSettings.Models.ConfigSource
- uid: OpenSettings.Models.ConfigurationConsumer
  commentId: T:OpenSettings.Models.ConfigurationConsumer
  parent: OpenSettings.Models
  href: OpenSettings.Models.ConfigurationConsumer.html
  name: ConfigurationConsumer
  nameWithType: ConfigurationConsumer
  fullName: OpenSettings.Models.ConfigurationConsumer
- uid: OpenSettings.Models.ConfigurationConsumerPollingSettingsWorker
  commentId: T:OpenSettings.Models.ConfigurationConsumerPollingSettingsWorker
  parent: OpenSettings.Models
  href: OpenSettings.Models.ConfigurationConsumerPollingSettingsWorker.html
  name: ConfigurationConsumerPollingSettingsWorker
  nameWithType: ConfigurationConsumerPollingSettingsWorker
  fullName: OpenSettings.Models.ConfigurationConsumerPollingSettingsWorker
- uid: OpenSettings.Models.ConfigurationController
  commentId: T:OpenSettings.Models.ConfigurationController
  parent: OpenSettings.Models
  href: OpenSettings.Models.ConfigurationController.html
  name: ConfigurationController
  nameWithType: ConfigurationController
  fullName: OpenSettings.Models.ConfigurationController
- uid: OpenSettings.Models.ConfigurationProvider
  commentId: T:OpenSettings.Models.ConfigurationProvider
  parent: OpenSettings.Models
  href: OpenSettings.Models.ConfigurationProvider.html
  name: ConfigurationProvider
  nameWithType: ConfigurationProvider
  fullName: OpenSettings.Models.ConfigurationProvider
- uid: OpenSettings.Models.ConfigurationSpa
  commentId: T:OpenSettings.Models.ConfigurationSpa
  parent: OpenSettings.Models
  href: OpenSettings.Models.ConfigurationSpa.html
  name: ConfigurationSpa
  nameWithType: ConfigurationSpa
  fullName: OpenSettings.Models.ConfigurationSpa
- uid: OpenSettings.Models.ConflictModel
  commentId: T:OpenSettings.Models.ConflictModel
  href: OpenSettings.Models.ConflictModel.html
  name: ConflictModel
  nameWithType: ConflictModel
  fullName: OpenSettings.Models.ConflictModel
- uid: OpenSettings.Models.DataAccessType
  commentId: T:OpenSettings.Models.DataAccessType
  parent: OpenSettings.Models
  href: OpenSettings.Models.DataAccessType.html
  name: DataAccessType
  nameWithType: DataAccessType
  fullName: OpenSettings.Models.DataAccessType
- uid: OpenSettings.Models.FileMergeResult
  commentId: T:OpenSettings.Models.FileMergeResult
  href: OpenSettings.Models.FileMergeResult.html
  name: FileMergeResult
  nameWithType: FileMergeResult
  fullName: OpenSettings.Models.FileMergeResult
- uid: OpenSettings.Models.FileModel
  commentId: T:OpenSettings.Models.FileModel
  href: OpenSettings.Models.FileModel.html
  name: FileModel
  nameWithType: FileModel
  fullName: OpenSettings.Models.FileModel
- uid: OpenSettings.Models.GeneratedSettingData
  commentId: T:OpenSettings.Models.GeneratedSettingData
  href: OpenSettings.Models.GeneratedSettingData.html
  name: GeneratedSettingData
  nameWithType: GeneratedSettingData
  fullName: OpenSettings.Models.GeneratedSettingData
- uid: OpenSettings.Models.ILocalSetting
  commentId: T:OpenSettings.Models.ILocalSetting
  href: OpenSettings.Models.ILocalSetting.html
  name: ILocalSetting
  nameWithType: ILocalSetting
  fullName: OpenSettings.Models.ILocalSetting
- uid: OpenSettings.Models.JsonMergeResult
  commentId: T:OpenSettings.Models.JsonMergeResult
  parent: OpenSettings.Models
  href: OpenSettings.Models.JsonMergeResult.html
  name: JsonMergeResult
  nameWithType: JsonMergeResult
  fullName: OpenSettings.Models.JsonMergeResult
- uid: OpenSettings.Models.License
  commentId: T:OpenSettings.Models.License
  parent: OpenSettings.Models
  href: OpenSettings.Models.License.html
  name: License
  nameWithType: License
  fullName: OpenSettings.Models.License
- uid: OpenSettings.Models.LicenseEdition
  commentId: T:OpenSettings.Models.LicenseEdition
  parent: OpenSettings.Models
  href: OpenSettings.Models.LicenseEdition.html
  name: LicenseEdition
  nameWithType: LicenseEdition
  fullName: OpenSettings.Models.LicenseEdition
- uid: OpenSettings.Models.NotificationSource
  commentId: T:OpenSettings.Models.NotificationSource
  parent: OpenSettings.Models
  href: OpenSettings.Models.NotificationSource.html
  name: NotificationSource
  nameWithType: NotificationSource
  fullName: OpenSettings.Models.NotificationSource
- uid: OpenSettings.Models.NotificationType
  commentId: T:OpenSettings.Models.NotificationType
  parent: OpenSettings.Models
  href: OpenSettings.Models.NotificationType.html
  name: NotificationType
  nameWithType: NotificationType
  fullName: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.OAuth2Info
  commentId: T:OpenSettings.Models.OAuth2Info
  parent: OpenSettings.Models
  href: OpenSettings.Models.OAuth2Info.html
  name: OAuth2Info
  nameWithType: OAuth2Info
  fullName: OpenSettings.Models.OAuth2Info
- uid: OpenSettings.Models.OpenSettingsAssemblyInfo
  commentId: T:OpenSettings.Models.OpenSettingsAssemblyInfo
  parent: OpenSettings.Models
  href: OpenSettings.Models.OpenSettingsAssemblyInfo.html
  name: OpenSettingsAssemblyInfo
  nameWithType: OpenSettingsAssemblyInfo
  fullName: OpenSettings.Models.OpenSettingsAssemblyInfo
- uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
  commentId: T:OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
  href: OpenSettings.Models.OpenSettingsConfigsDataCacheModel-1.html
  name: OpenSettingsConfigsDataCacheModel<T>
  nameWithType: OpenSettingsConfigsDataCacheModel<T>
  fullName: OpenSettings.Models.OpenSettingsConfigsDataCacheModel<T>
  nameWithType.vb: OpenSettingsConfigsDataCacheModel(Of T)
  fullName.vb: OpenSettings.Models.OpenSettingsConfigsDataCacheModel(Of T)
  name.vb: OpenSettingsConfigsDataCacheModel(Of T)
  spec.csharp:
  - uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
    name: OpenSettingsConfigsDataCacheModel
    href: OpenSettings.Models.OpenSettingsConfigsDataCacheModel-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: OpenSettings.Models.OpenSettingsConfigsDataCacheModel`1
    name: OpenSettingsConfigsDataCacheModel
    href: OpenSettings.Models.OpenSettingsConfigsDataCacheModel-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: OpenSettings.Models.OpenSettingsConfigsDataModel
  commentId: T:OpenSettings.Models.OpenSettingsConfigsDataModel
  href: OpenSettings.Models.OpenSettingsConfigsDataModel.html
  name: OpenSettingsConfigsDataModel
  nameWithType: OpenSettingsConfigsDataModel
  fullName: OpenSettings.Models.OpenSettingsConfigsDataModel
- uid: OpenSettings.Models.OpenSettingsConfigModel
  commentId: T:OpenSettings.Models.OpenSettingsConfigModel
  href: OpenSettings.Models.OpenSettingsConfigModel.html
  name: OpenSettingsConfigModel
  nameWithType: OpenSettingsConfigModel
  fullName: OpenSettings.Models.OpenSettingsConfigModel
- uid: OpenSettings.Models.Operation
  commentId: T:OpenSettings.Models.Operation
  parent: OpenSettings.Models
  href: OpenSettings.Models.Operation.html
  name: Operation
  nameWithType: Operation
  fullName: OpenSettings.Models.Operation
- uid: OpenSettings.Models.PagingInfo
  commentId: T:OpenSettings.Models.PagingInfo
  parent: OpenSettings.Models
  href: OpenSettings.Models.PagingInfo.html
  name: PagingInfo
  nameWithType: PagingInfo
  fullName: OpenSettings.Models.PagingInfo
- uid: OpenSettings.Models.PropertyInfoHelperModel
  commentId: T:OpenSettings.Models.PropertyInfoHelperModel
  parent: OpenSettings.Models
  href: OpenSettings.Models.PropertyInfoHelperModel.html
  name: PropertyInfoHelperModel
  nameWithType: PropertyInfoHelperModel
  fullName: OpenSettings.Models.PropertyInfoHelperModel
- uid: OpenSettings.Models.ProviderInfo
  commentId: T:OpenSettings.Models.ProviderInfo
  parent: OpenSettings.Models
  href: OpenSettings.Models.ProviderInfo.html
  name: ProviderInfo
  nameWithType: ProviderInfo
  fullName: OpenSettings.Models.ProviderInfo
- uid: OpenSettings.Models.ProviderInfoClient
  commentId: T:OpenSettings.Models.ProviderInfoClient
  parent: OpenSettings.Models
  href: OpenSettings.Models.ProviderInfoClient.html
  name: ProviderInfoClient
  nameWithType: ProviderInfoClient
  fullName: OpenSettings.Models.ProviderInfoClient
- uid: OpenSettings.Models.ProviderRegistryScheme
  commentId: T:OpenSettings.Models.ProviderRegistryScheme
  parent: OpenSettings.Models
  href: OpenSettings.Models.ProviderRegistryScheme.html
  name: ProviderRegistryScheme
  nameWithType: ProviderRegistryScheme
  fullName: OpenSettings.Models.ProviderRegistryScheme
- uid: OpenSettings.Models.RedisInfo
  commentId: T:OpenSettings.Models.RedisInfo
  parent: OpenSettings.Models
  href: OpenSettings.Models.RedisInfo.html
  name: RedisInfo
  nameWithType: RedisInfo
  fullName: OpenSettings.Models.RedisInfo
- uid: OpenSettings.Models.RedisMessage
  commentId: T:OpenSettings.Models.RedisMessage
  parent: OpenSettings.Models
  href: OpenSettings.Models.RedisMessage.html
  name: RedisMessage
  nameWithType: RedisMessage
  fullName: OpenSettings.Models.RedisMessage
- uid: OpenSettings.Models.RedisMessageType
  commentId: T:OpenSettings.Models.RedisMessageType
  parent: OpenSettings.Models
  href: OpenSettings.Models.RedisMessageType.html
  name: RedisMessageType
  nameWithType: RedisMessageType
  fullName: OpenSettings.Models.RedisMessageType
- uid: OpenSettings.Models.RegistrationMode
  commentId: T:OpenSettings.Models.RegistrationMode
  parent: OpenSettings.Models
  href: OpenSettings.Models.RegistrationMode.html
  name: RegistrationMode
  nameWithType: RegistrationMode
  fullName: OpenSettings.Models.RegistrationMode
- uid: OpenSettings.Models.ReloadStrategy
  commentId: T:OpenSettings.Models.ReloadStrategy
  parent: OpenSettings.Models
  href: OpenSettings.Models.ReloadStrategy.html
  name: ReloadStrategy
  nameWithType: ReloadStrategy
  fullName: OpenSettings.Models.ReloadStrategy
- uid: OpenSettings.Models.ReorderResponse
  commentId: T:OpenSettings.Models.ReorderResponse
  href: OpenSettings.Models.ReorderResponse.html
  name: ReorderResponse
  nameWithType: ReorderResponse
  fullName: OpenSettings.Models.ReorderResponse
- uid: OpenSettings.Models.SerializerType
  commentId: T:OpenSettings.Models.SerializerType
  parent: OpenSettings.Models
  href: OpenSettings.Models.SerializerType.html
  name: SerializerType
  nameWithType: SerializerType
  fullName: OpenSettings.Models.SerializerType
- uid: OpenSettings.Models.ServiceType
  commentId: T:OpenSettings.Models.ServiceType
  parent: OpenSettings.Models
  href: OpenSettings.Models.ServiceType.html
  name: ServiceType
  nameWithType: ServiceType
  fullName: OpenSettings.Models.ServiceType
- uid: OpenSettings.Models.SetSortOrderPosition
  commentId: T:OpenSettings.Models.SetSortOrderPosition
  parent: OpenSettings.Models
  href: OpenSettings.Models.SetSortOrderPosition.html
  name: SetSortOrderPosition
  nameWithType: SetSortOrderPosition
  fullName: OpenSettings.Models.SetSortOrderPosition
- uid: OpenSettings.Models.SortDirection
  commentId: T:OpenSettings.Models.SortDirection
  parent: OpenSettings.Models
  href: OpenSettings.Models.SortDirection.html
  name: SortDirection
  nameWithType: SortDirection
  fullName: OpenSettings.Models.SortDirection
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
