### YamlMime:ManagedReference
items:
- uid: OpenSettings.Configurations
  commentId: N:OpenSettings.Configurations
  id: OpenSettings.Configurations
  children:
  - OpenSettings.Configurations.ConsumerConfiguration
  - OpenSettings.Configurations.OpenSettingsConfiguration
  - OpenSettings.Configurations.OrmConfiguration
  - OpenSettings.Configurations.PollingSettingsWorkerConfiguration
  - OpenSettings.Configurations.ProviderConfiguration
  - OpenSettings.Configurations.RedisConfiguration
  langs:
  - csharp
  - vb
  name: OpenSettings.Configurations
  nameWithType: OpenSettings.Configurations
  fullName: OpenSettings.Configurations
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Configurations.ConsumerConfiguration
  commentId: T:OpenSettings.Configurations.ConsumerConfiguration
  parent: OpenSettings.Configurations
  href: OpenSettings.Configurations.ConsumerConfiguration.html
  name: ConsumerConfiguration
  nameWithType: ConsumerConfiguration
  fullName: OpenSettings.Configurations.ConsumerConfiguration
- uid: OpenSettings.Configurations.OpenSettingsConfiguration
  commentId: T:OpenSettings.Configurations.OpenSettingsConfiguration
  parent: OpenSettings.Configurations
  href: OpenSettings.Configurations.OpenSettingsConfiguration.html
  name: OpenSettingsConfiguration
  nameWithType: OpenSettingsConfiguration
  fullName: OpenSettings.Configurations.OpenSettingsConfiguration
- uid: OpenSettings.Configurations.OrmConfiguration
  commentId: T:OpenSettings.Configurations.OrmConfiguration
  parent: OpenSettings.Configurations
  href: OpenSettings.Configurations.OrmConfiguration.html
  name: OrmConfiguration
  nameWithType: OrmConfiguration
  fullName: OpenSettings.Configurations.OrmConfiguration
- uid: OpenSettings.Configurations.PollingSettingsWorkerConfiguration
  commentId: T:OpenSettings.Configurations.PollingSettingsWorkerConfiguration
  parent: OpenSettings.Configurations
  href: OpenSettings.Configurations.PollingSettingsWorkerConfiguration.html
  name: PollingSettingsWorkerConfiguration
  nameWithType: PollingSettingsWorkerConfiguration
  fullName: OpenSettings.Configurations.PollingSettingsWorkerConfiguration
- uid: OpenSettings.Configurations.ProviderConfiguration
  commentId: T:OpenSettings.Configurations.ProviderConfiguration
  parent: OpenSettings.Configurations
  href: OpenSettings.Configurations.ProviderConfiguration.html
  name: ProviderConfiguration
  nameWithType: ProviderConfiguration
  fullName: OpenSettings.Configurations.ProviderConfiguration
- uid: OpenSettings.Configurations.RedisConfiguration
  commentId: T:OpenSettings.Configurations.RedisConfiguration
  parent: OpenSettings.Configurations
  href: OpenSettings.Configurations.RedisConfiguration.html
  name: RedisConfiguration
  nameWithType: RedisConfiguration
  fullName: OpenSettings.Configurations.RedisConfiguration
- uid: OpenSettings.Configurations
  commentId: N:OpenSettings.Configurations
  href: OpenSettings.html
  name: OpenSettings.Configurations
  nameWithType: OpenSettings.Configurations
  fullName: OpenSettings.Configurations
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Configurations
    name: Configurations
    href: OpenSettings.Configurations.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Configurations
    name: Configurations
    href: OpenSettings.Configurations.html
