### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Interfaces.ISettingClassesService
  commentId: T:OpenSettings.Services.Interfaces.ISettingClassesService
  id: ISettingClassesService
  parent: OpenSettings.Services.Interfaces
  children: []
  langs:
  - csharp
  - vb
  name: ISettingClassesService
  nameWithType: ISettingClassesService
  fullName: OpenSettings.Services.Interfaces.ISettingClassesService
  type: Interface
  source:
    remote:
      path: src/OpenSettings/Services/Interfaces/ISettingClassesService.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: ISettingClassesService
    path: ../../../open-settings/src/OpenSettings/Services/Interfaces/ISettingClassesService.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.Interfaces
  syntax:
    content: public interface ISettingClassesService
    content.vb: Public Interface ISettingClassesService
references:
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
