### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService
  commentId: T:OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService
  id: IUserNotificationMappingsSqlService
  parent: OpenSettings.Services.Sql.Interfaces
  children: []
  langs:
  - csharp
  - vb
  name: IUserNotificationMappingsSqlService
  nameWithType: IUserNotificationMappingsSqlService
  fullName: OpenSettings.Services.Sql.Interfaces.IUserNotificationMappingsSqlService
  type: Interface
  source:
    remote:
      path: src/OpenSettings/Services/Sql/Interfaces/IUserNotificationMappingsSqlService.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IUserNotificationMappingsSqlService
    path: ../../../open-settings/src/OpenSettings/Services/Sql/Interfaces/IUserNotificationMappingsSqlService.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.Sql.Interfaces
  syntax:
    content: 'public interface IUserNotificationMappingsSqlService : IUserNotificationMappingsService'
    content.vb: Public Interface IUserNotificationMappingsSqlService Inherits IUserNotificationMappingsService
references:
- uid: OpenSettings.Services.Sql.Interfaces
  commentId: N:OpenSettings.Services.Sql.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Sql.Interfaces
  nameWithType: OpenSettings.Services.Sql.Interfaces
  fullName: OpenSettings.Services.Sql.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Sql
    name: Sql
    href: OpenSettings.Services.Sql.html
  - name: .
  - uid: OpenSettings.Services.Sql.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Sql.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Sql
    name: Sql
    href: OpenSettings.Services.Sql.html
  - name: .
  - uid: OpenSettings.Services.Sql.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Sql.Interfaces.html
