### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Controllers.v1
  commentId: N:OpenSettings.AspNetCore.Controllers.v1
  id: OpenSettings.AspNetCore.Controllers.v1
  children:
  - OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
  - OpenSettings.AspNetCore.Controllers.v1.AppsController
  - OpenSettings.AspNetCore.Controllers.v1.AuthController
  - OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
  - OpenSettings.AspNetCore.Controllers.v1.InstancesController
  - OpenSettings.AspNetCore.Controllers.v1.LicensesController
  - OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
  - OpenSettings.AspNetCore.Controllers.v1.NotificationsController
  - OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
  - OpenSettings.AspNetCore.Controllers.v1.ProviderController
  - OpenSettings.AspNetCore.Controllers.v1.SettingHistoriesController
  - OpenSettings.AspNetCore.Controllers.v1.SettingsController
  - OpenSettings.AspNetCore.Controllers.v1.TagsController
  - OpenSettings.AspNetCore.Controllers.v1.UsersController
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore.Controllers.v1
  nameWithType: OpenSettings.AspNetCore.Controllers.v1
  fullName: OpenSettings.AspNetCore.Controllers.v1
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore
references:
- uid: OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
  href: OpenSettings.AspNetCore.Controllers.v1.AppGroupsController.html
  name: AppGroupsController
  nameWithType: AppGroupsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
- uid: OpenSettings.AspNetCore.Controllers.v1.AppsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppsController
  href: OpenSettings.AspNetCore.Controllers.v1.AppsController.html
  name: AppsController
  nameWithType: AppsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppsController
- uid: OpenSettings.AspNetCore.Controllers.v1.AuthController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AuthController
  href: OpenSettings.AspNetCore.Controllers.v1.AuthController.html
  name: AuthController
  nameWithType: AuthController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AuthController
- uid: OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
  href: OpenSettings.AspNetCore.Controllers.v1.IdentifiersController.html
  name: IdentifiersController
  nameWithType: IdentifiersController
  fullName: OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
- uid: OpenSettings.AspNetCore.Controllers.v1.InstancesController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.InstancesController
  href: OpenSettings.AspNetCore.Controllers.v1.InstancesController.html
  name: InstancesController
  nameWithType: InstancesController
  fullName: OpenSettings.AspNetCore.Controllers.v1.InstancesController
- uid: OpenSettings.AspNetCore.Controllers.v1.LicensesController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.LicensesController
  href: OpenSettings.AspNetCore.Controllers.v1.LicensesController.html
  name: LicensesController
  nameWithType: LicensesController
  fullName: OpenSettings.AspNetCore.Controllers.v1.LicensesController
- uid: OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
  href: OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController.html
  name: LocalSettingsController
  nameWithType: LocalSettingsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
- uid: OpenSettings.AspNetCore.Controllers.v1.NotificationsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.NotificationsController
  href: OpenSettings.AspNetCore.Controllers.v1.NotificationsController.html
  name: NotificationsController
  nameWithType: NotificationsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.NotificationsController
- uid: OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
  href: OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController.html
  name: OpenSettingsController
  nameWithType: OpenSettingsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
- uid: OpenSettings.AspNetCore.Controllers.v1.ProviderController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.ProviderController
  href: OpenSettings.AspNetCore.Controllers.v1.ProviderController.html
  name: ProviderController
  nameWithType: ProviderController
  fullName: OpenSettings.AspNetCore.Controllers.v1.ProviderController
- uid: OpenSettings.AspNetCore.Controllers.v1.SettingHistoriesController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.SettingHistoriesController
  href: OpenSettings.AspNetCore.Controllers.v1.SettingHistoriesController.html
  name: SettingHistoriesController
  nameWithType: SettingHistoriesController
  fullName: OpenSettings.AspNetCore.Controllers.v1.SettingHistoriesController
- uid: OpenSettings.AspNetCore.Controllers.v1.SettingsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.SettingsController
  href: OpenSettings.AspNetCore.Controllers.v1.SettingsController.html
  name: SettingsController
  nameWithType: SettingsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.SettingsController
- uid: OpenSettings.AspNetCore.Controllers.v1.TagsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.TagsController
  href: OpenSettings.AspNetCore.Controllers.v1.TagsController.html
  name: TagsController
  nameWithType: TagsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.TagsController
- uid: OpenSettings.AspNetCore.Controllers.v1.UsersController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.UsersController
  href: OpenSettings.AspNetCore.Controllers.v1.UsersController.html
  name: UsersController
  nameWithType: UsersController
  fullName: OpenSettings.AspNetCore.Controllers.v1.UsersController
