### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Extensions
  commentId: N:OpenSettings.AspNetCore.Extensions
  id: OpenSettings.AspNetCore.Extensions
  children:
  - OpenSettings.AspNetCore.Extensions.ApplicationBuilderExtensions
  - OpenSettings.AspNetCore.Extensions.MvcBuilderExtensions
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore.Extensions
  nameWithType: OpenSettings.AspNetCore.Extensions
  fullName: OpenSettings.AspNetCore.Extensions
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore
references:
- uid: OpenSettings.AspNetCore.Extensions.ApplicationBuilderExtensions
  commentId: T:OpenSettings.AspNetCore.Extensions.ApplicationBuilderExtensions
  href: OpenSettings.AspNetCore.Extensions.ApplicationBuilderExtensions.html
  name: ApplicationBuilderExtensions
  nameWithType: ApplicationBuilderExtensions
  fullName: OpenSettings.AspNetCore.Extensions.ApplicationBuilderExtensions
- uid: OpenSettings.AspNetCore.Extensions.MvcBuilderExtensions
  commentId: T:OpenSettings.AspNetCore.Extensions.MvcBuilderExtensions
  href: OpenSettings.AspNetCore.Extensions.MvcBuilderExtensions.html
  name: MvcBuilderExtensions
  nameWithType: MvcBuilderExtensions
  fullName: OpenSettings.AspNetCore.Extensions.MvcBuilderExtensions
