### YamlMime:ManagedReference
items:
- uid: OpenSettings.Extensions
  commentId: N:OpenSettings.Extensions
  id: OpenSettings.Extensions
  children:
  - OpenSettings.Extensions.CacheModelExtensions
  - OpenSettings.Extensions.ConfigurationBuilderExtensions
  - OpenSettings.Extensions.DictionaryExtensions
  - OpenSettings.Extensions.HostBuilderExtensions
  - OpenSettings.Extensions.HttpContentResponseExtensions
  - OpenSettings.Extensions.ServiceCollectionExtensions
  - OpenSettings.Extensions.ServiceProviderExtensions
  - OpenSettings.Extensions.SettingsExtensions
  langs:
  - csharp
  - vb
  name: OpenSettings.Extensions
  nameWithType: OpenSettings.Extensions
  fullName: OpenSettings.Extensions
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Extensions.CacheModelExtensions
  commentId: T:OpenSettings.Extensions.CacheModelExtensions
  parent: OpenSettings.Extensions
  href: OpenSettings.Extensions.CacheModelExtensions.html
  name: CacheModelExtensions
  nameWithType: CacheModelExtensions
  fullName: OpenSettings.Extensions.CacheModelExtensions
- uid: OpenSettings.Extensions.ConfigurationBuilderExtensions
  commentId: T:OpenSettings.Extensions.ConfigurationBuilderExtensions
  href: OpenSettings.Extensions.ConfigurationBuilderExtensions.html
  name: ConfigurationBuilderExtensions
  nameWithType: ConfigurationBuilderExtensions
  fullName: OpenSettings.Extensions.ConfigurationBuilderExtensions
- uid: OpenSettings.Extensions.DictionaryExtensions
  commentId: T:OpenSettings.Extensions.DictionaryExtensions
  href: OpenSettings.Extensions.DictionaryExtensions.html
  name: DictionaryExtensions
  nameWithType: DictionaryExtensions
  fullName: OpenSettings.Extensions.DictionaryExtensions
- uid: OpenSettings.Extensions.HostBuilderExtensions
  commentId: T:OpenSettings.Extensions.HostBuilderExtensions
  href: OpenSettings.Extensions.HostBuilderExtensions.html
  name: HostBuilderExtensions
  nameWithType: HostBuilderExtensions
  fullName: OpenSettings.Extensions.HostBuilderExtensions
- uid: OpenSettings.Extensions.HttpContentResponseExtensions
  commentId: T:OpenSettings.Extensions.HttpContentResponseExtensions
  href: OpenSettings.Extensions.HttpContentResponseExtensions.html
  name: HttpContentResponseExtensions
  nameWithType: HttpContentResponseExtensions
  fullName: OpenSettings.Extensions.HttpContentResponseExtensions
- uid: OpenSettings.Extensions.ServiceCollectionExtensions
  commentId: T:OpenSettings.Extensions.ServiceCollectionExtensions
  href: OpenSettings.Extensions.ServiceCollectionExtensions.html
  name: ServiceCollectionExtensions
  nameWithType: ServiceCollectionExtensions
  fullName: OpenSettings.Extensions.ServiceCollectionExtensions
- uid: OpenSettings.Extensions.ServiceProviderExtensions
  commentId: T:OpenSettings.Extensions.ServiceProviderExtensions
  href: OpenSettings.Extensions.ServiceProviderExtensions.html
  name: ServiceProviderExtensions
  nameWithType: ServiceProviderExtensions
  fullName: OpenSettings.Extensions.ServiceProviderExtensions
- uid: OpenSettings.Extensions.SettingsExtensions
  commentId: T:OpenSettings.Extensions.SettingsExtensions
  parent: OpenSettings.Extensions
  href: OpenSettings.Extensions.SettingsExtensions.html
  name: SettingsExtensions
  nameWithType: SettingsExtensions
  fullName: OpenSettings.Extensions.SettingsExtensions
- uid: OpenSettings.Extensions
  commentId: N:OpenSettings.Extensions
  href: OpenSettings.html
  name: OpenSettings.Extensions
  nameWithType: OpenSettings.Extensions
  fullName: OpenSettings.Extensions
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Extensions
    name: Extensions
    href: OpenSettings.Extensions.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Extensions
    name: Extensions
    href: OpenSettings.Extensions.html
