### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore
  commentId: N:OpenSettings.AspNetCore
  id: OpenSettings.AspNetCore
  children:
  - OpenSettings.AspNetCore.ApplicationBuilderExtensions
  - OpenSettings.AspNetCore.IOpenSettingsTokenService
  - OpenSettings.AspNetCore.MvcBuilderExtensions
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore
  nameWithType: OpenSettings.AspNetCore
  fullName: OpenSettings.AspNetCore
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore
references:
- uid: OpenSettings.AspNetCore.ApplicationBuilderExtensions
  commentId: T:OpenSettings.AspNetCore.ApplicationBuilderExtensions
  href: OpenSettings.AspNetCore.ApplicationBuilderExtensions.html
  name: ApplicationBuilderExtensions
  nameWithType: ApplicationBuilderExtensions
  fullName: OpenSettings.AspNetCore.ApplicationBuilderExtensions
- uid: OpenSettings.AspNetCore.IOpenSettingsTokenService
  commentId: T:OpenSettings.AspNetCore.IOpenSettingsTokenService
  parent: OpenSettings.AspNetCore
  href: OpenSettings.AspNetCore.IOpenSettingsTokenService.html
  name: IOpenSettingsTokenService
  nameWithType: IOpenSettingsTokenService
  fullName: OpenSettings.AspNetCore.IOpenSettingsTokenService
- uid: OpenSettings.AspNetCore.MvcBuilderExtensions
  commentId: T:OpenSettings.AspNetCore.MvcBuilderExtensions
  href: OpenSettings.AspNetCore.MvcBuilderExtensions.html
  name: MvcBuilderExtensions
  nameWithType: MvcBuilderExtensions
  fullName: OpenSettings.AspNetCore.MvcBuilderExtensions
- uid: OpenSettings.AspNetCore
  commentId: N:OpenSettings.AspNetCore
  href: OpenSettings.html
  name: OpenSettings.AspNetCore
  nameWithType: OpenSettings.AspNetCore
  fullName: OpenSettings.AspNetCore
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
