### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse
  commentId: T:OpenSettings.Models.Responses.GetOrCreateUserResponse
  id: GetOrCreateUserResponse
  parent: OpenSettings.Models.Responses
  children:
  - OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName
  - OpenSettings.Models.Responses.GetOrCreateUserResponse.Id
  - OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials
  - OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive
  - OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated
  langs:
  - csharp
  - vb
  name: GetOrCreateUserResponse
  nameWithType: GetOrCreateUserResponse
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse
  type: Class
  source:
    remote:
      path: src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: GetOrCreateUserResponse
    path: ../../../open-settings/src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Responses
  syntax:
    content: public class GetOrCreateUserResponse
    content.vb: Public Class GetOrCreateUserResponse
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.Id
  commentId: P:OpenSettings.Models.Responses.GetOrCreateUserResponse.Id
  id: Id
  parent: OpenSettings.Models.Responses.GetOrCreateUserResponse
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: GetOrCreateUserResponse.Id
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.Id
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Id
    path: ../../../open-settings/src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Responses
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: OpenSettings.Models.Responses.GetOrCreateUserResponse.Id*
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName
  commentId: P:OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName
  id: DisplayName
  parent: OpenSettings.Models.Responses.GetOrCreateUserResponse
  langs:
  - csharp
  - vb
  name: DisplayName
  nameWithType: GetOrCreateUserResponse.DisplayName
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: DisplayName
    path: ../../../open-settings/src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Responses
  syntax:
    content: public string DisplayName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DisplayName As String
  overload: OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName*
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials
  commentId: P:OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials
  id: Initials
  parent: OpenSettings.Models.Responses.GetOrCreateUserResponse
  langs:
  - csharp
  - vb
  name: Initials
  nameWithType: GetOrCreateUserResponse.Initials
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Initials
    path: ../../../open-settings/src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Responses
  syntax:
    content: public string Initials { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Initials As String
  overload: OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials*
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive
  commentId: P:OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive
  id: IsActive
  parent: OpenSettings.Models.Responses.GetOrCreateUserResponse
  langs:
  - csharp
  - vb
  name: IsActive
  nameWithType: GetOrCreateUserResponse.IsActive
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IsActive
    path: ../../../open-settings/src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
    startLine: 12
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Responses
  syntax:
    content: public bool IsActive { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsActive As Boolean
  overload: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive*
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated
  commentId: P:OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated
  id: IsNewlyCreated
  parent: OpenSettings.Models.Responses.GetOrCreateUserResponse
  langs:
  - csharp
  - vb
  name: IsNewlyCreated
  nameWithType: GetOrCreateUserResponse.IsNewlyCreated
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IsNewlyCreated
    path: ../../../open-settings/src/OpenSettings/Models/Responses/GetOrCreateUserResponse.cs
    startLine: 14
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Responses
  syntax:
    content: public bool IsNewlyCreated { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsNewlyCreated As Boolean
  overload: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated*
references:
- uid: OpenSettings.Models.Responses
  commentId: N:OpenSettings.Models.Responses
  href: OpenSettings.html
  name: OpenSettings.Models.Responses
  nameWithType: OpenSettings.Models.Responses
  fullName: OpenSettings.Models.Responses
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  - name: .
  - uid: OpenSettings.Models.Responses
    name: Responses
    href: OpenSettings.Models.Responses.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  - name: .
  - uid: OpenSettings.Models.Responses
    name: Responses
    href: OpenSettings.Models.Responses.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.Id*
  commentId: Overload:OpenSettings.Models.Responses.GetOrCreateUserResponse.Id
  href: OpenSettings.Models.Responses.GetOrCreateUserResponse.html#OpenSettings_Models_Responses_GetOrCreateUserResponse_Id
  name: Id
  nameWithType: GetOrCreateUserResponse.Id
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName*
  commentId: Overload:OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName
  href: OpenSettings.Models.Responses.GetOrCreateUserResponse.html#OpenSettings_Models_Responses_GetOrCreateUserResponse_DisplayName
  name: DisplayName
  nameWithType: GetOrCreateUserResponse.DisplayName
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.DisplayName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials*
  commentId: Overload:OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials
  href: OpenSettings.Models.Responses.GetOrCreateUserResponse.html#OpenSettings_Models_Responses_GetOrCreateUserResponse_Initials
  name: Initials
  nameWithType: GetOrCreateUserResponse.Initials
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.Initials
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive*
  commentId: Overload:OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive
  href: OpenSettings.Models.Responses.GetOrCreateUserResponse.html#OpenSettings_Models_Responses_GetOrCreateUserResponse_IsActive
  name: IsActive
  nameWithType: GetOrCreateUserResponse.IsActive
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsActive
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated*
  commentId: Overload:OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated
  href: OpenSettings.Models.Responses.GetOrCreateUserResponse.html#OpenSettings_Models_Responses_GetOrCreateUserResponse_IsNewlyCreated
  name: IsNewlyCreated
  nameWithType: GetOrCreateUserResponse.IsNewlyCreated
  fullName: OpenSettings.Models.Responses.GetOrCreateUserResponse.IsNewlyCreated
