### YamlMime:ManagedReference
items:
- uid: OpenSettings.Exceptions
  commentId: N:OpenSettings.Exceptions
  id: OpenSettings.Exceptions
  children:
  - OpenSettings.Exceptions.DuplicateSettingsNameException
  - OpenSettings.Exceptions.MissingConfigurationWhenSkipInitialSyncAppDataException
  - OpenSettings.Exceptions.SyncAppDataMaxRetryExceededException
  langs:
  - csharp
  - vb
  name: OpenSettings.Exceptions
  nameWithType: OpenSettings.Exceptions
  fullName: OpenSettings.Exceptions
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Exceptions.DuplicateSettingsNameException
  commentId: T:OpenSettings.Exceptions.DuplicateSettingsNameException
  href: OpenSettings.Exceptions.DuplicateSettingsNameException.html
  name: DuplicateSettingsNameException
  nameWithType: DuplicateSettingsNameException
  fullName: OpenSettings.Exceptions.DuplicateSettingsNameException
- uid: OpenSettings.Exceptions.MissingConfigurationWhenSkipInitialSyncAppDataException
  commentId: T:OpenSettings.Exceptions.MissingConfigurationWhenSkipInitialSyncAppDataException
  href: OpenSettings.Exceptions.MissingConfigurationWhenSkipInitialSyncAppDataException.html
  name: MissingConfigurationWhenSkipInitialSyncAppDataException
  nameWithType: MissingConfigurationWhenSkipInitialSyncAppDataException
  fullName: OpenSettings.Exceptions.MissingConfigurationWhenSkipInitialSyncAppDataException
- uid: OpenSettings.Exceptions.SyncAppDataMaxRetryExceededException
  commentId: T:OpenSettings.Exceptions.SyncAppDataMaxRetryExceededException
  href: OpenSettings.Exceptions.SyncAppDataMaxRetryExceededException.html
  name: SyncAppDataMaxRetryExceededException
  nameWithType: SyncAppDataMaxRetryExceededException
  fullName: OpenSettings.Exceptions.SyncAppDataMaxRetryExceededException
