### YamlMime:ManagedReference
items:
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1
  commentId: T:OpenSettings.Domains.Sql.Entities.EntityBase`1
  id: EntityBase`1
  parent: OpenSettings.Domains.Sql.Entities
  children:
  - OpenSettings.Domains.Sql.Entities.EntityBase`1.CreatedOn
  - OpenSettings.Domains.Sql.Entities.EntityBase`1.Id
  - OpenSettings.Domains.Sql.Entities.EntityBase`1.UpdatedOn
  langs:
  - csharp
  - vb
  name: EntityBase<TId>
  nameWithType: EntityBase<TId>
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>
  type: Class
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: EntityBase
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: A base entity class that provides common properties for all entities.
  example: []
  syntax:
    content: public abstract class EntityBase<TId>
    typeParameters:
    - id: TId
      description: The type of the entity's identifier.
    content.vb: Public MustInherit Class EntityBase(Of TId)
  inheritance:
  - System.Object
  derivedClasses:
  - OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
  - OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.AppSqlModel
  - OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.ConfigurationSqlModel
  - OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
  - OpenSettings.Domains.Sql.Entities.InstanceSqlModel
  - OpenSettings.Domains.Sql.Entities.LicenseSqlModel
  - OpenSettings.Domains.Sql.Entities.NotificationSqlModel
  - OpenSettings.Domains.Sql.Entities.ProviderRegistrySqlModel
  - OpenSettings.Domains.Sql.Entities.SettingClassSqlModel
  - OpenSettings.Domains.Sql.Entities.SettingHistorySqlModel
  - OpenSettings.Domains.Sql.Entities.SettingSqlModel
  - OpenSettings.Domains.Sql.Entities.TagSqlModel
  - OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupClaimMappingModel
  - OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
  - OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleClaimMappingModel
  - OpenSettings.Domains.Sql.Entities.UserRoleGroupMappingModel
  - OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
  - OpenSettings.Domains.Sql.Entities.UserSqlModel
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  nameWithType.vb: EntityBase(Of TId)
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId)
  name.vb: EntityBase(Of TId)
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1.Id
  commentId: P:OpenSettings.Domains.Sql.Entities.EntityBase`1.Id
  id: Id
  parent: OpenSettings.Domains.Sql.Entities.EntityBase`1
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: EntityBase<TId>.Id
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>.Id
  type: Property
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Id
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
    startLine: 13
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: The unique identifier for the entity.
  example: []
  syntax:
    content: public virtual TId Id { get; set; }
    parameters: []
    return:
      type: '{TId}'
    content.vb: Public Overridable Property Id As TId
  overload: OpenSettings.Domains.Sql.Entities.EntityBase`1.Id*
  nameWithType.vb: EntityBase(Of TId).Id
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId).Id
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1.CreatedOn
  commentId: P:OpenSettings.Domains.Sql.Entities.EntityBase`1.CreatedOn
  id: CreatedOn
  parent: OpenSettings.Domains.Sql.Entities.EntityBase`1
  langs:
  - csharp
  - vb
  name: CreatedOn
  nameWithType: EntityBase<TId>.CreatedOn
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>.CreatedOn
  type: Property
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: CreatedOn
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
    startLine: 18
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: The date and time when the entity was created.
  example: []
  syntax:
    content: public virtual DateTime CreatedOn { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: Public Overridable Property CreatedOn As Date
  overload: OpenSettings.Domains.Sql.Entities.EntityBase`1.CreatedOn*
  nameWithType.vb: EntityBase(Of TId).CreatedOn
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId).CreatedOn
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1.UpdatedOn
  commentId: P:OpenSettings.Domains.Sql.Entities.EntityBase`1.UpdatedOn
  id: UpdatedOn
  parent: OpenSettings.Domains.Sql.Entities.EntityBase`1
  langs:
  - csharp
  - vb
  name: UpdatedOn
  nameWithType: EntityBase<TId>.UpdatedOn
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>.UpdatedOn
  type: Property
  source:
    remote:
      path: src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: UpdatedOn
    path: ../../../open-settings/src/OpenSettings/Domains/Sql/Entities/EntityBase.cs
    startLine: 23
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Domains.Sql.Entities
  summary: The date and time when the entity was last updated, or <code>null</code> if never updated.
  example: []
  syntax:
    content: public virtual DateTime? UpdatedOn { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
    content.vb: Public Overridable Property UpdatedOn As Date?
  overload: OpenSettings.Domains.Sql.Entities.EntityBase`1.UpdatedOn*
  nameWithType.vb: EntityBase(Of TId).UpdatedOn
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId).UpdatedOn
references:
- uid: OpenSettings.Domains.Sql.Entities
  commentId: N:OpenSettings.Domains.Sql.Entities
  href: OpenSettings.html
  name: OpenSettings.Domains.Sql.Entities
  nameWithType: OpenSettings.Domains.Sql.Entities
  fullName: OpenSettings.Domains.Sql.Entities
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1.Id*
  commentId: Overload:OpenSettings.Domains.Sql.Entities.EntityBase`1.Id
  href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html#OpenSettings_Domains_Sql_Entities_EntityBase_1_Id
  name: Id
  nameWithType: EntityBase<TId>.Id
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>.Id
  nameWithType.vb: EntityBase(Of TId).Id
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId).Id
- uid: '{TId}'
  commentId: '!:TId'
  definition: TId
  name: TId
  nameWithType: TId
  fullName: TId
- uid: TId
  commentId: '!:TId'
  name: TId
  nameWithType: TId
  fullName: TId
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1.CreatedOn*
  commentId: Overload:OpenSettings.Domains.Sql.Entities.EntityBase`1.CreatedOn
  href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html#OpenSettings_Domains_Sql_Entities_EntityBase_1_CreatedOn
  name: CreatedOn
  nameWithType: EntityBase<TId>.CreatedOn
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>.CreatedOn
  nameWithType.vb: EntityBase(Of TId).CreatedOn
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId).CreatedOn
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.datetime
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
  nameWithType.vb: Date
  fullName.vb: Date
  name.vb: Date
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1.UpdatedOn*
  commentId: Overload:OpenSettings.Domains.Sql.Entities.EntityBase`1.UpdatedOn
  href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html#OpenSettings_Domains_Sql_Entities_EntityBase_1_UpdatedOn
  name: UpdatedOn
  nameWithType: EntityBase<TId>.UpdatedOn
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>.UpdatedOn
  nameWithType.vb: EntityBase(Of TId).UpdatedOn
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId).UpdatedOn
- uid: System.Nullable{System.DateTime}
  commentId: T:System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.datetime
  name: DateTime?
  nameWithType: DateTime?
  fullName: System.DateTime?
  nameWithType.vb: Date?
  fullName.vb: Date?
  name.vb: Date?
  spec.csharp:
  - uid: System.DateTime
    name: DateTime
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: '?'
  spec.vb:
  - uid: System.DateTime
    name: Date
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
