### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.MemoryCache.MemoryCacheKeys
  commentId: T:OpenSettings.Services.MemoryCache.MemoryCacheKeys
  id: MemoryCacheKeys
  parent: OpenSettings.Services.MemoryCache
  children:
  - OpenSettings.Services.MemoryCache.MemoryCacheKeys.GetAvailableNotificationIds
  - OpenSettings.Services.MemoryCache.MemoryCacheKeys.OpenSettingsSpaMiddlewareHtml
  langs:
  - csharp
  - vb
  name: MemoryCacheKeys
  nameWithType: MemoryCacheKeys
  fullName: OpenSettings.Services.MemoryCache.MemoryCacheKeys
  type: Class
  source:
    remote:
      path: src/OpenSettings/Services/MemoryCache/MemoryCacheKeys.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: MemoryCacheKeys
    path: ../../../open-settings/src/OpenSettings/Services/MemoryCache/MemoryCacheKeys.cs
    startLine: 9
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.MemoryCache
  summary: >-
    Provides predefined cache keys for various parts of the application. 

    These keys are used for caching specific data in the memory cache to improve performance.
  example: []
  syntax:
    content: public static class MemoryCacheKeys
    content.vb: Public Module MemoryCacheKeys
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.Services.MemoryCache.MemoryCacheKeys.GetAvailableNotificationIds
  commentId: F:OpenSettings.Services.MemoryCache.MemoryCacheKeys.GetAvailableNotificationIds
  id: GetAvailableNotificationIds
  parent: OpenSettings.Services.MemoryCache.MemoryCacheKeys
  langs:
  - csharp
  - vb
  name: GetAvailableNotificationIds
  nameWithType: MemoryCacheKeys.GetAvailableNotificationIds
  fullName: OpenSettings.Services.MemoryCache.MemoryCacheKeys.GetAvailableNotificationIds
  type: Field
  source:
    remote:
      path: src/OpenSettings/Services/MemoryCache/MemoryCacheKeys.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: GetAvailableNotificationIds
    path: ../../../open-settings/src/OpenSettings/Services/MemoryCache/MemoryCacheKeys.cs
    startLine: 14
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.MemoryCache
  summary: The cache key for available notification ids, with a 5-minute expiration time.
  example: []
  syntax:
    content: public static CacheModel GetAvailableNotificationIds
    return:
      type: OpenSettings.Models.CacheModel
    content.vb: Public Shared GetAvailableNotificationIds As CacheModel
- uid: OpenSettings.Services.MemoryCache.MemoryCacheKeys.OpenSettingsSpaMiddlewareHtml
  commentId: F:OpenSettings.Services.MemoryCache.MemoryCacheKeys.OpenSettingsSpaMiddlewareHtml
  id: OpenSettingsSpaMiddlewareHtml
  parent: OpenSettings.Services.MemoryCache.MemoryCacheKeys
  langs:
  - csharp
  - vb
  name: OpenSettingsSpaMiddlewareHtml
  nameWithType: MemoryCacheKeys.OpenSettingsSpaMiddlewareHtml
  fullName: OpenSettings.Services.MemoryCache.MemoryCacheKeys.OpenSettingsSpaMiddlewareHtml
  type: Field
  source:
    remote:
      path: src/OpenSettings/Services/MemoryCache/MemoryCacheKeys.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: OpenSettingsSpaMiddlewareHtml
    path: ../../../open-settings/src/OpenSettings/Services/MemoryCache/MemoryCacheKeys.cs
    startLine: 19
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.MemoryCache
  summary: The cache key for the OpenSettings Spa Middleware Html content.
  example: []
  syntax:
    content: public static CacheModel OpenSettingsSpaMiddlewareHtml
    return:
      type: OpenSettings.Models.CacheModel
    content.vb: Public Shared OpenSettingsSpaMiddlewareHtml As CacheModel
references:
- uid: OpenSettings.Services.MemoryCache
  commentId: N:OpenSettings.Services.MemoryCache
  href: OpenSettings.html
  name: OpenSettings.Services.MemoryCache
  nameWithType: OpenSettings.Services.MemoryCache
  fullName: OpenSettings.Services.MemoryCache
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.MemoryCache
    name: MemoryCache
    href: OpenSettings.Services.MemoryCache.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.MemoryCache
    name: MemoryCache
    href: OpenSettings.Services.MemoryCache.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Models.CacheModel
  commentId: T:OpenSettings.Models.CacheModel
  parent: OpenSettings.Models
  href: OpenSettings.Models.CacheModel.html
  name: CacheModel
  nameWithType: CacheModel
  fullName: OpenSettings.Models.CacheModel
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
