### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.NotificationType
  commentId: T:OpenSettings.Models.NotificationType
  id: NotificationType
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.NotificationType.Accent
  - OpenSettings.Models.NotificationType.Error
  - OpenSettings.Models.NotificationType.Info
  - OpenSettings.Models.NotificationType.LicenseExpiring
  - OpenSettings.Models.NotificationType.Neutral
  - OpenSettings.Models.NotificationType.NewVersionAvailable
  - OpenSettings.Models.NotificationType.Success
  - OpenSettings.Models.NotificationType.VersionMismatch
  - OpenSettings.Models.NotificationType.Warn
  langs:
  - csharp
  - vb
  name: NotificationType
  nameWithType: NotificationType
  fullName: OpenSettings.Models.NotificationType
  type: Enum
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: NotificationType
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public enum NotificationType
    content.vb: Public Enum NotificationType
- uid: OpenSettings.Models.NotificationType.Neutral
  commentId: F:OpenSettings.Models.NotificationType.Neutral
  id: Neutral
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: Neutral
  nameWithType: NotificationType.Neutral
  fullName: OpenSettings.Models.NotificationType.Neutral
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Neutral
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Neutral = 1
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.Info
  commentId: F:OpenSettings.Models.NotificationType.Info
  id: Info
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: Info
  nameWithType: NotificationType.Info
  fullName: OpenSettings.Models.NotificationType.Info
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Info
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Info = 2
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.Accent
  commentId: F:OpenSettings.Models.NotificationType.Accent
  id: Accent
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: Accent
  nameWithType: NotificationType.Accent
  fullName: OpenSettings.Models.NotificationType.Accent
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Accent
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Accent = 3
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.Success
  commentId: F:OpenSettings.Models.NotificationType.Success
  id: Success
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: Success
  nameWithType: NotificationType.Success
  fullName: OpenSettings.Models.NotificationType.Success
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Success
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Success = 4
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.Warn
  commentId: F:OpenSettings.Models.NotificationType.Warn
  id: Warn
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: Warn
  nameWithType: NotificationType.Warn
  fullName: OpenSettings.Models.NotificationType.Warn
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Warn
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 12
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Warn = 5
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.Error
  commentId: F:OpenSettings.Models.NotificationType.Error
  id: Error
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: NotificationType.Error
  fullName: OpenSettings.Models.NotificationType.Error
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Error
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 14
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Error = 6
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.NewVersionAvailable
  commentId: F:OpenSettings.Models.NotificationType.NewVersionAvailable
  id: NewVersionAvailable
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: NewVersionAvailable
  nameWithType: NotificationType.NewVersionAvailable
  fullName: OpenSettings.Models.NotificationType.NewVersionAvailable
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: NewVersionAvailable
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 16
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: NewVersionAvailable = 7
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.VersionMismatch
  commentId: F:OpenSettings.Models.NotificationType.VersionMismatch
  id: VersionMismatch
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: VersionMismatch
  nameWithType: NotificationType.VersionMismatch
  fullName: OpenSettings.Models.NotificationType.VersionMismatch
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: VersionMismatch
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 18
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: VersionMismatch = 8
    return:
      type: OpenSettings.Models.NotificationType
- uid: OpenSettings.Models.NotificationType.LicenseExpiring
  commentId: F:OpenSettings.Models.NotificationType.LicenseExpiring
  id: LicenseExpiring
  parent: OpenSettings.Models.NotificationType
  langs:
  - csharp
  - vb
  name: LicenseExpiring
  nameWithType: NotificationType.LicenseExpiring
  fullName: OpenSettings.Models.NotificationType.LicenseExpiring
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/NotificationType.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: LicenseExpiring
    path: ../../../open-settings/src/OpenSettings/Models/NotificationType.cs
    startLine: 20
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: LicenseExpiring = 9
    return:
      type: OpenSettings.Models.NotificationType
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: OpenSettings.Models.NotificationType
  commentId: T:OpenSettings.Models.NotificationType
  parent: OpenSettings.Models
  href: OpenSettings.Models.NotificationType.html
  name: NotificationType
  nameWithType: NotificationType
  fullName: OpenSettings.Models.NotificationType
