### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.OAuth2Options
  commentId: T:OpenSettings.AspNetCore.OAuth2Options
  id: OAuth2Options
  parent: OpenSettings.AspNetCore
  children:
  - OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess
  - OpenSettings.AspNetCore.OAuth2Options.Authority
  - OpenSettings.AspNetCore.OAuth2Options.ClientId
  - OpenSettings.AspNetCore.OAuth2Options.ClientSecret
  - OpenSettings.AspNetCore.OAuth2Options.IsActive
  - OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri
  langs:
  - csharp
  - vb
  name: OAuth2Options
  nameWithType: OAuth2Options
  fullName: OpenSettings.AspNetCore.OAuth2Options
  type: Class
  source:
    remote:
      path: src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: OAuth2Options
    path: ../../../open-settings/src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
    startLine: 8
  assemblies:
  - OpenSettings.AspNetCore.Spa
  namespace: OpenSettings.AspNetCore
  summary: >-
    Represents the configuration options for OAuth2 authentication.

    This class holds the necessary settings for connecting to an OAuth2 provider and handling authentication.
  example: []
  syntax:
    content: public class OAuth2Options
    content.vb: Public Class OAuth2Options
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.AspNetCore.OAuth2Options.Authority
  commentId: P:OpenSettings.AspNetCore.OAuth2Options.Authority
  id: Authority
  parent: OpenSettings.AspNetCore.OAuth2Options
  langs:
  - csharp
  - vb
  name: Authority
  nameWithType: OAuth2Options.Authority
  fullName: OpenSettings.AspNetCore.OAuth2Options.Authority
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Authority
    path: ../../../open-settings/src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
    startLine: 16
  assemblies:
  - OpenSettings.AspNetCore.Spa
  namespace: OpenSettings.AspNetCore
  summary: >-
    Gets or sets the authority URL for the OAuth2 provider.

    The value is trimmed of any trailing slashes.
  example: []
  syntax:
    content: public string Authority { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Authority As String
  overload: OpenSettings.AspNetCore.OAuth2Options.Authority*
- uid: OpenSettings.AspNetCore.OAuth2Options.ClientId
  commentId: P:OpenSettings.AspNetCore.OAuth2Options.ClientId
  id: ClientId
  parent: OpenSettings.AspNetCore.OAuth2Options
  langs:
  - csharp
  - vb
  name: ClientId
  nameWithType: OAuth2Options.ClientId
  fullName: OpenSettings.AspNetCore.OAuth2Options.ClientId
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: ClientId
    path: ../../../open-settings/src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
    startLine: 32
  assemblies:
  - OpenSettings.AspNetCore.Spa
  namespace: OpenSettings.AspNetCore
  summary: >-
    Gets or sets the client id used to authenticate with the OAuth2 provider.

    This property is ignored during JSON serialization.
  example: []
  syntax:
    content: >-
      [JsonIgnore]

      public string ClientId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonIgnore>

      Public Property ClientId As String
  overload: OpenSettings.AspNetCore.OAuth2Options.ClientId*
  attributes:
  - type: System.Text.Json.Serialization.JsonIgnoreAttribute
    ctor: System.Text.Json.Serialization.JsonIgnoreAttribute.#ctor
    arguments: []
- uid: OpenSettings.AspNetCore.OAuth2Options.ClientSecret
  commentId: P:OpenSettings.AspNetCore.OAuth2Options.ClientSecret
  id: ClientSecret
  parent: OpenSettings.AspNetCore.OAuth2Options
  langs:
  - csharp
  - vb
  name: ClientSecret
  nameWithType: OAuth2Options.ClientSecret
  fullName: OpenSettings.AspNetCore.OAuth2Options.ClientSecret
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: ClientSecret
    path: ../../../open-settings/src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
    startLine: 39
  assemblies:
  - OpenSettings.AspNetCore.Spa
  namespace: OpenSettings.AspNetCore
  summary: >-
    Gets or sets the client secret used to authenticate with the OAuth2 provider.

    This property is ignored during JSON serialization.
  example: []
  syntax:
    content: >-
      [JsonIgnore]

      public string ClientSecret { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonIgnore>

      Public Property ClientSecret As String
  overload: OpenSettings.AspNetCore.OAuth2Options.ClientSecret*
  attributes:
  - type: System.Text.Json.Serialization.JsonIgnoreAttribute
    ctor: System.Text.Json.Serialization.JsonIgnoreAttribute.#ctor
    arguments: []
- uid: OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri
  commentId: P:OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri
  id: SignedOutRedirectUri
  parent: OpenSettings.AspNetCore.OAuth2Options
  langs:
  - csharp
  - vb
  name: SignedOutRedirectUri
  nameWithType: OAuth2Options.SignedOutRedirectUri
  fullName: OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: SignedOutRedirectUri
    path: ../../../open-settings/src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
    startLine: 48
  assemblies:
  - OpenSettings.AspNetCore.Spa
  namespace: OpenSettings.AspNetCore
  summary: >-
    Gets or sets the URI to redirect to after the user is signed out.

    <p>The default value is '<code>settings</code>'.</p>
  example: []
  syntax:
    content: public string SignedOutRedirectUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SignedOutRedirectUri As String
  overload: OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri*
- uid: OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess
  commentId: P:OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess
  id: AllowOfflineAccess
  parent: OpenSettings.AspNetCore.OAuth2Options
  langs:
  - csharp
  - vb
  name: AllowOfflineAccess
  nameWithType: OAuth2Options.AllowOfflineAccess
  fullName: OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: AllowOfflineAccess
    path: ../../../open-settings/src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
    startLine: 69
  assemblies:
  - OpenSettings.AspNetCore.Spa
  namespace: OpenSettings.AspNetCore
  summary: >-
    Gets or sets a value indicating whether offline access is allowed.

    If set to true, offline access tokens can be obtained.
  example: []
  syntax:
    content: public bool AllowOfflineAccess { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property AllowOfflineAccess As Boolean
  overload: OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess*
- uid: OpenSettings.AspNetCore.OAuth2Options.IsActive
  commentId: P:OpenSettings.AspNetCore.OAuth2Options.IsActive
  id: IsActive
  parent: OpenSettings.AspNetCore.OAuth2Options
  langs:
  - csharp
  - vb
  name: IsActive
  nameWithType: OAuth2Options.IsActive
  fullName: OpenSettings.AspNetCore.OAuth2Options.IsActive
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IsActive
    path: ../../../open-settings/src/OpenSettings.AspNetCore.Spa/OAuth2Options.cs
    startLine: 75
  assemblies:
  - OpenSettings.AspNetCore.Spa
  namespace: OpenSettings.AspNetCore
  summary: >-
    Gets or sets a value indicating whether the OAuth2 configuration is active.

    If true, the OAuth2 authentication is enabled.
  example: []
  syntax:
    content: public bool IsActive { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsActive As Boolean
  overload: OpenSettings.AspNetCore.OAuth2Options.IsActive*
references:
- uid: OpenSettings.AspNetCore
  commentId: N:OpenSettings.AspNetCore
  href: OpenSettings.html
  name: OpenSettings.AspNetCore
  nameWithType: OpenSettings.AspNetCore
  fullName: OpenSettings.AspNetCore
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.AspNetCore.OAuth2Options.Authority*
  commentId: Overload:OpenSettings.AspNetCore.OAuth2Options.Authority
  href: OpenSettings.AspNetCore.OAuth2Options.html#OpenSettings_AspNetCore_OAuth2Options_Authority
  name: Authority
  nameWithType: OAuth2Options.Authority
  fullName: OpenSettings.AspNetCore.OAuth2Options.Authority
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenSettings.AspNetCore.OAuth2Options.ClientId*
  commentId: Overload:OpenSettings.AspNetCore.OAuth2Options.ClientId
  href: OpenSettings.AspNetCore.OAuth2Options.html#OpenSettings_AspNetCore_OAuth2Options_ClientId
  name: ClientId
  nameWithType: OAuth2Options.ClientId
  fullName: OpenSettings.AspNetCore.OAuth2Options.ClientId
- uid: OpenSettings.AspNetCore.OAuth2Options.ClientSecret*
  commentId: Overload:OpenSettings.AspNetCore.OAuth2Options.ClientSecret
  href: OpenSettings.AspNetCore.OAuth2Options.html#OpenSettings_AspNetCore_OAuth2Options_ClientSecret
  name: ClientSecret
  nameWithType: OAuth2Options.ClientSecret
  fullName: OpenSettings.AspNetCore.OAuth2Options.ClientSecret
- uid: OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri*
  commentId: Overload:OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri
  href: OpenSettings.AspNetCore.OAuth2Options.html#OpenSettings_AspNetCore_OAuth2Options_SignedOutRedirectUri
  name: SignedOutRedirectUri
  nameWithType: OAuth2Options.SignedOutRedirectUri
  fullName: OpenSettings.AspNetCore.OAuth2Options.SignedOutRedirectUri
- uid: OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess*
  commentId: Overload:OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess
  href: OpenSettings.AspNetCore.OAuth2Options.html#OpenSettings_AspNetCore_OAuth2Options_AllowOfflineAccess
  name: AllowOfflineAccess
  nameWithType: OAuth2Options.AllowOfflineAccess
  fullName: OpenSettings.AspNetCore.OAuth2Options.AllowOfflineAccess
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: OpenSettings.AspNetCore.OAuth2Options.IsActive*
  commentId: Overload:OpenSettings.AspNetCore.OAuth2Options.IsActive
  href: OpenSettings.AspNetCore.OAuth2Options.html#OpenSettings_AspNetCore_OAuth2Options_IsActive
  name: IsActive
  nameWithType: OAuth2Options.IsActive
  fullName: OpenSettings.AspNetCore.OAuth2Options.IsActive
