### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody
  commentId: T:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody
  id: UpdateIdentifierRequestBody
  parent: OpenSettings.AspNetCore.Models.Requests
  children:
  - OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name
  - OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion
  - OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition
  - OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder
  langs:
  - csharp
  - vb
  name: UpdateIdentifierRequestBody
  nameWithType: UpdateIdentifierRequestBody
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody
  type: Class
  source:
    remote:
      path: src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: UpdateIdentifierRequestBody
    path: ../../../open-settings/src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
    startLine: 5
  assemblies:
  - OpenSettings.AspNetCore
  namespace: OpenSettings.AspNetCore.Models.Requests
  syntax:
    content: public class UpdateIdentifierRequestBody
    content.vb: Public Class UpdateIdentifierRequestBody
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name
  commentId: P:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name
  id: Name
  parent: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: UpdateIdentifierRequestBody.Name
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Name
    path: ../../../open-settings/src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
    startLine: 7
  assemblies:
  - OpenSettings.AspNetCore
  namespace: OpenSettings.AspNetCore.Models.Requests
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name*
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder
  commentId: P:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder
  id: SortOrder
  parent: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody
  langs:
  - csharp
  - vb
  name: SortOrder
  nameWithType: UpdateIdentifierRequestBody.SortOrder
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: SortOrder
    path: ../../../open-settings/src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
    startLine: 9
  assemblies:
  - OpenSettings.AspNetCore
  namespace: OpenSettings.AspNetCore.Models.Requests
  syntax:
    content: public int SortOrder { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property SortOrder As Integer
  overload: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder*
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition
  commentId: P:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition
  id: SetSortOrderPosition
  parent: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody
  langs:
  - csharp
  - vb
  name: SetSortOrderPosition
  nameWithType: UpdateIdentifierRequestBody.SetSortOrderPosition
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: SetSortOrderPosition
    path: ../../../open-settings/src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
    startLine: 11
  assemblies:
  - OpenSettings.AspNetCore
  namespace: OpenSettings.AspNetCore.Models.Requests
  syntax:
    content: public SetSortOrderPosition? SetSortOrderPosition { get; set; }
    parameters: []
    return:
      type: System.Nullable{OpenSettings.Models.SetSortOrderPosition}
    content.vb: Public Property SetSortOrderPosition As SetSortOrderPosition?
  overload: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition*
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion
  commentId: P:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion
  id: RowVersion
  parent: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody
  langs:
  - csharp
  - vb
  name: RowVersion
  nameWithType: UpdateIdentifierRequestBody.RowVersion
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion
  type: Property
  source:
    remote:
      path: src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: RowVersion
    path: ../../../open-settings/src/OpenSettings.AspNetCore/Models/Requests/UpdateIdentifierRequestBody.cs
    startLine: 13
  assemblies:
  - OpenSettings.AspNetCore
  namespace: OpenSettings.AspNetCore.Models.Requests
  syntax:
    content: public byte[] RowVersion { get; set; }
    parameters: []
    return:
      type: System.Byte[]
    content.vb: Public Property RowVersion As Byte()
  overload: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion*
references:
- uid: OpenSettings.AspNetCore.Models.Requests
  commentId: N:OpenSettings.AspNetCore.Models.Requests
  href: OpenSettings.html
  name: OpenSettings.AspNetCore.Models.Requests
  nameWithType: OpenSettings.AspNetCore.Models.Requests
  fullName: OpenSettings.AspNetCore.Models.Requests
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models
    name: Models
    href: OpenSettings.AspNetCore.Models.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models.Requests
    name: Requests
    href: OpenSettings.AspNetCore.Models.Requests.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.AspNetCore
    name: AspNetCore
    href: OpenSettings.AspNetCore.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models
    name: Models
    href: OpenSettings.AspNetCore.Models.html
  - name: .
  - uid: OpenSettings.AspNetCore.Models.Requests
    name: Requests
    href: OpenSettings.AspNetCore.Models.Requests.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name*
  commentId: Overload:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name
  href: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.html#OpenSettings_AspNetCore_Models_Requests_UpdateIdentifierRequestBody_Name
  name: Name
  nameWithType: UpdateIdentifierRequestBody.Name
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder*
  commentId: Overload:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder
  href: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.html#OpenSettings_AspNetCore_Models_Requests_UpdateIdentifierRequestBody_SortOrder
  name: SortOrder
  nameWithType: UpdateIdentifierRequestBody.SortOrder
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SortOrder
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition*
  commentId: Overload:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition
  href: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.html#OpenSettings_AspNetCore_Models_Requests_UpdateIdentifierRequestBody_SetSortOrderPosition
  name: SetSortOrderPosition
  nameWithType: UpdateIdentifierRequestBody.SetSortOrderPosition
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.SetSortOrderPosition
- uid: System.Nullable{OpenSettings.Models.SetSortOrderPosition}
  commentId: T:System.Nullable{OpenSettings.Models.SetSortOrderPosition}
  parent: System
  definition: System.Nullable`1
  href: OpenSettings.Models.SetSortOrderPosition.html
  name: SetSortOrderPosition?
  nameWithType: SetSortOrderPosition?
  fullName: OpenSettings.Models.SetSortOrderPosition?
  spec.csharp:
  - uid: OpenSettings.Models.SetSortOrderPosition
    name: SetSortOrderPosition
    href: OpenSettings.Models.SetSortOrderPosition.html
  - name: '?'
  spec.vb:
  - uid: OpenSettings.Models.SetSortOrderPosition
    name: SetSortOrderPosition
    href: OpenSettings.Models.SetSortOrderPosition.html
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion*
  commentId: Overload:OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion
  href: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.html#OpenSettings_AspNetCore_Models_Requests_UpdateIdentifierRequestBody_RowVersion
  name: RowVersion
  nameWithType: UpdateIdentifierRequestBody.RowVersion
  fullName: OpenSettings.AspNetCore.Models.Requests.UpdateIdentifierRequestBody.RowVersion
- uid: System.Byte[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte[]
  nameWithType: byte[]
  fullName: byte[]
  nameWithType.vb: Byte()
  fullName.vb: Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
