### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput
  commentId: T:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput
  id: UpdateLocalDataAndWriteToDiskInput
  parent: OpenSettings.Models.Inputs
  children:
  - OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
  - OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data
  - OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
  - OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
  langs:
  - csharp
  - vb
  name: UpdateLocalDataAndWriteToDiskInput
  nameWithType: UpdateLocalDataAndWriteToDiskInput
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput
  type: Class
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: UpdateLocalDataAndWriteToDiskInput
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public class UpdateLocalDataAndWriteToDiskInput
    content.vb: Public Class UpdateLocalDataAndWriteToDiskInput
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
  commentId: P:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
  id: ComputedIdentifier
  parent: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput
  langs:
  - csharp
  - vb
  name: ComputedIdentifier
  nameWithType: UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: ComputedIdentifier
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public Guid ComputedIdentifier { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property ComputedIdentifier As Guid
  overload: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier*
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data
  commentId: P:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data
  id: Data
  parent: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: UpdateLocalDataAndWriteToDiskInput.Data
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Data
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public string Data { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Data As String
  overload: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data*
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
  commentId: P:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
  id: StoreInSeparateFile
  parent: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput
  langs:
  - csharp
  - vb
  name: StoreInSeparateFile
  nameWithType: UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: StoreInSeparateFile
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public bool StoreInSeparateFile { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property StoreInSeparateFile As Boolean
  overload: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile*
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
  commentId: P:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
  id: IgnoreOnFileChange
  parent: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput
  langs:
  - csharp
  - vb
  name: IgnoreOnFileChange
  nameWithType: UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IgnoreOnFileChange
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/UpdateLocalDataAndWriteToDiskInput.cs
    startLine: 12
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public bool IgnoreOnFileChange { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IgnoreOnFileChange As Boolean
  overload: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange*
references:
- uid: OpenSettings.Models.Inputs
  commentId: N:OpenSettings.Models.Inputs
  href: OpenSettings.html
  name: OpenSettings.Models.Inputs
  nameWithType: OpenSettings.Models.Inputs
  fullName: OpenSettings.Models.Inputs
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  - name: .
  - uid: OpenSettings.Models.Inputs
    name: Inputs
    href: OpenSettings.Models.Inputs.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  - name: .
  - uid: OpenSettings.Models.Inputs
    name: Inputs
    href: OpenSettings.Models.Inputs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier*
  commentId: Overload:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
  href: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.html#OpenSettings_Models_Inputs_UpdateLocalDataAndWriteToDiskInput_ComputedIdentifier
  name: ComputedIdentifier
  nameWithType: UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.ComputedIdentifier
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data*
  commentId: Overload:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data
  href: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.html#OpenSettings_Models_Inputs_UpdateLocalDataAndWriteToDiskInput_Data
  name: Data
  nameWithType: UpdateLocalDataAndWriteToDiskInput.Data
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.Data
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile*
  commentId: Overload:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
  href: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.html#OpenSettings_Models_Inputs_UpdateLocalDataAndWriteToDiskInput_StoreInSeparateFile
  name: StoreInSeparateFile
  nameWithType: UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.StoreInSeparateFile
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange*
  commentId: Overload:OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
  href: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.html#OpenSettings_Models_Inputs_UpdateLocalDataAndWriteToDiskInput_IgnoreOnFileChange
  name: IgnoreOnFileChange
  nameWithType: UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
  fullName: OpenSettings.Models.Inputs.UpdateLocalDataAndWriteToDiskInput.IgnoreOnFileChange
