### YamlMime:ManagedReference
items:
- uid: OpenSettings.Configurations.RedisConfiguration
  commentId: T:OpenSettings.Configurations.RedisConfiguration
  id: RedisConfiguration
  parent: OpenSettings.Configurations
  children:
  - OpenSettings.Configurations.RedisConfiguration.Channel
  - OpenSettings.Configurations.RedisConfiguration.Configuration
  - OpenSettings.Configurations.RedisConfiguration.IsActive
  langs:
  - csharp
  - vb
  name: RedisConfiguration
  nameWithType: RedisConfiguration
  fullName: OpenSettings.Configurations.RedisConfiguration
  type: Class
  source:
    remote:
      path: src/OpenSettings/Configurations/RedisConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: RedisConfiguration
    path: ../../../open-settings/src/OpenSettings/Configurations/RedisConfiguration.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Represents the configuration for Redis. 

    These settings determine whether Redis is active, how to connect to Redis, and how to interact with Redis channels.
  example: []
  syntax:
    content: public class RedisConfiguration
    content.vb: Public Class RedisConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.Configurations.RedisConfiguration.IsActive
  commentId: P:OpenSettings.Configurations.RedisConfiguration.IsActive
  id: IsActive
  parent: OpenSettings.Configurations.RedisConfiguration
  langs:
  - csharp
  - vb
  name: IsActive
  nameWithType: RedisConfiguration.IsActive
  fullName: OpenSettings.Configurations.RedisConfiguration.IsActive
  type: Property
  source:
    remote:
      path: src/OpenSettings/Configurations/RedisConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IsActive
    path: ../../../open-settings/src/OpenSettings/Configurations/RedisConfiguration.cs
    startLine: 17
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Gets or sets a value indicating whether Redis is active.

    When <code>true</code>, Redis is enabled and used for communication.
  example: []
  syntax:
    content: public bool IsActive { get; set; }
    parameters: []
    return:
      type: System.Boolean
      description: A <xref href="System.Boolean" data-throw-if-not-resolved="false"></xref> indicating if Redis is active. Default is <code>false</code>.
    content.vb: Public Property IsActive As Boolean
  overload: OpenSettings.Configurations.RedisConfiguration.IsActive*
- uid: OpenSettings.Configurations.RedisConfiguration.Configuration
  commentId: P:OpenSettings.Configurations.RedisConfiguration.Configuration
  id: Configuration
  parent: OpenSettings.Configurations.RedisConfiguration
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: RedisConfiguration.Configuration
  fullName: OpenSettings.Configurations.RedisConfiguration.Configuration
  type: Property
  source:
    remote:
      path: src/OpenSettings/Configurations/RedisConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Configuration
    path: ../../../open-settings/src/OpenSettings/Configurations/RedisConfiguration.cs
    startLine: 33
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Gets or sets the configuration string for Redis. 

    This property is used to parse the configuration string for Redis connections, 

    typically via <xref href="StackExchange.Redis.ConfigurationOptions.Parse(System.String)" data-throw-if-not-resolved="false"></xref> in the Redis StackExchange library.
  example: []
  syntax:
    content: public string Configuration { get; set; }
    parameters: []
    return:
      type: System.String
      description: >-
        A <xref href="System.String" data-throw-if-not-resolved="false"></xref> representing the configuration for Redis, which is parsed using 

        <xref href="StackExchange.Redis.ConfigurationOptions.Parse(System.String)" data-throw-if-not-resolved="false"></xref> to establish Redis connection settings.
    content.vb: Public Property Configuration As String
  overload: OpenSettings.Configurations.RedisConfiguration.Configuration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: Thrown when <code class="paramref">value</code> is null or whitespace while <xref href="OpenSettings.Configurations.RedisConfiguration.IsActive" data-throw-if-not-resolved="false"></xref> is <code>true</code>.
- uid: OpenSettings.Configurations.RedisConfiguration.Channel
  commentId: P:OpenSettings.Configurations.RedisConfiguration.Channel
  id: Channel
  parent: OpenSettings.Configurations.RedisConfiguration
  langs:
  - csharp
  - vb
  name: Channel
  nameWithType: RedisConfiguration.Channel
  fullName: OpenSettings.Configurations.RedisConfiguration.Channel
  type: Property
  source:
    remote:
      path: src/OpenSettings/Configurations/RedisConfiguration.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Channel
    path: ../../../open-settings/src/OpenSettings/Configurations/RedisConfiguration.cs
    startLine: 56
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Configurations
  summary: >-
    Gets or sets the Redis channel used for communication. 

    This channel is used to send or receive messages related to settings.
  example: []
  syntax:
    content: public string Channel { get; set; }
    parameters: []
    return:
      type: System.String
      description: A <xref href="System.String" data-throw-if-not-resolved="false"></xref> representing the Redis channel name. The default value is "Settings".
    content.vb: Public Property Channel As String
  overload: OpenSettings.Configurations.RedisConfiguration.Channel*
references:
- uid: OpenSettings.Configurations
  commentId: N:OpenSettings.Configurations
  href: OpenSettings.html
  name: OpenSettings.Configurations
  nameWithType: OpenSettings.Configurations
  fullName: OpenSettings.Configurations
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Configurations
    name: Configurations
    href: OpenSettings.Configurations.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Configurations
    name: Configurations
    href: OpenSettings.Configurations.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: OpenSettings.Configurations.RedisConfiguration.IsActive*
  commentId: Overload:OpenSettings.Configurations.RedisConfiguration.IsActive
  href: OpenSettings.Configurations.RedisConfiguration.html#OpenSettings_Configurations_RedisConfiguration_IsActive
  name: IsActive
  nameWithType: RedisConfiguration.IsActive
  fullName: OpenSettings.Configurations.RedisConfiguration.IsActive
- uid: StackExchange.Redis.ConfigurationOptions.Parse(System.String)
  commentId: M:StackExchange.Redis.ConfigurationOptions.Parse(System.String)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: Parse(string)
  nameWithType: ConfigurationOptions.Parse(string)
  fullName: StackExchange.Redis.ConfigurationOptions.Parse(string)
  nameWithType.vb: ConfigurationOptions.Parse(String)
  fullName.vb: StackExchange.Redis.ConfigurationOptions.Parse(String)
  name.vb: Parse(String)
  spec.csharp:
  - uid: StackExchange.Redis.ConfigurationOptions.Parse(System.String)
    name: Parse
    isExternal: true
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: StackExchange.Redis.ConfigurationOptions.Parse(System.String)
    name: Parse
    isExternal: true
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenSettings.Configurations.RedisConfiguration.IsActive
  commentId: P:OpenSettings.Configurations.RedisConfiguration.IsActive
  href: OpenSettings.Configurations.RedisConfiguration.html#OpenSettings_Configurations_RedisConfiguration_IsActive
  name: IsActive
  nameWithType: RedisConfiguration.IsActive
  fullName: OpenSettings.Configurations.RedisConfiguration.IsActive
- uid: System.ArgumentNullException
  commentId: T:System.ArgumentNullException
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.argumentnullexception
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: OpenSettings.Configurations.RedisConfiguration.Configuration*
  commentId: Overload:OpenSettings.Configurations.RedisConfiguration.Configuration
  href: OpenSettings.Configurations.RedisConfiguration.html#OpenSettings_Configurations_RedisConfiguration_Configuration
  name: Configuration
  nameWithType: RedisConfiguration.Configuration
  fullName: OpenSettings.Configurations.RedisConfiguration.Configuration
- uid: OpenSettings.Configurations.RedisConfiguration.Channel*
  commentId: Overload:OpenSettings.Configurations.RedisConfiguration.Channel
  href: OpenSettings.Configurations.RedisConfiguration.html#OpenSettings_Configurations_RedisConfiguration_Channel
  name: Channel
  nameWithType: RedisConfiguration.Channel
  fullName: OpenSettings.Configurations.RedisConfiguration.Channel
