### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.SortDirection
  commentId: T:OpenSettings.Models.SortDirection
  id: SortDirection
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.SortDirection.Asc
  - OpenSettings.Models.SortDirection.Desc
  langs:
  - csharp
  - vb
  name: SortDirection
  nameWithType: SortDirection
  fullName: OpenSettings.Models.SortDirection
  type: Enum
  source:
    remote:
      path: src/OpenSettings/Models/SortDirection.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: SortDirection
    path: ../../../open-settings/src/OpenSettings/Models/SortDirection.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public enum SortDirection
    content.vb: Public Enum SortDirection
- uid: OpenSettings.Models.SortDirection.Asc
  commentId: F:OpenSettings.Models.SortDirection.Asc
  id: Asc
  parent: OpenSettings.Models.SortDirection
  langs:
  - csharp
  - vb
  name: Asc
  nameWithType: SortDirection.Asc
  fullName: OpenSettings.Models.SortDirection.Asc
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/SortDirection.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Asc
    path: ../../../open-settings/src/OpenSettings/Models/SortDirection.cs
    startLine: 7
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  summary: Indicates ascending order for sorting.
  example: []
  syntax:
    content: Asc = 1
    return:
      type: OpenSettings.Models.SortDirection
- uid: OpenSettings.Models.SortDirection.Desc
  commentId: F:OpenSettings.Models.SortDirection.Desc
  id: Desc
  parent: OpenSettings.Models.SortDirection
  langs:
  - csharp
  - vb
  name: Desc
  nameWithType: SortDirection.Desc
  fullName: OpenSettings.Models.SortDirection.Desc
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/SortDirection.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Desc
    path: ../../../open-settings/src/OpenSettings/Models/SortDirection.cs
    startLine: 12
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  summary: Indicates descending order for sorting.
  example: []
  syntax:
    content: Desc = 2
    return:
      type: OpenSettings.Models.SortDirection
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: OpenSettings.Models.SortDirection
  commentId: T:OpenSettings.Models.SortDirection
  parent: OpenSettings.Models
  href: OpenSettings.Models.SortDirection.html
  name: SortDirection
  nameWithType: SortDirection
  fullName: OpenSettings.Models.SortDirection
