### YamlMime:ManagedReference
items:
- uid: OpenSettings.Domains.Sql.DataContext
  commentId: N:OpenSettings.Domains.Sql.DataContext
  id: OpenSettings.Domains.Sql.DataContext
  children:
  - OpenSettings.Domains.Sql.DataContext.OpenSettingsDbContext
  langs:
  - csharp
  - vb
  name: OpenSettings.Domains.Sql.DataContext
  nameWithType: OpenSettings.Domains.Sql.DataContext
  fullName: OpenSettings.Domains.Sql.DataContext
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Domains.Sql.DataContext.OpenSettingsDbContext
  commentId: T:OpenSettings.Domains.Sql.DataContext.OpenSettingsDbContext
  parent: OpenSettings.Domains.Sql.DataContext
  href: OpenSettings.Domains.Sql.DataContext.OpenSettingsDbContext.html
  name: OpenSettingsDbContext
  nameWithType: OpenSettingsDbContext
  fullName: OpenSettings.Domains.Sql.DataContext.OpenSettingsDbContext
- uid: OpenSettings.Domains.Sql.DataContext
  commentId: N:OpenSettings.Domains.Sql.DataContext
  href: OpenSettings.html
  name: OpenSettings.Domains.Sql.DataContext
  nameWithType: OpenSettings.Domains.Sql.DataContext
  fullName: OpenSettings.Domains.Sql.DataContext
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.DataContext
    name: DataContext
    href: OpenSettings.Domains.Sql.DataContext.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.DataContext
    name: DataContext
    href: OpenSettings.Domains.Sql.DataContext.html
