### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Interfaces.IUserNotificationMappingService
  commentId: T:OpenSettings.Services.Interfaces.IUserNotificationMappingService
  id: IUserNotificationMappingService
  parent: OpenSettings.Services.Interfaces
  children: []
  langs:
  - csharp
  - vb
  name: IUserNotificationMappingService
  nameWithType: IUserNotificationMappingService
  fullName: OpenSettings.Services.Interfaces.IUserNotificationMappingService
  type: Interface
  source:
    remote:
      path: src/OpenSettings/Services/Interfaces/IUserNotificationMappingService.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: IUserNotificationMappingService
    path: ../../../open-settings/src/OpenSettings/Services/Interfaces/IUserNotificationMappingService.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Services.Interfaces
  syntax:
    content: public interface IUserNotificationMappingService
    content.vb: Public Interface IUserNotificationMappingService
references:
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
