### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Rest
  commentId: N:OpenSettings.Services.Rest
  id: OpenSettings.Services.Rest
  children:
  - OpenSettings.Services.Rest.AppGroupRestService
  - OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  - OpenSettings.Services.Rest.AppRestService
  - OpenSettings.Services.Rest.AppTagMappingRestService
  - OpenSettings.Services.Rest.ConfigurationRestService
  - OpenSettings.Services.Rest.IdentifierRestService
  - OpenSettings.Services.Rest.InstanceRestService
  - OpenSettings.Services.Rest.LicenseRestService
  - OpenSettings.Services.Rest.NotificationRestService
  - OpenSettings.Services.Rest.OpenSettingsRestService
  - OpenSettings.Services.Rest.ProviderRestService
  - OpenSettings.Services.Rest.QueryBuilder
  - OpenSettings.Services.Rest.SettingClassRestService
  - OpenSettings.Services.Rest.SettingHistoryRestService
  - OpenSettings.Services.Rest.SettingsRestService
  - OpenSettings.Services.Rest.TagRestService
  - OpenSettings.Services.Rest.UsersRestService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Rest
  nameWithType: OpenSettings.Services.Rest
  fullName: OpenSettings.Services.Rest
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Rest.AppGroupRestService
  commentId: T:OpenSettings.Services.Rest.AppGroupRestService
  href: OpenSettings.Services.Rest.AppGroupRestService.html
  name: AppGroupRestService
  nameWithType: AppGroupRestService
  fullName: OpenSettings.Services.Rest.AppGroupRestService
- uid: OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  commentId: T:OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  href: OpenSettings.Services.Rest.AppIdentifierMappingsRestService.html
  name: AppIdentifierMappingsRestService
  nameWithType: AppIdentifierMappingsRestService
  fullName: OpenSettings.Services.Rest.AppIdentifierMappingsRestService
- uid: OpenSettings.Services.Rest.AppRestService
  commentId: T:OpenSettings.Services.Rest.AppRestService
  href: OpenSettings.Services.Rest.AppRestService.html
  name: AppRestService
  nameWithType: AppRestService
  fullName: OpenSettings.Services.Rest.AppRestService
- uid: OpenSettings.Services.Rest.AppTagMappingRestService
  commentId: T:OpenSettings.Services.Rest.AppTagMappingRestService
  href: OpenSettings.Services.Rest.AppTagMappingRestService.html
  name: AppTagMappingRestService
  nameWithType: AppTagMappingRestService
  fullName: OpenSettings.Services.Rest.AppTagMappingRestService
- uid: OpenSettings.Services.Rest.ConfigurationRestService
  commentId: T:OpenSettings.Services.Rest.ConfigurationRestService
  href: OpenSettings.Services.Rest.ConfigurationRestService.html
  name: ConfigurationRestService
  nameWithType: ConfigurationRestService
  fullName: OpenSettings.Services.Rest.ConfigurationRestService
- uid: OpenSettings.Services.Rest.IdentifierRestService
  commentId: T:OpenSettings.Services.Rest.IdentifierRestService
  href: OpenSettings.Services.Rest.IdentifierRestService.html
  name: IdentifierRestService
  nameWithType: IdentifierRestService
  fullName: OpenSettings.Services.Rest.IdentifierRestService
- uid: OpenSettings.Services.Rest.InstanceRestService
  commentId: T:OpenSettings.Services.Rest.InstanceRestService
  href: OpenSettings.Services.Rest.InstanceRestService.html
  name: InstanceRestService
  nameWithType: InstanceRestService
  fullName: OpenSettings.Services.Rest.InstanceRestService
- uid: OpenSettings.Services.Rest.LicenseRestService
  commentId: T:OpenSettings.Services.Rest.LicenseRestService
  href: OpenSettings.Services.Rest.LicenseRestService.html
  name: LicenseRestService
  nameWithType: LicenseRestService
  fullName: OpenSettings.Services.Rest.LicenseRestService
- uid: OpenSettings.Services.Rest.NotificationRestService
  commentId: T:OpenSettings.Services.Rest.NotificationRestService
  href: OpenSettings.Services.Rest.NotificationRestService.html
  name: NotificationRestService
  nameWithType: NotificationRestService
  fullName: OpenSettings.Services.Rest.NotificationRestService
- uid: OpenSettings.Services.Rest.OpenSettingsRestService
  commentId: T:OpenSettings.Services.Rest.OpenSettingsRestService
  href: OpenSettings.Services.Rest.OpenSettingsRestService.html
  name: OpenSettingsRestService
  nameWithType: OpenSettingsRestService
  fullName: OpenSettings.Services.Rest.OpenSettingsRestService
- uid: OpenSettings.Services.Rest.ProviderRestService
  commentId: T:OpenSettings.Services.Rest.ProviderRestService
  href: OpenSettings.Services.Rest.ProviderRestService.html
  name: ProviderRestService
  nameWithType: ProviderRestService
  fullName: OpenSettings.Services.Rest.ProviderRestService
- uid: OpenSettings.Services.Rest.QueryBuilder
  commentId: T:OpenSettings.Services.Rest.QueryBuilder
  parent: OpenSettings.Services.Rest
  href: OpenSettings.Services.Rest.QueryBuilder.html
  name: QueryBuilder
  nameWithType: QueryBuilder
  fullName: OpenSettings.Services.Rest.QueryBuilder
- uid: OpenSettings.Services.Rest.SettingClassRestService
  commentId: T:OpenSettings.Services.Rest.SettingClassRestService
  href: OpenSettings.Services.Rest.SettingClassRestService.html
  name: SettingClassRestService
  nameWithType: SettingClassRestService
  fullName: OpenSettings.Services.Rest.SettingClassRestService
- uid: OpenSettings.Services.Rest.SettingHistoryRestService
  commentId: T:OpenSettings.Services.Rest.SettingHistoryRestService
  href: OpenSettings.Services.Rest.SettingHistoryRestService.html
  name: SettingHistoryRestService
  nameWithType: SettingHistoryRestService
  fullName: OpenSettings.Services.Rest.SettingHistoryRestService
- uid: OpenSettings.Services.Rest.SettingsRestService
  commentId: T:OpenSettings.Services.Rest.SettingsRestService
  href: OpenSettings.Services.Rest.SettingsRestService.html
  name: SettingsRestService
  nameWithType: SettingsRestService
  fullName: OpenSettings.Services.Rest.SettingsRestService
- uid: OpenSettings.Services.Rest.TagRestService
  commentId: T:OpenSettings.Services.Rest.TagRestService
  href: OpenSettings.Services.Rest.TagRestService.html
  name: TagRestService
  nameWithType: TagRestService
  fullName: OpenSettings.Services.Rest.TagRestService
- uid: OpenSettings.Services.Rest.UsersRestService
  commentId: T:OpenSettings.Services.Rest.UsersRestService
  href: OpenSettings.Services.Rest.UsersRestService.html
  name: UsersRestService
  nameWithType: UsersRestService
  fullName: OpenSettings.Services.Rest.UsersRestService
- uid: OpenSettings.Services.Rest
  commentId: N:OpenSettings.Services.Rest
  href: OpenSettings.html
  name: OpenSettings.Services.Rest
  nameWithType: OpenSettings.Services.Rest
  fullName: OpenSettings.Services.Rest
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
