### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.AuthMethod
  commentId: T:OpenSettings.Models.AuthMethod
  id: AuthMethod
  parent: OpenSettings.Models
  children:
  - OpenSettings.Models.AuthMethod.Basic
  - OpenSettings.Models.AuthMethod.Cookie
  - OpenSettings.Models.AuthMethod.Jwt
  - OpenSettings.Models.AuthMethod.Unset
  langs:
  - csharp
  - vb
  name: AuthMethod
  nameWithType: AuthMethod
  fullName: OpenSettings.Models.AuthMethod
  type: Enum
  source:
    remote:
      path: src/OpenSettings/Models/AuthMethod.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: AuthMethod
    path: ../../../open-settings/src/OpenSettings/Models/AuthMethod.cs
    startLine: 2
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: public enum AuthMethod
    content.vb: Public Enum AuthMethod
- uid: OpenSettings.Models.AuthMethod.Unset
  commentId: F:OpenSettings.Models.AuthMethod.Unset
  id: Unset
  parent: OpenSettings.Models.AuthMethod
  langs:
  - csharp
  - vb
  name: Unset
  nameWithType: AuthMethod.Unset
  fullName: OpenSettings.Models.AuthMethod.Unset
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AuthMethod.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Unset
    path: ../../../open-settings/src/OpenSettings/Models/AuthMethod.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Unset = 0
    return:
      type: OpenSettings.Models.AuthMethod
- uid: OpenSettings.Models.AuthMethod.Basic
  commentId: F:OpenSettings.Models.AuthMethod.Basic
  id: Basic
  parent: OpenSettings.Models.AuthMethod
  langs:
  - csharp
  - vb
  name: Basic
  nameWithType: AuthMethod.Basic
  fullName: OpenSettings.Models.AuthMethod.Basic
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AuthMethod.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Basic
    path: ../../../open-settings/src/OpenSettings/Models/AuthMethod.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Basic = 1
    return:
      type: OpenSettings.Models.AuthMethod
- uid: OpenSettings.Models.AuthMethod.Jwt
  commentId: F:OpenSettings.Models.AuthMethod.Jwt
  id: Jwt
  parent: OpenSettings.Models.AuthMethod
  langs:
  - csharp
  - vb
  name: Jwt
  nameWithType: AuthMethod.Jwt
  fullName: OpenSettings.Models.AuthMethod.Jwt
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AuthMethod.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Jwt
    path: ../../../open-settings/src/OpenSettings/Models/AuthMethod.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Jwt = 2
    return:
      type: OpenSettings.Models.AuthMethod
- uid: OpenSettings.Models.AuthMethod.Cookie
  commentId: F:OpenSettings.Models.AuthMethod.Cookie
  id: Cookie
  parent: OpenSettings.Models.AuthMethod
  langs:
  - csharp
  - vb
  name: Cookie
  nameWithType: AuthMethod.Cookie
  fullName: OpenSettings.Models.AuthMethod.Cookie
  type: Field
  source:
    remote:
      path: src/OpenSettings/Models/AuthMethod.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: Cookie
    path: ../../../open-settings/src/OpenSettings/Models/AuthMethod.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models
  syntax:
    content: Cookie = 3
    return:
      type: OpenSettings.Models.AuthMethod
references:
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
- uid: OpenSettings.Models.AuthMethod
  commentId: T:OpenSettings.Models.AuthMethod
  parent: OpenSettings.Models
  href: OpenSettings.Models.AuthMethod.html
  name: AuthMethod
  nameWithType: AuthMethod
  fullName: OpenSettings.Models.AuthMethod
