### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Rest.Interfaces
  commentId: N:OpenSettings.Services.Rest.Interfaces
  id: OpenSettings.Services.Rest.Interfaces
  children:
  - OpenSettings.Services.Rest.Interfaces.IAppConfigurationRestService
  - OpenSettings.Services.Rest.Interfaces.IAppGroupRestService
  - OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingRestService
  - OpenSettings.Services.Rest.Interfaces.IAppRestService
  - OpenSettings.Services.Rest.Interfaces.IAppSettingRestService
  - OpenSettings.Services.Rest.Interfaces.IAppTagMappingRestService
  - OpenSettings.Services.Rest.Interfaces.IAppTagRestService
  - OpenSettings.Services.Rest.Interfaces.IAuthRestService
  - OpenSettings.Services.Rest.Interfaces.IIdentifierRestService
  - OpenSettings.Services.Rest.Interfaces.IInstanceRestService
  - OpenSettings.Services.Rest.Interfaces.ILicenseRestService
  - OpenSettings.Services.Rest.Interfaces.INotificationRestService
  - OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
  - OpenSettings.Services.Rest.Interfaces.IProviderRestService
  - OpenSettings.Services.Rest.Interfaces.ISettingClassRestService
  - OpenSettings.Services.Rest.Interfaces.ISettingHistoryRestService
  - OpenSettings.Services.Rest.Interfaces.IUserRestService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Rest.Interfaces
  nameWithType: OpenSettings.Services.Rest.Interfaces
  fullName: OpenSettings.Services.Rest.Interfaces
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Rest.Interfaces.IAppGroupRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppGroupRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppGroupRestService.html
  name: IAppGroupRestService
  nameWithType: IAppGroupRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppGroupRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingRestService.html
  name: IAppIdentifierMappingRestService
  nameWithType: IAppIdentifierMappingRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppIdentifierMappingRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppRestService.html
  name: IAppRestService
  nameWithType: IAppRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppTagMappingRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppTagMappingRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppTagMappingRestService.html
  name: IAppTagMappingRestService
  nameWithType: IAppTagMappingRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppTagMappingRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAuthRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAuthRestService
  href: OpenSettings.Services.Rest.Interfaces.IAuthRestService.html
  name: IAuthRestService
  nameWithType: IAuthRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAuthRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppConfigurationRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppConfigurationRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppConfigurationRestService.html
  name: IAppConfigurationRestService
  nameWithType: IAppConfigurationRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppConfigurationRestService
- uid: OpenSettings.Services.Rest.Interfaces.IIdentifierRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IIdentifierRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IIdentifierRestService.html
  name: IIdentifierRestService
  nameWithType: IIdentifierRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IIdentifierRestService
- uid: OpenSettings.Services.Rest.Interfaces.IInstanceRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IInstanceRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IInstanceRestService.html
  name: IInstanceRestService
  nameWithType: IInstanceRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IInstanceRestService
- uid: OpenSettings.Services.Rest.Interfaces.ILicenseRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ILicenseRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ILicenseRestService.html
  name: ILicenseRestService
  nameWithType: ILicenseRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ILicenseRestService
- uid: OpenSettings.Services.Rest.Interfaces.INotificationRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.INotificationRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.INotificationRestService.html
  name: INotificationRestService
  nameWithType: INotificationRestService
  fullName: OpenSettings.Services.Rest.Interfaces.INotificationRestService
- uid: OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService.html
  name: IOpenSettingsRestService
  nameWithType: IOpenSettingsRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IOpenSettingsRestService
- uid: OpenSettings.Services.Rest.Interfaces.IProviderRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IProviderRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IProviderRestService.html
  name: IProviderRestService
  nameWithType: IProviderRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IProviderRestService
- uid: OpenSettings.Services.Rest.Interfaces.ISettingClassRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ISettingClassRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ISettingClassRestService.html
  name: ISettingClassRestService
  nameWithType: ISettingClassRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ISettingClassRestService
- uid: OpenSettings.Services.Rest.Interfaces.ISettingHistoryRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.ISettingHistoryRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.ISettingHistoryRestService.html
  name: ISettingHistoryRestService
  nameWithType: ISettingHistoryRestService
  fullName: OpenSettings.Services.Rest.Interfaces.ISettingHistoryRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppSettingRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppSettingRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppSettingRestService.html
  name: IAppSettingRestService
  nameWithType: IAppSettingRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppSettingRestService
- uid: OpenSettings.Services.Rest.Interfaces.IAppTagRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IAppTagRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IAppTagRestService.html
  name: IAppTagRestService
  nameWithType: IAppTagRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IAppTagRestService
- uid: OpenSettings.Services.Rest.Interfaces.IUserRestService
  commentId: T:OpenSettings.Services.Rest.Interfaces.IUserRestService
  parent: OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.Services.Rest.Interfaces.IUserRestService.html
  name: IUserRestService
  nameWithType: IUserRestService
  fullName: OpenSettings.Services.Rest.Interfaces.IUserRestService
- uid: OpenSettings.Services.Rest.Interfaces
  commentId: N:OpenSettings.Services.Rest.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Rest.Interfaces
  nameWithType: OpenSettings.Services.Rest.Interfaces
  fullName: OpenSettings.Services.Rest.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Rest
    name: Rest
    href: OpenSettings.Services.Rest.html
  - name: .
  - uid: OpenSettings.Services.Rest.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Rest.Interfaces.html
