### YamlMime:ManagedReference
items:
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput
  commentId: T:OpenSettings.Models.Inputs.GenerateTokenForMachineInput
  id: GenerateTokenForMachineInput
  parent: OpenSettings.Models.Inputs
  children:
  - OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType
  - OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId
  - OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret
  - OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId
  langs:
  - csharp
  - vb
  name: GenerateTokenForMachineInput
  nameWithType: GenerateTokenForMachineInput
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput
  type: Class
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: GenerateTokenForMachineInput
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
    startLine: 4
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public class GenerateTokenForMachineInput
    content.vb: Public Class GenerateTokenForMachineInput
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId
  commentId: P:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId
  id: ClientId
  parent: OpenSettings.Models.Inputs.GenerateTokenForMachineInput
  langs:
  - csharp
  - vb
  name: ClientId
  nameWithType: GenerateTokenForMachineInput.ClientId
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: ClientId
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
    startLine: 6
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public Guid ClientId { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property ClientId As Guid
  overload: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId*
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret
  commentId: P:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret
  id: ClientSecret
  parent: OpenSettings.Models.Inputs.GenerateTokenForMachineInput
  langs:
  - csharp
  - vb
  name: ClientSecret
  nameWithType: GenerateTokenForMachineInput.ClientSecret
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: ClientSecret
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
    startLine: 8
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public Guid ClientSecret { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property ClientSecret As Guid
  overload: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret*
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId
  commentId: P:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId
  id: TenantId
  parent: OpenSettings.Models.Inputs.GenerateTokenForMachineInput
  langs:
  - csharp
  - vb
  name: TenantId
  nameWithType: GenerateTokenForMachineInput.TenantId
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: TenantId
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
    startLine: 10
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public Guid? TenantId { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Guid}
    content.vb: Public Property TenantId As Guid?
  overload: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId*
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType
  commentId: P:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType
  id: CallerType
  parent: OpenSettings.Models.Inputs.GenerateTokenForMachineInput
  langs:
  - csharp
  - vb
  name: CallerType
  nameWithType: GenerateTokenForMachineInput.CallerType
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType
  type: Property
  source:
    remote:
      path: src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
      branch: master
      repo: https://github.com/OpenSettings/open-settings.git
    id: CallerType
    path: ../../../open-settings/src/OpenSettings/Models/Inputs/GenerateTokenForMachineInput.cs
    startLine: 12
  assemblies:
  - OpenSettings
  namespace: OpenSettings.Models.Inputs
  syntax:
    content: public CallerType CallerType { get; set; }
    parameters: []
    return:
      type: OpenSettings.Models.CallerType
    content.vb: Public Property CallerType As CallerType
  overload: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType*
references:
- uid: OpenSettings.Models.Inputs
  commentId: N:OpenSettings.Models.Inputs
  href: OpenSettings.html
  name: OpenSettings.Models.Inputs
  nameWithType: OpenSettings.Models.Inputs
  fullName: OpenSettings.Models.Inputs
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  - name: .
  - uid: OpenSettings.Models.Inputs
    name: Inputs
    href: OpenSettings.Models.Inputs.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  - name: .
  - uid: OpenSettings.Models.Inputs
    name: Inputs
    href: OpenSettings.Models.Inputs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId*
  commentId: Overload:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId
  href: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.html#OpenSettings_Models_Inputs_GenerateTokenForMachineInput_ClientId
  name: ClientId
  nameWithType: GenerateTokenForMachineInput.ClientId
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientId
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret*
  commentId: Overload:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret
  href: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.html#OpenSettings_Models_Inputs_GenerateTokenForMachineInput_ClientSecret
  name: ClientSecret
  nameWithType: GenerateTokenForMachineInput.ClientSecret
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.ClientSecret
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId*
  commentId: Overload:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId
  href: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.html#OpenSettings_Models_Inputs_GenerateTokenForMachineInput_TenantId
  name: TenantId
  nameWithType: GenerateTokenForMachineInput.TenantId
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.TenantId
- uid: System.Nullable{System.Guid}
  commentId: T:System.Nullable{System.Guid}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid?
  nameWithType: Guid?
  fullName: System.Guid?
  spec.csharp:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
  spec.vb:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType*
  commentId: Overload:OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType
  href: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.html#OpenSettings_Models_Inputs_GenerateTokenForMachineInput_CallerType
  name: CallerType
  nameWithType: GenerateTokenForMachineInput.CallerType
  fullName: OpenSettings.Models.Inputs.GenerateTokenForMachineInput.CallerType
- uid: OpenSettings.Models.CallerType
  commentId: T:OpenSettings.Models.CallerType
  parent: OpenSettings.Models
  href: OpenSettings.Models.CallerType.html
  name: CallerType
  nameWithType: CallerType
  fullName: OpenSettings.Models.CallerType
- uid: OpenSettings.Models
  commentId: N:OpenSettings.Models
  href: OpenSettings.html
  name: OpenSettings.Models
  nameWithType: OpenSettings.Models
  fullName: OpenSettings.Models
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Models
    name: Models
    href: OpenSettings.Models.html
