### YamlMime:ManagedReference
items:
- uid: OpenSettings.AspNetCore.Controllers.v1
  commentId: N:OpenSettings.AspNetCore.Controllers.v1
  id: OpenSettings.AspNetCore.Controllers.v1
  children:
  - OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
  - OpenSettings.AspNetCore.Controllers.v1.AppInstancesController
  - OpenSettings.AspNetCore.Controllers.v1.AppSettingHistoriesController
  - OpenSettings.AspNetCore.Controllers.v1.AppSettingsController
  - OpenSettings.AspNetCore.Controllers.v1.AppTagsController
  - OpenSettings.AspNetCore.Controllers.v1.AppsController
  - OpenSettings.AspNetCore.Controllers.v1.AuthController
  - OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
  - OpenSettings.AspNetCore.Controllers.v1.LicensesController
  - OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
  - OpenSettings.AspNetCore.Controllers.v1.NotificationsController
  - OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
  - OpenSettings.AspNetCore.Controllers.v1.ProviderController
  - OpenSettings.AspNetCore.Controllers.v1.TokenController
  - OpenSettings.AspNetCore.Controllers.v1.UsersController
  langs:
  - csharp
  - vb
  name: OpenSettings.AspNetCore.Controllers.v1
  nameWithType: OpenSettings.AspNetCore.Controllers.v1
  fullName: OpenSettings.AspNetCore.Controllers.v1
  type: Namespace
  assemblies:
  - OpenSettings.AspNetCore
references:
- uid: OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
  href: OpenSettings.AspNetCore.Controllers.v1.AppGroupsController.html
  name: AppGroupsController
  nameWithType: AppGroupsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppGroupsController
- uid: OpenSettings.AspNetCore.Controllers.v1.AppInstancesController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppInstancesController
  href: OpenSettings.AspNetCore.Controllers.v1.AppInstancesController.html
  name: AppInstancesController
  nameWithType: AppInstancesController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppInstancesController
- uid: OpenSettings.AspNetCore.Controllers.v1.AppsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppsController
  href: OpenSettings.AspNetCore.Controllers.v1.AppsController.html
  name: AppsController
  nameWithType: AppsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppsController
- uid: OpenSettings.AspNetCore.Controllers.v1.AppSettingHistoriesController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppSettingHistoriesController
  href: OpenSettings.AspNetCore.Controllers.v1.AppSettingHistoriesController.html
  name: AppSettingHistoriesController
  nameWithType: AppSettingHistoriesController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppSettingHistoriesController
- uid: OpenSettings.AspNetCore.Controllers.v1.AppSettingsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppSettingsController
  href: OpenSettings.AspNetCore.Controllers.v1.AppSettingsController.html
  name: AppSettingsController
  nameWithType: AppSettingsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppSettingsController
- uid: OpenSettings.AspNetCore.Controllers.v1.AppTagsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AppTagsController
  href: OpenSettings.AspNetCore.Controllers.v1.AppTagsController.html
  name: AppTagsController
  nameWithType: AppTagsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AppTagsController
- uid: OpenSettings.AspNetCore.Controllers.v1.AuthController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.AuthController
  href: OpenSettings.AspNetCore.Controllers.v1.AuthController.html
  name: AuthController
  nameWithType: AuthController
  fullName: OpenSettings.AspNetCore.Controllers.v1.AuthController
- uid: OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
  href: OpenSettings.AspNetCore.Controllers.v1.IdentifiersController.html
  name: IdentifiersController
  nameWithType: IdentifiersController
  fullName: OpenSettings.AspNetCore.Controllers.v1.IdentifiersController
- uid: OpenSettings.AspNetCore.Controllers.v1.LicensesController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.LicensesController
  href: OpenSettings.AspNetCore.Controllers.v1.LicensesController.html
  name: LicensesController
  nameWithType: LicensesController
  fullName: OpenSettings.AspNetCore.Controllers.v1.LicensesController
- uid: OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
  href: OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController.html
  name: LocalSettingsController
  nameWithType: LocalSettingsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.LocalSettingsController
- uid: OpenSettings.AspNetCore.Controllers.v1.NotificationsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.NotificationsController
  href: OpenSettings.AspNetCore.Controllers.v1.NotificationsController.html
  name: NotificationsController
  nameWithType: NotificationsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.NotificationsController
- uid: OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
  href: OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController.html
  name: OpenSettingsController
  nameWithType: OpenSettingsController
  fullName: OpenSettings.AspNetCore.Controllers.v1.OpenSettingsController
- uid: OpenSettings.AspNetCore.Controllers.v1.ProviderController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.ProviderController
  href: OpenSettings.AspNetCore.Controllers.v1.ProviderController.html
  name: ProviderController
  nameWithType: ProviderController
  fullName: OpenSettings.AspNetCore.Controllers.v1.ProviderController
- uid: OpenSettings.AspNetCore.Controllers.v1.TokenController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.TokenController
  href: OpenSettings.AspNetCore.Controllers.v1.TokenController.html
  name: TokenController
  nameWithType: TokenController
  fullName: OpenSettings.AspNetCore.Controllers.v1.TokenController
- uid: OpenSettings.AspNetCore.Controllers.v1.UsersController
  commentId: T:OpenSettings.AspNetCore.Controllers.v1.UsersController
  href: OpenSettings.AspNetCore.Controllers.v1.UsersController.html
  name: UsersController
  nameWithType: UsersController
  fullName: OpenSettings.AspNetCore.Controllers.v1.UsersController
