### YamlMime:ManagedReference
items:
- uid: OpenSettings.Domains.Sql.Entities
  commentId: N:OpenSettings.Domains.Sql.Entities
  id: OpenSettings.Domains.Sql.Entities
  children:
  - OpenSettings.Domains.Sql.Entities.AppConfigurationSqlModel
  - OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
  - OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.AppInstanceSqlModel
  - OpenSettings.Domains.Sql.Entities.AppSettingClassSqlModel
  - OpenSettings.Domains.Sql.Entities.AppSettingHistorySqlModel
  - OpenSettings.Domains.Sql.Entities.AppSettingSqlModel
  - OpenSettings.Domains.Sql.Entities.AppSqlModel
  - OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.AppTagSqlModel
  - OpenSettings.Domains.Sql.Entities.DataProtectionKeySqlModel
  - OpenSettings.Domains.Sql.Entities.EntityBase`1
  - OpenSettings.Domains.Sql.Entities.GlobalConfigurationHistorySqlModel
  - OpenSettings.Domains.Sql.Entities.GlobalConfigurationSqlModel
  - OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
  - OpenSettings.Domains.Sql.Entities.LicenseSqlModel
  - OpenSettings.Domains.Sql.Entities.LockSqlModel
  - OpenSettings.Domains.Sql.Entities.LoginEntrySqlModel
  - OpenSettings.Domains.Sql.Entities.NotificationSqlModel
  - OpenSettings.Domains.Sql.Entities.ProviderRegistrySqlModel
  - OpenSettings.Domains.Sql.Entities.TenantSqlModel
  - OpenSettings.Domains.Sql.Entities.TenantUserMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
  - OpenSettings.Domains.Sql.Entities.UserGroupUserClaimMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleUserClaimMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserRoleUserGroupMappingSqlModel
  - OpenSettings.Domains.Sql.Entities.UserSqlModel
  langs:
  - csharp
  - vb
  name: OpenSettings.Domains.Sql.Entities
  nameWithType: OpenSettings.Domains.Sql.Entities
  fullName: OpenSettings.Domains.Sql.Entities
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Domains.Sql.Entities.AppConfigurationSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppConfigurationSqlModel
  href: OpenSettings.Domains.Sql.Entities.AppConfigurationSqlModel.html
  name: AppConfigurationSqlModel
  nameWithType: AppConfigurationSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppConfigurationSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.AppGroupSqlModel.html
  name: AppGroupSqlModel
  nameWithType: AppGroupSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppGroupSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel.html
  name: AppIdentifierMappingSqlModel
  nameWithType: AppIdentifierMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppIdentifierMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppInstanceSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppInstanceSqlModel
  href: OpenSettings.Domains.Sql.Entities.AppInstanceSqlModel.html
  name: AppInstanceSqlModel
  nameWithType: AppInstanceSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppInstanceSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppSettingClassSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppSettingClassSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.AppSettingClassSqlModel.html
  name: AppSettingClassSqlModel
  nameWithType: AppSettingClassSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppSettingClassSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppSettingHistorySqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppSettingHistorySqlModel
  href: OpenSettings.Domains.Sql.Entities.AppSettingHistorySqlModel.html
  name: AppSettingHistorySqlModel
  nameWithType: AppSettingHistorySqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppSettingHistorySqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppSettingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppSettingSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.AppSettingSqlModel.html
  name: AppSettingSqlModel
  nameWithType: AppSettingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppSettingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.AppSqlModel.html
  name: AppSqlModel
  nameWithType: AppSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel.html
  name: AppTagMappingSqlModel
  nameWithType: AppTagMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppTagMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.AppTagSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.AppTagSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.AppTagSqlModel.html
  name: AppTagSqlModel
  nameWithType: AppTagSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.AppTagSqlModel
- uid: OpenSettings.Domains.Sql.Entities.DataProtectionKeySqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.DataProtectionKeySqlModel
  href: OpenSettings.Domains.Sql.Entities.DataProtectionKeySqlModel.html
  name: DataProtectionKeySqlModel
  nameWithType: DataProtectionKeySqlModel
  fullName: OpenSettings.Domains.Sql.Entities.DataProtectionKeySqlModel
- uid: OpenSettings.Domains.Sql.Entities.EntityBase`1
  commentId: T:OpenSettings.Domains.Sql.Entities.EntityBase`1
  href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html
  name: EntityBase<TId>
  nameWithType: EntityBase<TId>
  fullName: OpenSettings.Domains.Sql.Entities.EntityBase<TId>
  nameWithType.vb: EntityBase(Of TId)
  fullName.vb: OpenSettings.Domains.Sql.Entities.EntityBase(Of TId)
  name.vb: EntityBase(Of TId)
  spec.csharp:
  - uid: OpenSettings.Domains.Sql.Entities.EntityBase`1
    name: EntityBase
    href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html
  - name: <
  - name: TId
  - name: '>'
  spec.vb:
  - uid: OpenSettings.Domains.Sql.Entities.EntityBase`1
    name: EntityBase
    href: OpenSettings.Domains.Sql.Entities.EntityBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TId
  - name: )
- uid: OpenSettings.Domains.Sql.Entities.GlobalConfigurationHistorySqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.GlobalConfigurationHistorySqlModel
  href: OpenSettings.Domains.Sql.Entities.GlobalConfigurationHistorySqlModel.html
  name: GlobalConfigurationHistorySqlModel
  nameWithType: GlobalConfigurationHistorySqlModel
  fullName: OpenSettings.Domains.Sql.Entities.GlobalConfigurationHistorySqlModel
- uid: OpenSettings.Domains.Sql.Entities.GlobalConfigurationSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.GlobalConfigurationSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.GlobalConfigurationSqlModel.html
  name: GlobalConfigurationSqlModel
  nameWithType: GlobalConfigurationSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.GlobalConfigurationSqlModel
- uid: OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.IdentifierSqlModel.html
  name: IdentifierSqlModel
  nameWithType: IdentifierSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.IdentifierSqlModel
- uid: OpenSettings.Domains.Sql.Entities.LicenseSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.LicenseSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.LicenseSqlModel.html
  name: LicenseSqlModel
  nameWithType: LicenseSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.LicenseSqlModel
- uid: OpenSettings.Domains.Sql.Entities.LockSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.LockSqlModel
  href: OpenSettings.Domains.Sql.Entities.LockSqlModel.html
  name: LockSqlModel
  nameWithType: LockSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.LockSqlModel
- uid: OpenSettings.Domains.Sql.Entities.LoginEntrySqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.LoginEntrySqlModel
  href: OpenSettings.Domains.Sql.Entities.LoginEntrySqlModel.html
  name: LoginEntrySqlModel
  nameWithType: LoginEntrySqlModel
  fullName: OpenSettings.Domains.Sql.Entities.LoginEntrySqlModel
- uid: OpenSettings.Domains.Sql.Entities.NotificationSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.NotificationSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.NotificationSqlModel.html
  name: NotificationSqlModel
  nameWithType: NotificationSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.NotificationSqlModel
- uid: OpenSettings.Domains.Sql.Entities.ProviderRegistrySqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.ProviderRegistrySqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.ProviderRegistrySqlModel.html
  name: ProviderRegistrySqlModel
  nameWithType: ProviderRegistrySqlModel
  fullName: OpenSettings.Domains.Sql.Entities.ProviderRegistrySqlModel
- uid: OpenSettings.Domains.Sql.Entities.TenantSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.TenantSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.TenantSqlModel.html
  name: TenantSqlModel
  nameWithType: TenantSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.TenantSqlModel
- uid: OpenSettings.Domains.Sql.Entities.TenantUserMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.TenantUserMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.TenantUserMappingSqlModel.html
  name: TenantUserMappingSqlModel
  nameWithType: TenantUserMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.TenantUserMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel.html
  name: UserClaimMappingSqlModel
  nameWithType: UserClaimMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserClaimMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserClaimSqlModel.html
  name: UserClaimSqlModel
  nameWithType: UserClaimSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserClaimSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel.html
  name: UserGroupMappingSqlModel
  nameWithType: UserGroupMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel.html
  name: UserGroupNotificationMappingSqlModel
  nameWithType: UserGroupNotificationMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupNotificationMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserGroupSqlModel.html
  name: UserGroupSqlModel
  nameWithType: UserGroupSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserGroupUserClaimMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserGroupUserClaimMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserGroupUserClaimMappingSqlModel.html
  name: UserGroupUserClaimMappingSqlModel
  nameWithType: UserGroupUserClaimMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserGroupUserClaimMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel.html
  name: UserNotificationMappingSqlModel
  nameWithType: UserNotificationMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserNotificationMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel.html
  name: UserRoleMappingSqlModel
  nameWithType: UserRoleMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserRoleSqlModel.html
  name: UserRoleSqlModel
  nameWithType: UserRoleSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleUserClaimMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleUserClaimMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserRoleUserClaimMappingSqlModel.html
  name: UserRoleUserClaimMappingSqlModel
  nameWithType: UserRoleUserClaimMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleUserClaimMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserRoleUserGroupMappingSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserRoleUserGroupMappingSqlModel
  href: OpenSettings.Domains.Sql.Entities.UserRoleUserGroupMappingSqlModel.html
  name: UserRoleUserGroupMappingSqlModel
  nameWithType: UserRoleUserGroupMappingSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserRoleUserGroupMappingSqlModel
- uid: OpenSettings.Domains.Sql.Entities.UserSqlModel
  commentId: T:OpenSettings.Domains.Sql.Entities.UserSqlModel
  parent: OpenSettings.Domains.Sql.Entities
  href: OpenSettings.Domains.Sql.Entities.UserSqlModel.html
  name: UserSqlModel
  nameWithType: UserSqlModel
  fullName: OpenSettings.Domains.Sql.Entities.UserSqlModel
- uid: OpenSettings.Domains.Sql.Entities
  commentId: N:OpenSettings.Domains.Sql.Entities
  href: OpenSettings.html
  name: OpenSettings.Domains.Sql.Entities
  nameWithType: OpenSettings.Domains.Sql.Entities
  fullName: OpenSettings.Domains.Sql.Entities
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Domains
    name: Domains
    href: OpenSettings.Domains.html
  - name: .
  - uid: OpenSettings.Domains.Sql
    name: Sql
    href: OpenSettings.Domains.Sql.html
  - name: .
  - uid: OpenSettings.Domains.Sql.Entities
    name: Entities
    href: OpenSettings.Domains.Sql.Entities.html
