### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  id: OpenSettings.Services.Interfaces
  children:
  - OpenSettings.Services.Interfaces.IAppConfigurationService
  - OpenSettings.Services.Interfaces.IAppGroupService
  - OpenSettings.Services.Interfaces.IAppIdentifierMappingService
  - OpenSettings.Services.Interfaces.IAppInstanceService
  - OpenSettings.Services.Interfaces.IAppService
  - OpenSettings.Services.Interfaces.IAppSettingClassService
  - OpenSettings.Services.Interfaces.IAppSettingHistoryService
  - OpenSettings.Services.Interfaces.IAppSettingService
  - OpenSettings.Services.Interfaces.IAppTagMappingService
  - OpenSettings.Services.Interfaces.IAppTagService
  - OpenSettings.Services.Interfaces.IAuthService
  - OpenSettings.Services.Interfaces.IDataChangeService
  - OpenSettings.Services.Interfaces.IGlobalConfigurationService
  - OpenSettings.Services.Interfaces.IGlobalConfigurationSqlService
  - OpenSettings.Services.Interfaces.IIdentifierService
  - OpenSettings.Services.Interfaces.IInstanceUrlResolverService
  - OpenSettings.Services.Interfaces.ILicenseService
  - OpenSettings.Services.Interfaces.ILocalSettingService
  - OpenSettings.Services.Interfaces.ILockService
  - OpenSettings.Services.Interfaces.INotificationService
  - OpenSettings.Services.Interfaces.IOpenSettingsMemoryCache
  - OpenSettings.Services.Interfaces.IOpenSettingsNotificationSyncTimedService
  - OpenSettings.Services.Interfaces.IOpenSettingsService
  - OpenSettings.Services.Interfaces.IPollingSettingTimedService
  - OpenSettings.Services.Interfaces.IProviderCoordinationTimedService
  - OpenSettings.Services.Interfaces.IProviderService
  - OpenSettings.Services.Interfaces.ISettings
  - OpenSettings.Services.Interfaces.ITokenRestService
  - OpenSettings.Services.Interfaces.ITokenService
  - OpenSettings.Services.Interfaces.IUserNotificationMappingService
  - OpenSettings.Services.Interfaces.IUserService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Interfaces.IAppConfigurationService
  commentId: T:OpenSettings.Services.Interfaces.IAppConfigurationService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppConfigurationService.html
  name: IAppConfigurationService
  nameWithType: IAppConfigurationService
  fullName: OpenSettings.Services.Interfaces.IAppConfigurationService
- uid: OpenSettings.Services.Interfaces.IAppGroupService
  commentId: T:OpenSettings.Services.Interfaces.IAppGroupService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppGroupService.html
  name: IAppGroupService
  nameWithType: IAppGroupService
  fullName: OpenSettings.Services.Interfaces.IAppGroupService
- uid: OpenSettings.Services.Interfaces.IAppIdentifierMappingService
  commentId: T:OpenSettings.Services.Interfaces.IAppIdentifierMappingService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppIdentifierMappingService.html
  name: IAppIdentifierMappingService
  nameWithType: IAppIdentifierMappingService
  fullName: OpenSettings.Services.Interfaces.IAppIdentifierMappingService
- uid: OpenSettings.Services.Interfaces.IAppInstanceService
  commentId: T:OpenSettings.Services.Interfaces.IAppInstanceService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppInstanceService.html
  name: IAppInstanceService
  nameWithType: IAppInstanceService
  fullName: OpenSettings.Services.Interfaces.IAppInstanceService
- uid: OpenSettings.Services.Interfaces.IAppService
  commentId: T:OpenSettings.Services.Interfaces.IAppService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppService.html
  name: IAppService
  nameWithType: IAppService
  fullName: OpenSettings.Services.Interfaces.IAppService
- uid: OpenSettings.Services.Interfaces.IAppSettingClassService
  commentId: T:OpenSettings.Services.Interfaces.IAppSettingClassService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppSettingClassService.html
  name: IAppSettingClassService
  nameWithType: IAppSettingClassService
  fullName: OpenSettings.Services.Interfaces.IAppSettingClassService
- uid: OpenSettings.Services.Interfaces.IAppSettingHistoryService
  commentId: T:OpenSettings.Services.Interfaces.IAppSettingHistoryService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppSettingHistoryService.html
  name: IAppSettingHistoryService
  nameWithType: IAppSettingHistoryService
  fullName: OpenSettings.Services.Interfaces.IAppSettingHistoryService
- uid: OpenSettings.Services.Interfaces.IAppSettingService
  commentId: T:OpenSettings.Services.Interfaces.IAppSettingService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppSettingService.html
  name: IAppSettingService
  nameWithType: IAppSettingService
  fullName: OpenSettings.Services.Interfaces.IAppSettingService
- uid: OpenSettings.Services.Interfaces.IAppTagMappingService
  commentId: T:OpenSettings.Services.Interfaces.IAppTagMappingService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppTagMappingService.html
  name: IAppTagMappingService
  nameWithType: IAppTagMappingService
  fullName: OpenSettings.Services.Interfaces.IAppTagMappingService
- uid: OpenSettings.Services.Interfaces.IAppTagService
  commentId: T:OpenSettings.Services.Interfaces.IAppTagService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAppTagService.html
  name: IAppTagService
  nameWithType: IAppTagService
  fullName: OpenSettings.Services.Interfaces.IAppTagService
- uid: OpenSettings.Services.Interfaces.IAuthService
  commentId: T:OpenSettings.Services.Interfaces.IAuthService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IAuthService.html
  name: IAuthService
  nameWithType: IAuthService
  fullName: OpenSettings.Services.Interfaces.IAuthService
- uid: OpenSettings.Services.Interfaces.IDataChangeService
  commentId: T:OpenSettings.Services.Interfaces.IDataChangeService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IDataChangeService.html
  name: IDataChangeService
  nameWithType: IDataChangeService
  fullName: OpenSettings.Services.Interfaces.IDataChangeService
- uid: OpenSettings.Services.Interfaces.IGlobalConfigurationService
  commentId: T:OpenSettings.Services.Interfaces.IGlobalConfigurationService
  href: OpenSettings.Services.Interfaces.IGlobalConfigurationService.html
  name: IGlobalConfigurationService
  nameWithType: IGlobalConfigurationService
  fullName: OpenSettings.Services.Interfaces.IGlobalConfigurationService
- uid: OpenSettings.Services.Interfaces.IGlobalConfigurationSqlService
  commentId: T:OpenSettings.Services.Interfaces.IGlobalConfigurationSqlService
  href: OpenSettings.Services.Interfaces.IGlobalConfigurationSqlService.html
  name: IGlobalConfigurationSqlService
  nameWithType: IGlobalConfigurationSqlService
  fullName: OpenSettings.Services.Interfaces.IGlobalConfigurationSqlService
- uid: OpenSettings.Services.Interfaces.IIdentifierService
  commentId: T:OpenSettings.Services.Interfaces.IIdentifierService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IIdentifierService.html
  name: IIdentifierService
  nameWithType: IIdentifierService
  fullName: OpenSettings.Services.Interfaces.IIdentifierService
- uid: OpenSettings.Services.Interfaces.IInstanceUrlResolverService
  commentId: T:OpenSettings.Services.Interfaces.IInstanceUrlResolverService
  href: OpenSettings.Services.Interfaces.IInstanceUrlResolverService.html
  name: IInstanceUrlResolverService
  nameWithType: IInstanceUrlResolverService
  fullName: OpenSettings.Services.Interfaces.IInstanceUrlResolverService
- uid: OpenSettings.Services.Interfaces.ILicenseService
  commentId: T:OpenSettings.Services.Interfaces.ILicenseService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ILicenseService.html
  name: ILicenseService
  nameWithType: ILicenseService
  fullName: OpenSettings.Services.Interfaces.ILicenseService
- uid: OpenSettings.Services.Interfaces.ILocalSettingService
  commentId: T:OpenSettings.Services.Interfaces.ILocalSettingService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ILocalSettingService.html
  name: ILocalSettingService
  nameWithType: ILocalSettingService
  fullName: OpenSettings.Services.Interfaces.ILocalSettingService
- uid: OpenSettings.Services.Interfaces.ILockService
  commentId: T:OpenSettings.Services.Interfaces.ILockService
  href: OpenSettings.Services.Interfaces.ILockService.html
  name: ILockService
  nameWithType: ILockService
  fullName: OpenSettings.Services.Interfaces.ILockService
- uid: OpenSettings.Services.Interfaces.INotificationService
  commentId: T:OpenSettings.Services.Interfaces.INotificationService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.INotificationService.html
  name: INotificationService
  nameWithType: INotificationService
  fullName: OpenSettings.Services.Interfaces.INotificationService
- uid: OpenSettings.Services.Interfaces.IOpenSettingsMemoryCache
  commentId: T:OpenSettings.Services.Interfaces.IOpenSettingsMemoryCache
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IOpenSettingsMemoryCache.html
  name: IOpenSettingsMemoryCache
  nameWithType: IOpenSettingsMemoryCache
  fullName: OpenSettings.Services.Interfaces.IOpenSettingsMemoryCache
- uid: OpenSettings.Services.Interfaces.IOpenSettingsNotificationSyncTimedService
  commentId: T:OpenSettings.Services.Interfaces.IOpenSettingsNotificationSyncTimedService
  href: OpenSettings.Services.Interfaces.IOpenSettingsNotificationSyncTimedService.html
  name: IOpenSettingsNotificationSyncTimedService
  nameWithType: IOpenSettingsNotificationSyncTimedService
  fullName: OpenSettings.Services.Interfaces.IOpenSettingsNotificationSyncTimedService
- uid: OpenSettings.Services.Interfaces.IOpenSettingsService
  commentId: T:OpenSettings.Services.Interfaces.IOpenSettingsService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IOpenSettingsService.html
  name: IOpenSettingsService
  nameWithType: IOpenSettingsService
  fullName: OpenSettings.Services.Interfaces.IOpenSettingsService
- uid: OpenSettings.Services.Interfaces.IPollingSettingTimedService
  commentId: T:OpenSettings.Services.Interfaces.IPollingSettingTimedService
  href: OpenSettings.Services.Interfaces.IPollingSettingTimedService.html
  name: IPollingSettingTimedService
  nameWithType: IPollingSettingTimedService
  fullName: OpenSettings.Services.Interfaces.IPollingSettingTimedService
- uid: OpenSettings.Services.Interfaces.IProviderCoordinationTimedService
  commentId: T:OpenSettings.Services.Interfaces.IProviderCoordinationTimedService
  href: OpenSettings.Services.Interfaces.IProviderCoordinationTimedService.html
  name: IProviderCoordinationTimedService
  nameWithType: IProviderCoordinationTimedService
  fullName: OpenSettings.Services.Interfaces.IProviderCoordinationTimedService
- uid: OpenSettings.Services.Interfaces.IProviderService
  commentId: T:OpenSettings.Services.Interfaces.IProviderService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IProviderService.html
  name: IProviderService
  nameWithType: IProviderService
  fullName: OpenSettings.Services.Interfaces.IProviderService
- uid: OpenSettings.Services.Interfaces.ISettings
  commentId: T:OpenSettings.Services.Interfaces.ISettings
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ISettings.html
  name: ISettings
  nameWithType: ISettings
  fullName: OpenSettings.Services.Interfaces.ISettings
- uid: OpenSettings.Services.Interfaces.ITokenRestService
  commentId: T:OpenSettings.Services.Interfaces.ITokenRestService
  href: OpenSettings.Services.Interfaces.ITokenRestService.html
  name: ITokenRestService
  nameWithType: ITokenRestService
  fullName: OpenSettings.Services.Interfaces.ITokenRestService
- uid: OpenSettings.Services.Interfaces.ITokenService
  commentId: T:OpenSettings.Services.Interfaces.ITokenService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.ITokenService.html
  name: ITokenService
  nameWithType: ITokenService
  fullName: OpenSettings.Services.Interfaces.ITokenService
- uid: OpenSettings.Services.Interfaces.IUserNotificationMappingService
  commentId: T:OpenSettings.Services.Interfaces.IUserNotificationMappingService
  href: OpenSettings.Services.Interfaces.IUserNotificationMappingService.html
  name: IUserNotificationMappingService
  nameWithType: IUserNotificationMappingService
  fullName: OpenSettings.Services.Interfaces.IUserNotificationMappingService
- uid: OpenSettings.Services.Interfaces.IUserService
  commentId: T:OpenSettings.Services.Interfaces.IUserService
  parent: OpenSettings.Services.Interfaces
  href: OpenSettings.Services.Interfaces.IUserService.html
  name: IUserService
  nameWithType: IUserService
  fullName: OpenSettings.Services.Interfaces.IUserService
- uid: OpenSettings.Services.Interfaces
  commentId: N:OpenSettings.Services.Interfaces
  href: OpenSettings.html
  name: OpenSettings.Services.Interfaces
  nameWithType: OpenSettings.Services.Interfaces
  fullName: OpenSettings.Services.Interfaces
  spec.csharp:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
  spec.vb:
  - uid: OpenSettings
    name: OpenSettings
    href: OpenSettings.html
  - name: .
  - uid: OpenSettings.Services
    name: Services
    href: OpenSettings.Services.html
  - name: .
  - uid: OpenSettings.Services.Interfaces
    name: Interfaces
    href: OpenSettings.Services.Interfaces.html
