### YamlMime:ManagedReference
items:
- uid: OpenSettings.Services.Rest
  commentId: N:OpenSettings.Services.Rest
  id: OpenSettings.Services.Rest
  children:
  - OpenSettings.Services.Rest.AppConfigurationRestService
  - OpenSettings.Services.Rest.AppGroupRestService
  - OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  - OpenSettings.Services.Rest.AppInstanceRestService
  - OpenSettings.Services.Rest.AppRestService
  - OpenSettings.Services.Rest.AppSettingClassRestService
  - OpenSettings.Services.Rest.AppSettingHistoryRestService
  - OpenSettings.Services.Rest.AppSettingRestService
  - OpenSettings.Services.Rest.AppTagMappingRestService
  - OpenSettings.Services.Rest.AppTagRestService
  - OpenSettings.Services.Rest.IdentifierRestService
  - OpenSettings.Services.Rest.LicenseRestService
  - OpenSettings.Services.Rest.NotificationRestService
  - OpenSettings.Services.Rest.OpenSettingsRestService
  - OpenSettings.Services.Rest.ProviderRestService
  - OpenSettings.Services.Rest.UsersRestService
  langs:
  - csharp
  - vb
  name: OpenSettings.Services.Rest
  nameWithType: OpenSettings.Services.Rest
  fullName: OpenSettings.Services.Rest
  type: Namespace
  assemblies:
  - OpenSettings
references:
- uid: OpenSettings.Services.Rest.AppConfigurationRestService
  commentId: T:OpenSettings.Services.Rest.AppConfigurationRestService
  href: OpenSettings.Services.Rest.AppConfigurationRestService.html
  name: AppConfigurationRestService
  nameWithType: AppConfigurationRestService
  fullName: OpenSettings.Services.Rest.AppConfigurationRestService
- uid: OpenSettings.Services.Rest.AppGroupRestService
  commentId: T:OpenSettings.Services.Rest.AppGroupRestService
  href: OpenSettings.Services.Rest.AppGroupRestService.html
  name: AppGroupRestService
  nameWithType: AppGroupRestService
  fullName: OpenSettings.Services.Rest.AppGroupRestService
- uid: OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  commentId: T:OpenSettings.Services.Rest.AppIdentifierMappingsRestService
  href: OpenSettings.Services.Rest.AppIdentifierMappingsRestService.html
  name: AppIdentifierMappingsRestService
  nameWithType: AppIdentifierMappingsRestService
  fullName: OpenSettings.Services.Rest.AppIdentifierMappingsRestService
- uid: OpenSettings.Services.Rest.AppInstanceRestService
  commentId: T:OpenSettings.Services.Rest.AppInstanceRestService
  href: OpenSettings.Services.Rest.AppInstanceRestService.html
  name: AppInstanceRestService
  nameWithType: AppInstanceRestService
  fullName: OpenSettings.Services.Rest.AppInstanceRestService
- uid: OpenSettings.Services.Rest.AppRestService
  commentId: T:OpenSettings.Services.Rest.AppRestService
  href: OpenSettings.Services.Rest.AppRestService.html
  name: AppRestService
  nameWithType: AppRestService
  fullName: OpenSettings.Services.Rest.AppRestService
- uid: OpenSettings.Services.Rest.AppSettingClassRestService
  commentId: T:OpenSettings.Services.Rest.AppSettingClassRestService
  href: OpenSettings.Services.Rest.AppSettingClassRestService.html
  name: AppSettingClassRestService
  nameWithType: AppSettingClassRestService
  fullName: OpenSettings.Services.Rest.AppSettingClassRestService
- uid: OpenSettings.Services.Rest.AppSettingHistoryRestService
  commentId: T:OpenSettings.Services.Rest.AppSettingHistoryRestService
  href: OpenSettings.Services.Rest.AppSettingHistoryRestService.html
  name: AppSettingHistoryRestService
  nameWithType: AppSettingHistoryRestService
  fullName: OpenSettings.Services.Rest.AppSettingHistoryRestService
- uid: OpenSettings.Services.Rest.AppSettingRestService
  commentId: T:OpenSettings.Services.Rest.AppSettingRestService
  href: OpenSettings.Services.Rest.AppSettingRestService.html
  name: AppSettingRestService
  nameWithType: AppSettingRestService
  fullName: OpenSettings.Services.Rest.AppSettingRestService
- uid: OpenSettings.Services.Rest.AppTagMappingRestService
  commentId: T:OpenSettings.Services.Rest.AppTagMappingRestService
  href: OpenSettings.Services.Rest.AppTagMappingRestService.html
  name: AppTagMappingRestService
  nameWithType: AppTagMappingRestService
  fullName: OpenSettings.Services.Rest.AppTagMappingRestService
- uid: OpenSettings.Services.Rest.AppTagRestService
  commentId: T:OpenSettings.Services.Rest.AppTagRestService
  href: OpenSettings.Services.Rest.AppTagRestService.html
  name: AppTagRestService
  nameWithType: AppTagRestService
  fullName: OpenSettings.Services.Rest.AppTagRestService
- uid: OpenSettings.Services.Rest.IdentifierRestService
  commentId: T:OpenSettings.Services.Rest.IdentifierRestService
  href: OpenSettings.Services.Rest.IdentifierRestService.html
  name: IdentifierRestService
  nameWithType: IdentifierRestService
  fullName: OpenSettings.Services.Rest.IdentifierRestService
- uid: OpenSettings.Services.Rest.LicenseRestService
  commentId: T:OpenSettings.Services.Rest.LicenseRestService
  href: OpenSettings.Services.Rest.LicenseRestService.html
  name: LicenseRestService
  nameWithType: LicenseRestService
  fullName: OpenSettings.Services.Rest.LicenseRestService
- uid: OpenSettings.Services.Rest.NotificationRestService
  commentId: T:OpenSettings.Services.Rest.NotificationRestService
  href: OpenSettings.Services.Rest.NotificationRestService.html
  name: NotificationRestService
  nameWithType: NotificationRestService
  fullName: OpenSettings.Services.Rest.NotificationRestService
- uid: OpenSettings.Services.Rest.OpenSettingsRestService
  commentId: T:OpenSettings.Services.Rest.OpenSettingsRestService
  href: OpenSettings.Services.Rest.OpenSettingsRestService.html
  name: OpenSettingsRestService
  nameWithType: OpenSettingsRestService
  fullName: OpenSettings.Services.Rest.OpenSettingsRestService
- uid: OpenSettings.Services.Rest.ProviderRestService
  commentId: T:OpenSettings.Services.Rest.ProviderRestService
  href: OpenSettings.Services.Rest.ProviderRestService.html
  name: ProviderRestService
  nameWithType: ProviderRestService
  fullName: OpenSettings.Services.Rest.ProviderRestService
- uid: OpenSettings.Services.Rest.UsersRestService
  commentId: T:OpenSettings.Services.Rest.UsersRestService
  href: OpenSettings.Services.Rest.UsersRestService.html
  name: UsersRestService
  nameWithType: UsersRestService
  fullName: OpenSettings.Services.Rest.UsersRestService
